# 0.24 — Quantum detection across **multiple ETF dates** (genAI-style, per date)

Run the entity-emergence detector in a **5-month window before each quantum investability date**,
each with a **fixed baseline before that window** (short window ⇒ fixed baseline ≈ point-in-time,
exactly like the genAI/CHAT run). One date per row instead of genAI's single CHAT date.

| date | 5-mo detection | baseline (24 mo before) | testable? |
|---|---|---|---|
| BQTUM index 2015-12-18 | Jul–Dec 2015 | 2013–2015 | yes |
| QTUM ETF 2018-09-04 | Apr–Sep 2018 | 2016–2018 | yes |
| CHPX ETF 2025-01-15 | Aug 2024–Jan 2025 | 2022–2024 | yes |
| QTUP ETF 2026-09-01 | Apr–Sep 2026 | 2024–2026 | **no** — no 2026 data (future) |

In [ ]:
import os, re
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUTPUT_DIR = _ROOT / "notebooks" / "output"
ENV_PATH = _ROOT / ".env"                       # OPENAI_API_KEY etc. for the llm_kept column
if ENV_PATH.exists():
    for _l in ENV_PATH.read_text().splitlines():
        _l = _l.strip()
        if "=" in _l and not _l.startswith("#"):
            _k, _, _v = _l.partition("="); os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))

# --- the dates to test ---
DATES = {"BQTUM_index": "2015-12-18", "QTUM_etf": "2018-09-04",
         "CHPX_etf": "2025-01-15", "QTUP_etf": "2026-09-01"}
DETECT_MONTHS = 5          # detection window length, before each date
BASELINE_MONTHS = 24       # fixed baseline length, immediately before the detection window
DATA_LAST_YEAR = 2025      # we have raw/terms only through 2025

# --- detector params (same as the entity-emergence pipeline) ---
FREQ="W-MON"; REP_HL=8; MIN_MENTIONS=3; DEGREE_MIN=8; PERSIST_WEEKS=2; CLUSTER_K=15; CLUSTER_MAX=0.60
TERM_STOP = set(ENGLISH_STOP_WORDS) | {"says","said","new","year","week","report","shares","stock",
    "jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"}
EVENT_STOP = {"collapse","rout","bankruptcy","bankrupt","fraud","lawsuit","sue","sues","sued","probe","hearing",
 "trial","court","arrest","arrested","resign","resigns","ban","bans","banned","outage","recall","default","slump",
 "slumps","plunge","plunges","crash","derailment","strike","quake","earthquake","protest","protests","unrest",
 "attack","war","sanctions","fine","fined","scandal","layoffs","layoff","pivot","halt","halts","delay","delays",
 "death","dies","killed","guilty","charges","charged","indicted","crisis","takeover","merger","deal","acquires",
 "acquire","buys","stake","ipo","listing","bond","bonds","notes","debt","offering","case","settlement","shortage",
 "shutdown","tumbles","soars","jumps","rises","falls","drops","gains","cuts","raises"}
def is_entity(t): return not any(tok in EVENT_STOP for tok in t.split())   # Stage 0 = generic blocklist
HINT = re.compile(r"\bionq\b|rigetti|\bd-wave\b|\bdwave\b|quantinuum|\bqubit|quantum comput|psiquantum|quantum advantage", re.I)
def normalize_terms(v): return v.tolist() if isinstance(v, np.ndarray) else (list(v) if isinstance(v,(list,tuple)) else [])
def filter_terms(ts): return [t for t in ts if len(t)>=3 and not any(tok in TERM_STOP for tok in t.split())]
def week_ts(w): return pd.Period(w, freq=FREQ).start_time
def clustcoef(P, adj):
    if len(P)<2: return 0.0
    tot=pairs=0
    for i in range(len(P)):
        for j in range(i+1,len(P)):
            tot+=1
            if P[j] in adj[P[i]]: pairs+=1
    return pairs/tot if tot else 0.0
print("config ok ·", DETECT_MONTHS, "mo detection ·", BASELINE_MONTHS, "mo baseline · dates:", list(DATES))

## Step 1 — Corpus: build per-year `terms` from raw (self-contained)

**No dependency on pre-existing files.** For any calendar year, if `terms_{year}.parquet` is
missing it is built from `raw_news_{year}.csv.xz` with the extractor below (keep Bloomberg wires →
dedupe → strip source prefixes → unigram+bigram phrases minus finance stopwords). First run builds
+ caches each year; later runs just load. This is the only source of `terms` — nothing else.

In [ ]:
import lzma
import polars as pl
# --- phrase extractor (identical to the code that built every terms_{year}.parquet) ---
WIRES = ["BN", "BFW", "BBO"]
TOKEN_RE  = re.compile(r"(?u)\b[a-z][a-z0-9\-]{2,}\b")
BIGRAM_RE = re.compile(r"(?u)\b[a-z][a-z0-9\-]{2,}\s+[a-z][a-z0-9\-]{2,}\b")
EXTRACT_STOP = set(ENGLISH_STOP_WORDS) | {
    "inc","plc","ltd","llc","corp","co","sa","ag","nv","group","holdings","ceo","cfo","says","said","new","year",
    "today","week","day","update","report","reports","results","announces","announced","shares","stock","stocks",
    "stake","dividend","q1","q2","q3","q4","fy","unit","mln","bln","pct","jan","feb","mar","apr","may","jun","jul",
    "aug","sep","oct","nov","dec","sales","deal","chief","cut","raised","raise","buy","sell","net","revenue","beat",
    "miss","forecast","outlook","business","market","markets","global","first","second","third","fourth","annual",
    "meeting","plans","plan","bn","march","april","june","july","august","september","october","november","december",
    "rated","hold","neutral","perform","outperform","underperform","overweight","underweight","equal-weight","lowers",
    "upgrade","downgrade","maintains","reiterates","est","eps","adj","sees","expects","names","appoints","hires",
    "officer","director","chairman","executive","promotes","tender","offering","offer","notes","bond","bonds","debt","bills","yield"}
def _strip_prefix(text):
    for _ in range(2):
        if ":" not in text: return text
        pre, _, rest = text.partition(":")
        if not pre or not rest or len(pre) > 30 or len(pre.split()) > 4: return text
        text = rest.strip()
    return text
def _extract(text):
    t = text.lower(); terms = set()
    for bg in BIGRAM_RE.findall(t):
        if all(tok not in EXTRACT_STOP for tok in bg.split()): terms.add(bg)
    for tok in TOKEN_RE.findall(t):
        if tok not in EXTRACT_STOP and len(tok) >= 3: terms.add(tok)
    return sorted(terms)

def build_year_terms(yr):
    """Build terms_{yr}.parquet from raw_news_{yr}.csv.xz if not already cached; return its path."""
    out = OUTPUT_DIR / f"terms_{yr}.parquet"
    if out.exists(): return out
    raw = _ROOT / "data" / "raw" / f"raw_news_{yr}.csv.xz"
    if not raw.exists(): raise FileNotFoundError(f"no raw news for {yr}: {raw}")
    with lzma.open(raw, "rb") as f:
        d = (pl.scan_csv(f, infer_schema_length=10_000)
             .select(["Headline", "CaptureTime", "WireName"])
             .filter(pl.col("WireName").is_in(WIRES) & pl.col("Headline").is_not_null())
             .with_columns(pl.col("CaptureTime").str.to_datetime(time_zone="UTC", strict=False))
             .collect()).to_pandas()
    d["date"] = pd.to_datetime(d["CaptureTime"]).dt.tz_localize(None)
    d = d[d.date.dt.year == yr].dropna(subset=["Headline"]).drop_duplicates("Headline")
    d["Headline"] = d["Headline"].map(_strip_prefix)
    d = d[d.Headline.str.split().map(len) >= 4].reset_index(drop=True)
    d["terms"] = [_extract(h) for h in d["Headline"]]
    d[["Headline", "date", "terms"]].to_parquet(out, index=False)
    print(f"  built terms_{yr}.parquet ({len(d):,} headlines)")
    return out

def load_corpus(y0, y1):
    """Full [Headline, date, terms] for calendar years [y0, y1] — building any missing year from raw."""
    parts = []
    for yr in range(y0, y1 + 1):
        build_year_terms(yr)
        parts.append(pd.read_parquet(OUTPUT_DIR / f"terms_{yr}.parquet")[["Headline", "date", "terms"]])
    df = pd.concat(parts, ignore_index=True)
    df["date"] = pd.to_datetime(df["date"]).dt.normalize()
    return df
print("self-contained corpus loader ready (builds terms_{year}.parquet from raw on demand)")

## Step 2 — The detector (one row per week × emerging entity)

For each week in the window the detector lists every **novel** entity (≥3 mentions, not an event word),
its **partner words** that week, and the per-week measures: `mentions`, `degree` (how many other words it
co-appears with), `clustering` (1.0 = one tight story, →0 = a bridge across many stories).

In [ ]:
def detect(news, baseline_end, ds, de):
    df = news.copy()
    df["terms_f"] = df["terms"].map(normalize_terms).map(filter_terms)
    df["week"] = df["date"].dt.to_period(FREQ).astype(str)
    baseline_terms = set()
    for tl in df.loc[df.date <= baseline_end, "terms_f"]: baseline_terms.update(tl)   # fixed baseline
    disc = [w for w in sorted(df["week"].unique(), key=week_ts) if ds <= week_ts(w) <= de]
    rows = []
    for week in disc:
        grp = df.loc[df.week == week]
        twc, adj = Counter(), defaultdict(Counter)
        for tl in grp["terms_f"]:
            s = set(tl)
            for t in s: twc[t] += 1
            for a, b in combinations(sorted(s), 2): adj[a][b]+=1; adj[b][a]+=1
        for t, cnt in twc.items():
            if t in baseline_terms or cnt < MIN_MENTIONS or not is_entity(t): continue   # novel + support + entity
            epart = [p for p,_ in adj[t].most_common() if is_entity(p)]; P = epart[:CLUSTER_K]
            reps = [hl for hl,tl in zip(grp["Headline"],grp["terms_f"]) if t in set(tl)][:REP_HL]
            rows.append({"week":week, "anchor":t, "partners":", ".join(epart[:8]),
                         "mentions":int(cnt), "degree":len(epart), "clustering":round(clustcoef(P,adj),3),
                         "subgraph":[t]+P[:10], "reps":reps, "example":reps[0] if reps else ""})
    return pd.DataFrame(rows)

def promotion_week(sub):
    """First week an anchor graduates: caught >=PERSIST_WEEKS, degree at a new high, median clustering a bridge."""
    sub = sub.sort_values("week", key=lambda s: s.map(week_ts))
    wk, deg, clu = list(sub.week), list(sub.degree), list(sub.clustering)
    for i in range(len(wk)):
        if (i+1) >= PERSIST_WEEKS and deg[i] >= max(deg[:i] or [0]) and float(np.median(clu[:i+1])) <= CLUSTER_MAX:
            return wk[i]
    return None
print("detect + promotion_week ready")

## Step 3 — LLM filter (fills the `llm_kept` column)

In the pipeline the LLM only ever judges **promoted** entities — it's a conservative gate that *removes*
clusters that are clearly a single-company event / a macro aggregate / wire boilerplate, and keeps anything
that looks like a real multi-actor technology theme. So `llm_kept` is only defined for promoted rows.

In [ ]:
from pydantic import BaseModel
from typing import Literal
REJECT_SYS = ("You are a conservative FILTER that REMOVES clusters of news headlines that are NOT emerging themes. "
 "You never decide what IS a theme; only flag clusters that CLEARLY are: 1. single_entity_event, "
 "2. macro_market_aggregate, 3. boilerplate_wire. If unclear, KEEP. KEEP anything describing a SPECIFIC "
 "technological/industrial/product development across multiple actors.")
class Reject(BaseModel):
    verdict: Literal["keep","reject"]; category: Literal["single_entity_event","macro_market_aggregate","boilerplate_wire","none"]; reason: str
_client = None
def llm_keep(subgraph, headlines):
    """Return True (keep) / False (reject); None if no API key configured."""
    global _client
    if not os.environ.get("OPENAI_API_KEY"): return None
    from openai import OpenAI
    if _client is None: _client = OpenAI(api_key=os.environ["OPENAI_API_KEY"], base_url=os.environ.get("OPENAI_BASE") or None)
    user = "Cluster entities: " + ", ".join(subgraph[:14]) + "\nHeadlines:\n" + "\n".join(f"- {h}" for h in headlines[:8]) + "\n\nClassify this cluster."
    r = _client.beta.chat.completions.parse(model=os.environ.get("OPENAI_DEFAULT_MODEL","gpt-4o-mini"), temperature=0,
        response_format=Reject, messages=[{"role":"system","content":REJECT_SYS},{"role":"user","content":user}])
    return r.choices[0].message.parsed.verdict == "keep"
print("llm_keep ready ·", "API key found" if os.environ.get("OPENAI_API_KEY") else "NO API key (llm_kept stays blank)")

## Step 4 — One dataframe per target date

`DFS[date]` is a tidy table: **one row per (week, emerging entity)**, sorted by week then degree.
Columns — `partners` (the other words), then the measures: numeric `mentions / degree / clustering`,
binary `is_quantum / caught / promoted / llm_kept`, plus an `example` headline. Each is saved to
`quantum_weekly_<date>.{parquet,csv}`. The LLM runs only on promoted rows (capped at `LLM_MAX`).

In [ ]:
LLM_MAX = 25
COLS = ["week","anchor","partners","mentions","degree","clustering","is_quantum","caught","promoted","llm_kept","example"]
DFS, summary = {}, []
for name, ds_str in DATES.items():
    D = pd.Timestamp(ds_str)
    det_start  = (D - pd.DateOffset(months=DETECT_MONTHS)).normalize()
    base_start = (det_start - pd.DateOffset(months=BASELINE_MONTHS)).normalize()
    if D.year > DATA_LAST_YEAR:                                   # QTUP — no data yet
        DFS[name] = pd.DataFrame(columns=COLS)
        summary.append({"date":name,"when":D.date(),"rows":0,"caught":0,"promoted":0,"quantum_rows":0,"status":"no data (future)"})
        print(f"{name} ({D.date()}): SKIP — needs {D.year} data we don't have"); continue

    corpus = load_corpus(base_start.year, D.year)
    corpus = corpus[(corpus.date >= base_start) & (corpus.date <= D)]
    R = detect(corpus, baseline_end=det_start, ds=det_start, de=D)

    # --- per-row measures ---
    R["is_quantum"] = R["anchor"].str.contains(HINT, na=False)
    R["caught"]     = (R.mentions >= MIN_MENTIONS) & (R.degree >= DEGREE_MIN)
    R["promoted"]   = False
    for a, sub in R[R.caught].groupby("anchor"):                  # mark the graduation week per anchor
        pw = promotion_week(sub)
        if pw is not None: R.loc[(R.anchor == a) & (R.week == pw), "promoted"] = True

    # --- llm_kept only on promoted rows (the pipeline's last gate) ---
    R["llm_kept"] = pd.NA
    prom_idx = list(R.index[R.promoted])
    for i in prom_idx[:LLM_MAX]:
        R.at[i, "llm_kept"] = llm_keep(R.at[i,"subgraph"], R.at[i,"reps"])

    out = R.sort_values(["week","degree"], ascending=[True, False])[COLS].reset_index(drop=True)
    DFS[name] = out
    out.to_parquet(OUTPUT_DIR / f"quantum_weekly_{name}.parquet", index=False)
    out.drop(columns=[]).to_csv(OUTPUT_DIR / f"quantum_weekly_{name}.csv", index=False)
    summary.append({"date":name,"when":D.date(),"rows":len(out),"caught":int(out.caught.sum()),
                    "promoted":int(out.promoted.sum()),"quantum_rows":int(out.is_quantum.sum()),"status":"ok"})
    print(f"{name} ({D.date()}): {len(out):,} rows · {int(out.caught.sum()):,} caught · "
          f"{int(out.promoted.sum())} promoted · {int(out.is_quantum.sum())} quantum rows  -> quantum_weekly_{name}.csv")
print("\nSUMMARY"); print(pd.DataFrame(summary).to_string(index=False))

## How an entity gets selected — the funnel

Everything below is computed **per week**, from that week's headlines. An entity must pass four gates in order:

`candidates → caught → promoted → llm_kept`

### 1 · Candidates — *novel, supported, entity-like*

For each week in the window:

- Each headline already carries its `terms` (unigram + bigram phrases, stopwords stripped — extracted once per year and cached). `filter_terms` drops anything under 3 characters or containing a stopword.
- We build the week's **co-occurrence graph**: every pair of terms sharing a headline becomes an edge (`adj`), and each term accumulates a `mentions` count (`twc`).

A term `t` is emitted as a candidate row only if it clears **three entry gates**:

| gate | rule | what it removes |
|---|---|---|
| **novel** | `t ∉ baseline_terms` — never seen before the window (headlines dated ≤ `baseline_end`) | anything already established |
| **support** | `mentions ≥ MIN_MENTIONS` (3) | one-off noise |
| **entity** | `is_entity(t)` — no token in the `EVENT_STOP` blocklist | events: `collapse`, `ipo`, `merger`, … |

Each surviving row stores its measures: `mentions`, `degree`, `clustering`, `partners` (top-8 neighbours) and a few `example` headlines.

### 2 · caught — *connected enough this week*

A per-row test: `caught = (mentions ≥ 3) AND (degree ≥ DEGREE_MIN=8)`. Support is already met, so the binding condition is **`degree ≥ 8`** — the anchor shares a headline with at least 8 distinct other entities this week.

- **`degree`** = number of distinct entity-neighbours of `t`.
- **`clustering`** = among `t`'s top-15 neighbours, the fraction of neighbour-*pairs* that also co-occur with each other. **`≈1.0` = one tight story; `→0` = a hub bridging separate stories.**

### 3 · promoted — *persists, grows, bridges*

Here we shift from per-week to **per-anchor, across weeks**. We sort an anchor's caught weeks in time and promote it at the **first week** where all three signals hold:

| signal | rule | meaning |
|---|---|---|
| **persist** | caught for ≥ `PERSIST_WEEKS` (2) | not a one-week blip |
| **grow** | `degree` at a new high vs. earlier weeks | reach is expanding |
| **bridge** | median `clustering` so far ≤ `CLUSTER_MAX` (0.60) | spans many stories, not a single-event clique |

That week is stamped `promoted = True`. This is the decisive cut — for CHPX, **4,217 caught → 43 promoted**.

### 4 · llm_kept — *survives the reject filter* (final gate)

Run only on the top `LLM_MAX` (25) promoted clusters per date:

- **Input** — the cluster's entities (`subgraph` = anchor + top partners) plus a handful of `example` headlines.
- **Role** (`REJECT_SYS`) — a deliberately *conservative* filter: reject **only** if the cluster is clearly a (1) single-entity event, (2) macro / market aggregate, or (3) wire boilerplate; **if unsure, keep**; always keep a specific technological / industrial development spanning *multiple actors*.
- **Output** — `verdict ∈ {keep, reject}` → `llm_kept = (verdict == "keep")`. `None` means no API key, or the cluster fell outside the top-25 judged.

**Finally selected = `llm_kept == True`** — i.e. it passed all four gates.

> ⚠️ **This last gate is currently the unreliable one.** It rejected *ChatGPT* at its promotion week despite a textbook emergence (degree 15 → 119 over 20 weeks, ~4 months before the CHAT ETF). So the zero "finally selected" count is a filter problem, **not** a detection failure — gates 1–3 work.

## Step 4b — Position at each funnel step (ranking columns)

Adds, to every `DFS[date]`, where each anchor sits at each gate (lower rank = stronger):

- `rank_candidate` — by `mentions` among **that week's candidates** (step 1)
- `rank_caught` — by `degree` among **that week's caught** anchors (step 2; `<NA>` if not caught)
- `rank_promoted` — by `degree` among the **window's promoted** anchors (step 3; `<NA>` if not promoted). This is the order they're fed to the LLM.
- `llm_judged` — `True` if `rank_promoted ≤ LLM_MAX` (actually sent to the LLM)

In [31]:
# Position at each funnel step — add rank columns to every DFS[date], then re-save.
for name, _df in list(DFS.items()):
    if _df.empty: continue
    df = _df.copy()
    df["rank_candidate"] = df.groupby("week")["mentions"].rank(ascending=False, method="min").astype("Int64")  # step 1
    df["rank_caught"] = pd.Series(pd.NA, index=df.index, dtype="Int64")                                         # step 2
    cr = df[df.caught].groupby("week")["degree"].rank(ascending=False, method="min")
    df.loc[cr.index, "rank_caught"] = cr.astype(int)
    df["rank_promoted"] = pd.Series(pd.NA, index=df.index, dtype="Int64")                                       # step 3
    pm = df[df.promoted].sort_values("degree", ascending=False)
    df.loc[pm.index, "rank_promoted"] = list(range(1, len(pm) + 1))
    df["llm_judged"] = df["rank_promoted"].notna() & (df["rank_promoted"] <= LLM_MAX)                           # step 4 gate
    DFS[name] = df
    df.to_parquet(OUTPUT_DIR / f"quantum_weekly_{name}.parquet", index=False)
    df.to_csv(OUTPUT_DIR / f"quantum_weekly_{name}.csv", index=False)
    print(f"{name}: +rank columns · promoted {int(df.promoted.sum())} · sent to LLM {int(df.llm_judged.sum())}")
_ex = next((d for d in DFS.values() if not d.empty), None)
if _ex is not None: print("\ncolumns now:", list(_ex.columns))

BQTUM_index: +rank columns · promoted 99 · sent to LLM 25
QTUM_etf: +rank columns · promoted 92 · sent to LLM 25
CHPX_etf: +rank columns · promoted 43 · sent to LLM 25

columns now: ['week', 'anchor', 'partners', 'mentions', 'degree', 'clustering', 'is_quantum', 'caught', 'promoted', 'llm_kept', 'example', 'rank_candidate', 'rank_caught', 'rank_promoted', 'llm_judged']

## Step 5 — For each date, each week: the top-K anchors with **all columns**

`WEEKLY[date]` keeps, for every week in that date's window, the `PER_WEEK` highest-`degree` anchors,
with **every** column — `partners` (the other words), the numeric measures (`mentions`, `degree`,
`clustering`), the binary flags (`is_quantum`, `caught`, `promoted`, `llm_kept`), and an `example`
headline. Each date renders as its own table; the full untrimmed table is still `DFS[date]` / the CSV.

In [32]:
from IPython.display import display
PER_WEEK = 10        # top anchors to show FOR EACH WEEK (ranked by degree)
ALLCOLS = ["week","anchor","partners","mentions","degree","clustering","is_quantum","caught","promoted","llm_kept","example"]
pd.set_option("display.max_colwidth", 55); pd.set_option("display.max_rows", 800); pd.set_option("display.width", 240)
WEEKLY = {}
for name in DATES:
    df = DFS[name]
    if df.empty:
        print(f"### {name}: no data (future date)"); continue
    wk = (df.sort_values(["week","degree"], ascending=[True, False])
            .groupby("week", sort=True).head(PER_WEEK).reset_index(drop=True))
    WEEKLY[name] = wk
    wk[ALLCOLS].to_csv(OUTPUT_DIR / f"quantum_weekly_top{PER_WEEK}_{name}.csv", index=False)
    print(f"### {name} — top {PER_WEEK} anchors PER WEEK · {wk.week.nunique()} weeks · "
          f"{int(df.is_quantum.sum())} quantum row(s) in full table")
    qr = df[df.is_quantum].sort_values("week")          # PINNED: always show quantum, even if below the top-K
    if len(qr):
        print("  ↓ quantum rows (pinned — shown regardless of degree rank):")
        display(qr[ALLCOLS])
    display(wk[ALLCOLS])

### BQTUM_index — top 10 anchors PER WEEK · 22 weeks · 0 quantum row(s) in full table

                      week                anchor                                                partners  mentions  degree  clustering  is_quantum  caught  promoted llm_kept                                                 example
0    2015-07-21/2015-07-27                  dnya  cebus, danya, danya cebus, ils, loss, shekels, inco...        27      70       0.619       False    True     False     <NA>  *DANYA CEBUS SAYS CONTRACT WORTH ABOUT 600 MLN SHEK...
1    2015-07-21/2015-07-27       american colony  american, colony, israel, project, amcl, sale, chan...        15      52       0.629       False    True     False     <NA>  *AMERICAN COLONY TO TAKE 61M ILS 2Q CHARGE FOR ASSE...
2    2015-07-21/2015-07-27     dongwon financial  dongwon, financial, korea, earnings, table, south, ...        15      52       0.638       False    True     False     <NA>  Dongwon Financial Holdings Shares Drop in South Kor...
3    2015-07-21/2015-07-27             technivie  abbvie, approval, fda, gets, chronic, hepatitis, ch...        15      46       0.590       False    True     False     <NA>         TECHNIVIE & VIEKIRA PARK ARE MARKETED BY ABBVIE
4    2015-07-21/2015-07-27               austrac  tabcorp, proceedings, matters, tah, brought, civil,...        11      38       0.410       False    True     False     <NA>                     AUSTRAC PROCEEDINGS AGAINST TABCORP
5    2015-07-21/2015-07-27                 tsavo  media, cyberplex, tsavo media, committee, pact, alt...        12      37       0.533       False    True     False     <NA>  *TSAVO MEDIA SAYS COMMITTEE FORMED TO REVIEW ALTERN...
6    2015-07-21/2015-07-27              conpharm     table, loss, sk0, loss sk0, share, pretax, shr, sk1        20      36       0.648       False    True     False     <NA>  *CONPHARM 1H OP PROFIT SK722,000 VS SK947,000      ...
7    2015-07-21/2015-07-27                 gavis  lupin, expand, generic, products, generics, million...        17      36       0.229       False    True     False     <NA>     *LUPIN ACQUIRES GAVIS TO EXPAND US GENERIC BUSINESS
8    2015-07-21/2015-07-27             wah shing  shing, wah, declares, holding, international, intl,...         8      35       0.562       False    True     False     <NA>  Wah Shing's Hui Discusses Strategy, Toy Market & China
9    2015-07-21/2015-07-27           burst media  burst, media, cyberplex, approach, acquisition, cor...         7      35       0.590       False    True     False     <NA>  *CYBERPLEX INC. PROPOSES ACQUISITION OF BURST MEDIA...
10   2015-07-28/2015-08-03               rugeley  power, international, international power, plant, r...        80     182       0.752       False    True     False     <NA>  International Power’s Rugeley, U.K. Coal Unit Halts...
11   2015-07-28/2015-08-03               aislive  lng, grain, shows, aislive shows, isle, tanker, ais...        65     105       0.905       False    True     False     <NA>  LNG Tanker Methania Due in Zeebrugge Dec. 16, AISLi...
12   2015-07-28/2015-08-03               benzina  unipetrol, stations, czech, unip, update1, gas, sha...        30      99       0.629       False    True     False     <NA>  *UNIPETROL'S BENZINA AIMS TO HAVE 440 FILLING STATI...
13   2015-07-28/2015-08-03                  niif  fund, infra, india, fund niif, india infra, focused...        21      97       0.638       False    True     False     <NA>     NIIF IS LIKE SOVEREIGN WEALTH FUND FOCUSED ON INFRA
14   2015-07-28/2015-08-03              publigaz  suez, distrigaz, fluxys, eni, gdf, gdf suez, agree,...        28      91       0.724       False    True     False     <NA>  *GDF SUEZ SAYS ELECTRABEL, PUBLIGAZ SOLD FLUXYS FOR...
15   2015-07-28/2015-08-03   odakyu construction  construction, odakyu, earnings, yen, daiwa, house, ...        60      88       0.752       False    True     False     <NA>  Odakyu Construction Co Ltd 1Q Group Net Income 217....
16   2015-07-28/2015-08-03                 touat  gdf, field, algeria, gdf suez, suez, gas, sonatrach...        24      83       0.771       False    True     False     <NA>  GDF Suez Drills at Touat in Algeria for Biggest E&P...
17   2015-07-28/2015-08-03               spolana  unipetrol, anwil, sale, koruna, spolana sale, bid, ...        23      79       0.476       False    True     False     <NA>  Orlen May Sell Anwil, Spolana, Unipetrol Fertilizer...
18   2015-07-28/2015-08-03                kaucuk  unipetrol, dwory, pkn, agrees, unipetrol agrees, sa...        19      69       0.486       False    True     False     <NA>  *UNIPETROL SAYS KAUCUK UNIT CHARGE MUST BE INCREASE...
19   2015-07-28/2015-08-03       unipetrol price  price, unipetrol, estimate, koruna, komercni, share...        35      67       0.695       False    True     False     <NA>  Unipetrol Price Estimate Lowered to 145 Koruna at K...
20   2015-08-04/2015-08-10                 meego  nokia, nok1v, symbian, intel, platform, savander, w...        66     225       0.695       False    True     False     <NA>  *VODDLER LAUNCHES MOVIE-APP FOR NOKIA MEEGO PLATFOR...
21   2015-08-04/2015-08-10           nokia price  nokia, price, target, nok1v, estimate, ubs, eu27, bank       161     170       0.886       False    True     False     <NA>  *NOKIA PRICE EST. RAISED TO EU10 FROM EU6.7 AT RBS ...
22   2015-08-04/2015-08-10                 obrem  micrel, mcrl, capital, obrem capital, holder, micre...        54     143       0.724       False    True     False     <NA>  *MICREL BUYS 1.6M SHRS FROM OBREM                  ...
23   2015-08-04/2015-08-10                   wp7  nokia, phone, microsoft, wp7 phone, lower, opportun...        23     100       0.590       False    True     False     <NA>  *NOKIA SAYS GREATEST SMARTPHONE GROWTH OPPORTUNITIE...
24   2015-08-04/2015-08-10                vereit  shr, ffo, exposure, negative, affo, asset, non-cont...        31      99       0.333       False    True     False     <NA>                            *VEREIT™ 2Q ADJ. FFO 22C/SHR
25   2015-08-04/2015-08-10             nokia evp  evp, nokia, speaking, espoo, finland, torres, spoke...        24      81       0.714       False    True     False     <NA>  *NOKIA EVP SALES COLIN GILES SPEAKING AT HONG KONG ...
26   2015-08-04/2015-08-10               voddler  nokia, app, symbian, lumia, nokia lumia, standard, ...        17      77       0.581       False    True     False     <NA>  *NOKIA INTRODUCES VODDLER VIDEO-ON-DEMAND SERVICE F...
27   2015-08-04/2015-08-10                  n900  nokia, nok1v, shipments, meego, support, handset, n...        21      72       0.543       False    True     False     <NA>  *NOKIA SAYS WON'T PROVIDE MEEGO SUPPORT FOR N900 TO...
28   2015-08-04/2015-08-10           nokia sells  nokia, sells, metacarta, million, cash, cash wanes,...        19      71       0.533       False    True     False     <NA>  Nokia Sells 750 Million Euros of Convertibles as Ca...
29   2015-08-04/2015-08-10              kochikar  nokia, apps, ovi, feature, people, phone, phones, t...        18      68       0.600       False    True     False     <NA>  *NOKIA DEVELOPER RELATIONS CHIEF PURNIMA KOCHIKAR S...
30   2015-08-11/2015-08-17         tianjin blast  blast, tianjin, china, disruption, iron, iron ore, ...        26      96       0.648       False    True     False     <NA>  *CHINA'S TIANJIN BLAST DEATH TOLL RISES TO 14: CCTV...
31   2015-08-11/2015-08-17     china devaluation  china, devaluation, impact, low, einhorn, gain, gre...        19      94       0.629       False    True     False     <NA>  Europe Index Futures Signal Stocks to Fall on China...
32   2015-08-11/2015-08-17    suomen terveystalo  suomen, terveystalo, sut1v, eu0, profit, loss, shar...        36      73       0.495       False    True     False     <NA>  *SUOMEN TERVEYSTALO BOARD APPROVES RIGHTS ISSUE    ...
33   2015-08-11/2015-08-17            yuan shock  shock, yuan, china, dollar, boosts, boosts dollar, ...        11      63       0.790       False    True     False     <NA>  China’s Yuan Shock Boosts Dollar as Commodity Curre...
34   2015-08-11/2015-08-17        tianjin blasts  blasts, tianjin, china, damages, toll, extent, ford...        16      61       0.619       False    True     False     <NA>  *MAERSK UNABLE TO ASCERTAIN EXTENT OF DAMAGE IN TIA...
35   2015-08-11/2015-08-17                 sut1v  terveystalo, suomen, suomen terveystalo, eu0, healt...        31      59       0.438       False    True     False     <NA>  *TERVEYSTALO COMMENTS ON ARBITRAL TRIBUNAL DECISION...
36   2015-08-11/2015-08-17           weissgerber  greek, german, greece, imf, needs, germany, imf nee...        13      56       0.571       False    True      True    False  *GREEK BRIDGE LOAN REMAINS ON THE TABLE, WEISSGERBE...
37   2015-08-11/2015-08-17              plus-tps  canal, canal plus-tps, french, regulator, vivendi, ...        12      53       0.648       False    True     False     <NA>  French Antitrust Agency Seeks Comment on Canal Plus...
38   2015-08-11/2015-08-17        china devalues  china, devalues, yuan, declines, decades, currency,...        15      49       0.771       False    True     False     <NA>  China Devalues Yuan by Most in Two Decades to Comba...
39   2015-08-11/2015-08-17        canal plus-tps  canal, plus-tps, french, regulator, antitrust, fren...         8      47       0.743       False    True     False     <NA>  French Antitrust Agency Seeks Comment on Canal Plus...
40   2015-08-18/2015-08-24                 addyi  fda, sprout, pharmaceuticals, sprout pharmaceutical...        17      77       0.400       False    True     False     <NA>         *SPROUT PHARMACEUTICALS’S ADDYI APPROVED BY FDA
41   2015-08-18/2015-08-24               azd3480  astrazeneca, targacept, primary, meet, phase, azn, ...        20      67       0.590       False    True     False     <NA>  *TARGACEPT ACTIVE COMPARATOR DONEPEZIL, AZD3480 NOT...
42   2015-08-18/2015-08-24         tianjin blast  blast, tianjin, impact, china, yuan, caused, caused...        11      54       0.610       False    True     False     <NA>  Tianjin Blast Impact on Iron Ore May Be Short-Lived...
43   2015-08-18/2015-08-24                 zikit  table, properties, zikit properties, is0, qtr, shar...        30      48       0.771       False    True     False     <NA>  Zikit Textile Dyeing FY97 Net IS1.38-Share vs IS0.3...
44   2015-08-18/2015-08-24               azd1446  targacept, azd1446 did, core, did, improve, symptom...        14      44       0.629       False    True     False     <NA>  *TARGACEPT ANNOUNCES DECISION BY ASTRAZENECA TO ADV...
45   2015-08-18/2015-08-24      anntaylor profit  anntaylor, profit, loft, declines, discounts, updat...        26      40       0.619       False    True     False     <NA>  AnnTaylor Profit Rises on Higher Sales at Loft Chai...
46   2015-08-18/2015-08-24               tc-2696  targacept, acute, acute post-op, pain, post-op, via...         9      39       0.552       False    True     False     <NA>  *TARGACEPT SEES TC-2696 NOT VIABLE FOR ACUTE POST-O...
47   2015-08-18/2015-08-24                picato  fda, leo, pharma, leo pharma, severe, label, requir...         7      39       0.533       False    True     False     <NA>  *FDA WARNS OF SEVERE ADVERSE EVENTS WITH LEO PHARMA...
48   2015-08-18/2015-08-24                tokali  turkey, fed, halk, rates, won, rate, does, halk yat...         5      35       0.600       False    True     False     <NA>  *TURKEY WON'T RAISE RATES UNTIL FED DOES: HALK YATI...
49   2015-08-18/2015-08-24        tianjin blasts  blasts, tianjin, bmw, china, impact, bmw comments, ...         5      34       0.657       False    True     False     <NA>  *BMW COMMENTS ON DAMAGE IN TIANJIN BLASTS IN E-MAIL...
50   2015-08-25/2015-08-31    peninsula minerals  minerals, peninsula, pen, drilling, intersections, ...        27     103       0.562       False    True     False     <NA>  *PENINSULA MINERALS TO CHANGE NAME TO PENINSULA ENE...
51   2015-08-25/2015-08-31          hac kimisawa  hac, kimisawa, yen, profit, current, earnings, half...        56      85       0.648       False    True     False     <NA>  Hac Kimisawa FY93 Current Profit Up 54.38% to 1.076...
52   2015-08-25/2015-08-31              kimisawa  hac, hac kimisawa, yen, profit, current, earnings, ...        56      85       0.648       False    True     False     <NA>  Hac Kimisawa FY93 Current Profit Up 54.38% to 1.076...
53   2015-08-25/2015-08-31           valdez gold  gold, valdez, gammon, gammon gold, los, properties,...        11      46       0.581       False    True     False     <NA>  *GAMMON GOLD SIGNS DEFINITIVE AGREEMENT WITH VALDEZ...
54   2015-08-25/2015-08-31   pacific exploration  exploration, pacific, production, retirement, arata...        14      40       0.448       False    True      True    False        *PACIFIC EXPLORATION GAINS 11% IN BOGOTA TRADING
55   2015-08-25/2015-08-31        polypore cites  cites, polypore, lithium, edv, ppo, battery, capaci...         6      36       0.638       False    True     False     <NA>  *POLYPORE CITES LITHIUM BATTERY SEPARATOR CAPACITY ...
56   2015-08-25/2015-08-31  millennium chemicals  chemicals, millennium, table, br1, earnings, qtr, r...        16      32       0.562       False    True     False     <NA>  Millennium Chemicals Third-Quarter EPS fell 25.82% ...
57   2015-08-25/2015-08-31               trigana  indonesia, recorder, ntsc, indonesia ntsc, cockpit,...         7      32       0.505       False    True     False     <NA>  *INDONESIA NTSC SAYS HAS TRANSCRIBED TRIGANA VOICE ...
58   2015-08-25/2015-08-31            night tube  night, tube, tfl, union, london, comments, aid, aid...         5      30       0.714       False    True     False     <NA>  *TFL SAYS NIGHT TUBE DEFERRED TO AID SUCCESS OF UNI...
59   2015-08-25/2015-08-31        ashley madison  ashley, madison, data, begin, suits, breach, data b...         8      28       0.543       False    True      True    False  *ASHLEY MADISON SUED IN U.S. BY CLIENTS SEEKING TO ...
60   2015-09-01/2015-09-07     stirling products  products, stirling, sti, purchase, trading, files, ...        58     153       0.629       False    True     False     <NA>  *STIRLING PRODUCTS SEES PACT WITH OFFSHORE ENTITY I...
61   2015-09-01/2015-09-07      ljungberggruppen  table, ljgrb, earnings, share, sk2, sk1, property, sk3        60     118       0.457       False    True     False     <NA>  *LJUNGBERGGRUPPEN 9M SALES SK1.33B VS SK574M       ...
62   2015-09-01/2015-09-07                symbiq  hospira, fda, infusion, approval, pump, gets, hospi...        25      93       0.600       False    True     False     <NA>  *HOSPIRA GOT FDA NOTICE ABOUT PRIOR ISSUED SYMBIQ I...
63   2015-09-01/2015-09-07          physiometrix  reiterated, cibc, adams, harkness, initial, million...        21      62       0.171       False    True     False     <NA>   Physiometrix Files to Sell 2.5 Million Initial Shares
64   2015-09-01/2015-09-07             immunoxel  stirling, products, stirling products, study, sti, ...        15      55       0.438       False    True     False     <NA>  *STIRLING REPORTS ON THIRD PARTY CLAIMS REGARDING I...
65   2015-09-01/2015-09-07               endrate  hospira, copies, deaths, fda, mistakenly, used, war...        10      43       0.600       False    True     False     <NA>  *MISUSE OF ENDRATE, GENERIC COPIES CAUSED DEATHS, U...
66   2015-09-01/2015-09-07               pmi-150  javelin, patent, jav, protection, expands, javelin ...        11      42       0.495       False    True     False     <NA>  *JAVELIN SAYS ARMY REPRESENTATIVES STILL COMMITTED ...
67   2015-09-01/2015-09-07                menire  table, loss, share, eu0, loss eu0, month, month los...        22      37       0.600       False    True     False     <NA>  Menire to Raise as Much as FM20.4 Mln in Public Off...
68   2015-09-01/2015-09-07              palvelut  turvatiimi, otso, otso palvelut, tut1v, issue, pay,...        12      35       0.657       False    True     False     <NA>  *TURVATIIMI ARRANGES DIRECTED ISSUE TO PAY FOR OTSO...
69   2015-09-01/2015-09-07               hakkari  pkk, turkish, cnnturk, army, kills, militants, pkk ...         7      32       0.600       False    True      True    False  *TURKISH ARMY KILLS 20 PKK MILITANTS IN HAKKARI: CN...
70   2015-09-08/2015-09-14            aragonesas  uralita, update1, profit, spain, qtr, prices, bid, pvc        44     114       0.552       False    True     False     <NA>  Spain's Uralita May Sell 25% of Chemical Unit Arago...
71   2015-09-08/2015-09-14       brc diamondcore  brc, diamondcore, rio, bcd, tinto, congo, venture, ...        21      59       0.781       False    True     False     <NA>  *BRC DIAMONDCORE PROPOSES NAME CHANGE TO DELRAND RE...
72   2015-09-08/2015-09-14           diamondcore  brc, brc diamondcore, rio, bcd, tinto, congo, ventu...        21      59       0.781       False    True     False     <NA>  *BRC DIAMONDCORE PROPOSES NAME CHANGE TO DELRAND RE...
73   2015-09-08/2015-09-14        polymedix gets  gets, polymedix, grant, phase, develop, nih, nih gr...        13      55       0.533       False    True     False     <NA>  *POLYMEDIX GETS GUIDANCE TO ENHANCE THE PROPOSED 2B...
74   2015-09-08/2015-09-14                corbyn  leader, labour, elected, elected leader, jeremy, je...        11      55       0.467       False    True     False     <NA>         Corbyn’s Bid to Become U.K.’s Opposition Leader
75   2015-09-08/2015-09-14              ipad pro  ipad, pro, apple, cook, apple introduces, introduce...        11      48       0.514       False    True     False     <NA>             *APPLE CEO TIM COOK UNVEILS LARGER IPAD PRO
76   2015-09-08/2015-09-14         polaroid sale  polaroid, sale, judge, judge rules, rules, update1,...        15      43       0.657       False    True     False     <NA>  *POLAROID SALE VIOLATES $350 MILLION TRADEMARK LIEN...
77   2015-09-08/2015-09-14                 hemis  hmso, goldcorp, agreement, earn-in, expands, hemis ...         8      38       0.410       False    True     False     <NA>  *HEMIS CORP SIGNS EARN-IN AGREEMENT WITH GOLDCORP I...
78   2015-09-08/2015-09-14   goodwill investment  goodwill, investment, share, profit, holding, table...        11      35       0.619       False    True     False     <NA>  China Industrial Intl Changes its Name to Goodwill ...
79   2015-09-08/2015-09-14         ritchie funds  funds, ritchie, time, assets, barclays, petters, wi...        10      33       0.581       False    True     False     <NA>  *BARCLAYS SUES RITCHIE FUNDS OVER PETTERS GROUP INV...
80   2015-09-15/2015-09-21        travelport gds  gds, travelport, north, oww, relocate, relocate nor...         8      37       0.610       False    True     False     <NA>  *TRAVELPORT GDS INTRODUCES TRAVEL BOOKING PRODUCT F...
81   2015-09-15/2015-09-21           croatia chf  chf, croatia, law, loan, loan law, raiffeisen, ecb,...         6      34       0.724       False    True     False     <NA>      *CROATIA CHF LOANS LAW MAY HURT INTL RESERVES: ECB
82   2015-09-15/2015-09-21      olive kitteridge  emmy, kitteridge, olive, wins, role, hbo, wins emmy...         6      34       0.714       False    True     False     <NA>  *JANE ANDERSON WINS EMMY FOR WRITING HBO'S `OLIVE K...
83   2015-09-15/2015-09-21            kitteridge  emmy, olive, olive kitteridge, wins, role, hbo, win...         6      34       0.714       False    True     False     <NA>  *JANE ANDERSON WINS EMMY FOR WRITING HBO'S `OLIVE K...
84   2015-09-15/2015-09-21          baotou huazi  baotou, huazi, yuan, placement, private, private pl...         8      31       0.590       False    True     False     <NA>  *BAOTOU HUAZI SEEKS UP TO 31.68B YUAN IN PRIVATE PL...

### QTUM_etf — top 10 anchors PER WEEK · 22 weeks · 0 quantum row(s) in full table

                      week                   anchor                                                partners  mentions  degree  clustering  is_quantum  caught  promoted llm_kept                                                 example
0    2018-04-10/2018-04-16                   dabbab  abu, gippsland, abu dabbab, project, gip, alluvial,...        31     103       0.705       False    True     False     <NA>  Gippsland Agrees Tantalum Sale From Abu Dabbab Proj...
1    2018-04-10/2018-04-16                  cofetel  mexico, telecom, amxl, statement, connection, link,...        22      90       0.648       False    True     False     <NA>  Mexico’s Cofetel to Unveil Connection Cost Model: N...
2    2018-04-10/2018-04-16               abu dabbab  abu, dabbab, gippsland, project, gip, files, gippsl...        22      72       0.676       False    True     False     <NA>  *GIPPSLAND TO MAKE ANNOUNCEMENT ON ABU DABBAB PROJE...
3    2018-04-10/2018-04-16                      plh  plymouth, minerals, plymouth minerals, zambia, cash...        16      52       0.505       False    True     False     <NA>                  *PLH PLYMOUTH TO FOCUS ON TUNGSTEN-TIN
4    2018-04-10/2018-04-16          sentiment mixed  mixed, sentiment, amid, data, ahead, economic, econ...        15      49       0.524       False    True     False     <NA>                Sentiment Mixed Ahead of Debt Limit Vote
5    2018-04-10/2018-04-16                   fury-1  monitor, oil, testing, energy, monitor energy, petr...        12      47       0.571       False    True     False     <NA>  COE:FURY-1 INITIAL FLOW RATES REACH 75 BARRELS OF O...
6    2018-04-10/2018-04-16               syria risk  risk, syria, inside, auction, axes, ruble, russia, ...         6      42       0.667       False    True     False     <NA>  Russia Axes Bond Auction as Sanctions, Syria Risk B...
7    2018-04-10/2018-04-16         platinum futures  futures, platinum, tokyo, yen, gram, limit, daily, ...        35      39       0.867       False    True     False     <NA>  *PLATINUM FUTURES IN TOKYO DECLINE BY 300-YEN DAILY...
8    2018-04-10/2018-04-16          gippsland files  files, gippsland, gip, project, tin, abu, abu dabba...        13      39       0.648       False    True     False     <NA>  *GIPPSLAND FILES ADOBHA DRILLING RESULTS           ...
9    2018-04-10/2018-04-16          soybeans called  called, soybeans, lower, demand, wheat, grains, hig...        12      38       0.848       False    True     False     <NA>  Grain, Soybeans Called Lower as Japan Quake May Lim...
10   2018-04-17/2018-04-23                     ffbh  federal, bancshares, arkansas, news, nasdaq, rule, ...        34      80       0.343       False    True     False     <NA>                             (FFBH) Reason Not Available
11   2018-04-17/2018-04-23         eletropaulo gets  eletropaulo, gets, brazil, rate, eletrobras, loan, ...        21      58       0.648       False    True     False     <NA>  *ELETROPAULO GETS BRAZIL ANEEL APPROVAL FOR BRL172M...
12   2018-04-17/2018-04-23               chuo musen  chuo, musen, earnings, yen, current, half-year, mil...        47      48       0.705       False    True     False     <NA>    Chuo Musen Co Reports 1st Qtr Group Earnings Results
13   2018-04-17/2018-04-23                  munjals  burmans, fortis, invest, validity, fortis healthcar...        10      40       0.514       False    True     False     <NA>   *FORTIS HEALTHCARE - IMPROVED OFFER FROM HERO/MUNJALS
14   2018-04-17/2018-04-23                  burmans  munjals, fortis, invest, validity, directly, inr15b...         9      39       0.486       False    True      True    False  *MUNJALS AND BURMANS OFFER TO INVEST INR15B DIRECTL...
15   2018-04-17/2018-04-23                  bernini  brazil, eletropaulo, aes, replace, update1, aes bra...         9      37       0.533       False    True     False     <NA>  Brazil's Eletropaulo Names Bernini to Replace Clanc...
16   2018-04-17/2018-04-23                   linkon  loss, share, qtr, table, qtr loss, press, press rel...        12      31       0.476       False    True     False     <NA>   Linkon Corp. 3rd-Qtr Loss 2c-Share vs Loss 6c (Table)
17   2018-04-17/2018-04-23                   kacher  alto, networks, palo, palo alto, light, light stree...         8      30       0.705       False    True     False     <NA>  *LIGHT STREET'S KACHER PITCHES PALO ALTO NETWORKS L...
18   2018-04-17/2018-04-23                mbs close  close, mbs, coupon, fannie, current, current coupon...         4      29       0.724       False    True     False     <NA>  Ginnie/Fannie Higher Coupon Swaps Drop on Class C D...
19   2018-04-17/2018-04-23                   cation  crescent, iss, nominees, point, crescent point, bac...         6      28       0.790       False    True     False     <NA>  *ISS BACKS CATION'S CRESCENT POINT BOARD NOMINEES H...
20   2018-04-24/2018-04-30                    aktav    aktia, profit, eu0, income, board, talks, bank, eu29       134     286       0.590       False    True     False     <NA>  *AKTIA 1Q NET INCOME EU14.8 MLN VS EU19.3 MLN YR AG...
21   2018-04-24/2018-04-30            rochefortaise  communication, rochefortaise communication, rise, q...        23      48       0.600       False    True     False     <NA>    Rochefortaise Raised to `Buy' at KBC Securities (Fr)
22   2018-04-24/2018-04-30                   emidio  geothermal, san, san emidio, project, geothermal ge...         9      35       0.638       False    True     False     <NA>  *U.S. GEOTHERMAL GETS $10.7M CASH GRANT FOR SAN EMIDIO
23   2018-04-24/2018-04-30                mbs close  close, mbs, fannie, fannie mae, mae, coupon, curren...         4      32       0.781       False    True     False     <NA>  Fannie Mae Current Coupon Spread Steady, 10Y Over 3...
24   2018-04-24/2018-04-30          husky wisconsin  husky, wisconsin, refinery, blast, evacuated, area,...        10      32       0.581       False    True     False     <NA>  Husky Wisconsin Refinery Fire Extinguished After Mo...
25   2018-04-24/2018-04-30                  naumova  head, head naumova, ex-pyaterochka, chain, pyateroc...         5      31       0.419       False    True     False     <NA>  X5 Retail Falls as Pyaterochka Chain’s Head Naumova...
26   2018-04-24/2018-04-30            koreas summit  koreas, summit, korea, talks, toplive, edges, gdp, ...         4      29       0.686       False    True     False     <NA>  Won Edges Lower Before U.S. GDP, Koreas Summit: Ins...
27   2018-04-24/2018-04-30     geothermal completes  completes, geothermal, power, purchase, earth, eart...         8      28       0.505       False    True     False     <NA>  *U.S. GEOTHERMAL COMPLETES PURCHASE OF EARTH POWER ...
28   2018-04-24/2018-04-30         geothermal cites  cites, geothermal, platform, accounting, accounting...         6      28       0.514       False    True     False     <NA>  *US GEOTHERMAL CITES ACCOUNTING TREATMENT ON RAFT R...
29   2018-04-24/2018-04-30                   kuhnke  bank, deutsche, deutsche bank, coo, frank, kuhnke c...         7      28       0.629       False    True     False     <NA>  *DEUTSCHE BANK IS SAID SET TO NAME KUHNKE OPERATION...
30   2018-05-01/2018-05-07                   u-wood  table, ber, loss, sen, share, ringgit, million, ear...        40      98       0.467       False    True     False     <NA>  U-Wood Holdings Bhd., Reports First-Quarter Earning...
31   2018-05-01/2018-05-07        doktas dokumculuk  doktas, dokumculuk, table, share, loss, tbl, declar...        30      82       0.648       False    True     False     <NA>  Doktas Dokumculuk Reports Second-Quarter Earnings (...
32   2018-05-01/2018-05-07               bershidsky  leonid, leonid bershidsky, google, apple, criticize...         9      36       0.619       False    True     False     <NA>  EU Privacy Rules May Give Google More Power: Leonid...
33   2018-05-01/2018-05-07        leonid bershidsky  bershidsky, leonid, google, apple, criticized, sorr...         9      36       0.619       False    True     False     <NA>  EU Privacy Rules May Give Google More Power: Leonid...
34   2018-05-01/2018-05-07                  jaresko  ukraine, include, creditor, invites, join, join cre...         7      36       0.371       False    True     False     <NA>  *JARESKO SAYS UKRAINE INVITES RUSSIA TO JOIN CREDIT...
35   2018-05-01/2018-05-07           chip-packaging  advanced, plant, china, update1, advanced semicondu...         9      35       0.638       False    True     False     <NA>  Advanced Micro Plans 2nd Chinese Chip-Packaging Pla...
36   2018-05-01/2018-05-07               garnet tin  garnet, tin, project, consolidated, consolidated ti...        14      34       0.733       False    True     False     <NA>                    MT GARNET TIN PROJECT FUNDING UPDATE
37   2018-05-01/2018-05-07               twse index  index, taiwan, twse, month, led, chipmakers, high, ...         9      34       0.800       False    True     False     <NA>  Taiwan's TWSE Index Falls, Led by First Financial; ...
38   2018-05-01/2018-05-07               mgic posts  loss, mgic, posts, defaults, straight, quarterly, q...        11      33       0.867       False    True     False     <NA>  MGIC Posts $34.4 Million Loss as Claims Surge on Fo...
39   2018-05-01/2018-05-07               besi posts  besi, posts, loss, qtr, update1, quarter, quarter l...        10      32       0.733       False    True     False     <NA>  BESI Posts Second-Quarter Net Income of EU31.5 Million
40   2018-05-08/2018-05-14                      jtv  jumptv, loss, neulion, banks, jordan, jordan banks,...        74     189       0.276       False    True     False     <NA>  *JUMPTV 3Q LOSS 24C-SHR                            ...
41   2018-05-08/2018-05-14                sugarloaf  awe, aut, adi, ops, ami, files, sugarloaf ami, adelphi        68     116       0.819       False    True     False     <NA>  AWE Reports Upgrade to Sugarloaf Reserves and Resou...
42   2018-05-08/2018-05-14                   vinovo  vino, loss, profit, genetech, sk0, property, sells,...        43      95       0.400       False    True     False     <NA>                        *VINOVO 3Q LOSS PER SHARE SK0.01
43   2018-05-08/2018-05-14                    yolla  origin, awe, field, platform, production, yolla pla...        23      86       0.610       False    True     False     <NA>                 YOLLA 6 OUTPUT WELL REACHES TOTAL DEPTH
44   2018-05-08/2018-05-14             arrowsmith-2  awe, norwest, nwe, energy, norwest energy, arrowsmi...        40      80       0.676       False    True     False     <NA>  *NORWEST RECOMMENCED FLOW BACK OF ARROWSMITH-2 WELL...
45   2018-05-08/2018-05-14              local world  local, world, trinity, mirror, trinity mirror, dail...        34      78       0.829       False    True     False     <NA>             *TRINITY MIRROR UPDATE EXCLUDES LOCAL WORLD
46   2018-05-08/2018-05-14               tieto wins  tieto, wins, order, tie1v, finland, contract, servi...        29      68       0.667       False    True     False     <NA>  *TIETO WINS ORDR IN FINLAND, TO DELIVER MUNICIPAL I...
47   2018-05-08/2018-05-14                senecio-3  awe, gas, appraisal, senecio-3 appraisal, drilling,...        22      64       0.486       False    True     False     <NA>  AWE Updates on Flow Test at Senecio-3, Onshore Pert...
48   2018-05-08/2018-05-14                 hotgroup  pounds, acquisitions, trinity, update1, million, mi...        22      60       0.657       False    True     False     <NA>  Trinity to Sell Hotgroup Unit for 11.2 Million Poun...
49   2018-05-08/2018-05-14               arrowsmith  norwest, awe, energy, norwest energy, nwe, project,...        24      53       0.657       False    True     False     <NA>  *NORWEST SAYS BHARAT KEEN TO PROGRESS INVESTMENT IN...
50   2018-05-15/2018-05-21        statoilhydro gets  gets, statoilhydro, consent, stl, drilling, drill, ...        78     171       0.800       False    True     False     <NA>  StatoilHydro Gets Consent to Use Sleipner B, Norway...
51   2018-05-15/2018-05-21                   utsira  high, statoil, norway, utsira high, power, electrif...        50     168       0.752       False    True     False     <NA>  Norway’s Lien Says ‘No Conclusions’ on Power for Ut...
52   2018-05-15/2018-05-21                    dagny  statoil, stl, field, topsides, development, dagny f...        44     155       0.619       False    True     False     <NA>  *EURONAV IN FINAL ROUND OF TENDER FOR STATOIL DAGNY...
53   2018-05-15/2018-05-21            statoil finds  finds, statoil, oil, gas, sea, norwegian, norwegian...        58     148       0.971       False    True     False     <NA>  Statoil Finds Gas Instead of Oil at Castberg After ...
54   2018-05-15/2018-05-21              aran energy   aran, energy, rns, arco, punts, bid, statoil, million        47     141       0.762       False    True     False     <NA>  (RNS)-U.K. CLEARS STATOIL'S PROPOSED ACQUISITION OF...
55   2018-05-15/2018-05-21                michelsen  statoil, norway, spoke, head, michelsen spoke, prod...        45     129       0.743       False    True     False     <NA>  *STATOIL HEAD NORWAY DEV, PRODUCTION MICHELSEN SPOK...
56   2018-05-15/2018-05-21              snohvit lng  lng, snohvit, plant, statoil, statoilhydro, product...        69     121       0.848       False    True     False     <NA>  Statoil Says No ‘Firm Plans’ to Proceed With Snohvi...
57   2018-05-15/2018-05-21                   sincor  venezuela, total, oil, update1, statoil, refinery, ...        38     116       0.781       False    True     False     <NA>  *TOTAL SAYS PDVSA'S STAKE IN SINCOR TO INCREASE TO ...
58   2018-05-15/2018-05-21               veslefrikk  statoil, brage, oil, oseberg, output, statoilhydro,...        29     115       0.867       False    True     False     <NA>  Statoil Plans to Shut Down Veslefrikk Field in 2018...
59   2018-05-15/2018-05-21        shtokman partners  partners, shtokman, gazprom, decision, lng, investm...        48     109       0.857       False    True     False     <NA>  Total Says Shtokman Partners Haven’t Decided to Pos...
60   2018-05-22/2018-05-28              gm-chrysler  wouldn, update1, union, talks, update2, link, fix, ...        45     145       0.752       False    True     False     <NA>  Merkle Says GM-Chrysler Merger Is `Possible' Next Y...
61   2018-05-22/2018-05-28                    obits  lee, john, david, david goldberg, flanagan, goldber...        12     105       0.457       False    True     False     <NA>  Jim Wright, David Goldberg, Maurice Flanagan: Obits...
62   2018-05-22/2018-05-28         chrysler lenders  chrysler, lenders, update1, treasury, reuters, comm...        28      98       0.724       False    True     False     <NA>  *CHRYSLER LENDERS APPEALED A BANKRUPTCY RULING PERM...
63   2018-05-22/2018-05-28                 chrylser  marchionne, link, total, vehicle, loans, dealer, fo...        17      82       0.476       False    True      True    False    Chrylser Group Dec. Total U.S. Vehicle Sales Down 4%
64   2018-05-22/2018-05-28         west electricity  electricity, west, amid, trading, weekend, workweek...        25      65       0.800       False    True     False     <NA>  U.S. West Electricity Rises on Low Hydro Supply, Ga...
65   2018-05-22/2018-05-28                  averion  avro, averion international, international, service...        31      65       0.400       False    True     False     <NA>  *AVERION ANNOUNCES GOING PRIVATE TRANSACTION       ...
66   2018-05-22/2018-05-28            chrysler-fiat  video, obama, mexico, vehicles, success, help, obam...        17      58       0.381       False    True      True     <NA>         *CHRYSLER-FIAT'S MARCHIONNE INTERVIEWED ON CNBC
67   2018-05-22/2018-05-28                  cudmore  cap, contagion, czech, czech koruna, koruna, contag...         8      57       0.562       False    True     False     <NA>  Turkish Lira Options May Underprice EM Contagion Ri...
68   2018-05-22/2018-05-28           chrysler needs    chrysler, needs, york, half, press, suv, video, cars        16      56       0.600       False    True      True    False  Chrysler Needs Electric Cars to Meet Fuel Rules Eve...
69   2018-05-22/2018-05-28             chrysler won  chrysler, won, plant, michigan, open, plant open, m...        12      56       0.724       False    True      True     <NA>  Chrysler Won’t Need Cash After Restructuring, Press...
70   2018-05-29/2018-06-04                     kfin  kuwait, finance, kuwait finance, house, fils, dinar...       105     261       0.752       False    True     False     <NA>  *KUWAIT FINANCE HOUSE FY EPS 30.2 FILS VS 39.9 FILS...
71   2018-05-29/2018-06-04                  celamin  cnl, chaketma, project, cash, end, qtr, capital, ph...        64     172       0.305       False    True     False     <NA>  *CELAMIN HOLDINGS TO MAKE ANNOUNCEMENT ON JV IN TUN...
72   2018-05-29/2018-06-04                 park inn  inn, park, rezidor, rezt, russia, hotel, hotels, opens        44     105       0.838       False    True     False     <NA>  *REZIDOR ANNOUNCES BLU HOTEL, OSLO ALNA, PARK INN  ...
73   2018-05-29/2018-06-04              raven mount  mount, raven, rav, pnds, russia, loss, raven russia...        30      81       0.762       False    True     False     <NA>  *RAVEN RUSSIA HAS 91.49% OF RAVEN MOUNT OFFER ACCEP...
74   2018-05-29/2018-06-04                 chaketma  celamin, project, cnl, drilling, phosphate, chaketm...        24      60       0.505       False    True     False     <NA>  *CELAMIN NOTES GASSAA KEBIRA RESOURCE TRIPLES CHAKE...
75   2018-05-29/2018-06-04            rezidor opens  opens, rezidor, rezt, hotel, inn, park, russia, rad...        23      55       0.819       False    True     False     <NA>  *REZIDOR OPENS PARK INN VELIKY NOVGOROD IN RUSSIA  ...
76   2018-05-29/2018-06-04               time-share  wyndham, update1, restructures, wyndham restructure...        15      50       0.476       False    True     False     <NA>  Wyndham Posts Loss on Time-Share, May Sell Shares (...
77   2018-05-29/2018-06-04            italy turmoil  italy, turmoil, bridgewater, marshall, marshall wac...        12      48       0.438       False    True     False     <NA>  Bridgewater, Marshall Wace Profit as Italy Turmoil ...
78   2018-05-29/2018-06-04                  aandahl  samsonite, soren, blue, blue orca, orca, governance...        10      47       0.390       False    True     False     <NA>  Soren Aandahl, Seth Fischer Present at Sohn Confere...
79   2018-05-29/2018-06-04                  missoni  hotel, rezidor, hotel missoni, rezt, disappearance,...        12      46       0.495       False    True     False     <NA>  *REZIDOR SAYS HOTEL MISSONI DOHA TO OPEN LATE 2015 ...
80   2018-06-05/2018-06-11           unitednetworks  update1, profit, sale, update2, assets, million, ve...        67     149       0.657       False    True     False     <NA>  Powerco Shareholders Approve Purchase of UnitedNetw...
81   2018-06-05/2018-06-11                    alvdi   vdi, rev, billings, eu0, eu11, eu12, rev eu12, margin        54      69       0.295       False    True     False     <NA>  *VDI GROUP SEES FY BILLINGS RISING 1-2%            ...
82   2018-06-05/2018-06-11                     kcpl  western, resources, western resources, buyout, affi...        13      57       0.581       False    True     False     <NA>  *MOODY'S DOWNGRADES KCPL; AFFIRMS RATINGS OF GREAT ...
83   2018-06-05/2018-06-11                    jansa  slovenia, president, vows, govt, talks, avoid, avoi...        10      47       0.505       False    True     False     <NA>      *SLOVENIA'S SAREC VOWS TO AVOID JANSA IN COALITION

### CHPX_etf — top 10 anchors PER WEEK · 22 weeks · 1 quantum row(s) in full table
  ↓ quantum rows (pinned — shown regardless of degree rank):

                       week      anchor                                                partners  mentions  degree  clustering  is_quantum  caught  promoted llm_kept                                                example
5408  2025-01-07/2025-01-13  ionq delta  daily, daily volume, delta, hedge, ionq, options, o...         3       9         1.0        True    True     False     <NA>  IonQ Delta Hedge at 12% Daily Volume: Options Pre-Mkt

                      week                  anchor                                                partners  mentions  degree  clustering  is_quantum  caught  promoted llm_kept                                                 example
0    2024-08-20/2024-08-26                  wukong  game, tencent-backed, first-day, history, makes, ch...         9      54       0.562       False    True     False     <NA>  Tencent-Backed ‘Wukong’ Makes Gaming History in Fir...
1    2024-08-20/2024-08-26                   durov  telegram, france, afp, airport, paris, paris airpor...         8      35       0.362       False    True     False     <NA>  Telegram CEO Pavel Durov Arrested at Paris Airport,...
2    2024-08-20/2024-08-26             lynch yacht  lynch, yacht, bloomer, missing, morgan, morgan stan...         6      34       0.610       False    True     False     <NA>  Morgan Stanley’s Bloomer Among Lynch Yacht Missing,...
3    2024-08-20/2024-08-26                  freixe  nestle, laurent, schneider, mark, laurent freixe, s...        12      32       0.486       False    True     False     <NA>                     *NESTLÉ NAMES LAURENT FREIXE AS CEO
4    2024-08-20/2024-08-26                  v-wave  johnson, payment, upfront, medtech, diluting, upfro...        13      30       0.162       False    True     False     <NA>                         Johnson & Johnson to Buy V-Wave
5    2024-08-20/2024-08-26         canada railways  canada, railways, shippers, shut, lock, snarling, s...         6      28       0.505       False    True     False     <NA>  Trudeau Urges a Deal as Canada Railways Edge Closer...
6    2024-08-20/2024-08-26                ww2 bomb  bomb, ww2, czech, discovery, follow, litvinov, move...         3      23       0.657       False    True     False     <NA>  *ORLEN LITVINOV MOVES FOLLOW DISCOVERY OF WW2 BOMB ...
7    2024-08-20/2024-08-26             italy coast  coast, guard, italy, lynch, yacht, bloomer, rescue,...         3      21       0.714       False    True     False     <NA>  *ITALY COAST GUARD SAYS UNLIKELY TO RESCUE LYNCH, B...
8    2024-08-20/2024-08-26                  altrad  beerenberg, cash, nok41, recommended, beerenberg bo...         4      21       0.457       False    True     False     <NA>  *BEERENBERG BOARD UNANIMOUSLY RECOMMENDS OFFER BY A...
9    2024-08-20/2024-08-26                   wamco  trades, king, longtime, shunned, spotlight, thrust,...         8      21       0.267       False    True     False     <NA>  *US CRIMINAL PROBE INTO WAMCO SAID TO FOCUS ON 'CHE...
10   2024-08-27/2024-09-02        typhoon shanshan  shanshan, typhoon, japan, dumping, rain, coast, dum...        10      32       0.686       False    True     False     <NA>  Japan Issues Highest Warning as Typhoon Shanshan Ne...
11   2024-08-27/2024-09-02                   wamco  franklin, resources, free, free rein, rein, chicago...         9      31       0.619       False    True      True    False  *CHICAGO TEACHERS’ PREPARES TO PULL WAMCO CORE PLUS...
12   2024-08-27/2024-09-02          sanctioned lng  lng, sanctioned, cargo, ship, yamal, yamal cargo, d...         6      29       0.600       False    True     False     <NA>             Panama Starts Probe of Sanctioned LNG Ships
13   2024-08-27/2024-09-02                 nextrna  bayer, pact, oncology, funding, milestones, receive...         4      25       0.457       False    True     False     <NA>  *NEXTRNA TO RECEIVE UP TO $547M IN MILESTONES, RESE...
14   2024-08-27/2024-09-02                  kaseya  africa, cdc, africa cdc, general, jean, jean kaseya...         4      23       0.552       False    True     False     <NA>  *AFRICA CDC DIRECTOR GENERAL JEAN KASEYA SPEAKS TO ...
15   2024-08-27/2024-09-02            altice intnl  altice, intnl, eu225m, eu1, rev, ebitda, ebitda eu4...         6      23       0.467       False    True     False     <NA>                *ALTICE INTNL 2Q REV. EU1.10B, -3.2% Y/Y
16   2024-08-27/2024-09-02                   durov  telegram, prosecutors, businessweek, businessweek d...         4      21       0.400       False    True     False     <NA>  What's Next for Telegram CEO Pavel Durov: Businessw...
17   2024-08-27/2024-09-02                   odevo  cvc, property, manager, alongside, fidelio, investm...         5      21       0.524       False    True     False     <NA>  CVC Said in Talks to Invest in $3 Billion Property ...
18   2024-08-27/2024-09-02             volue board  board, volue, bidco, edison, considers, end, fair, ...         3      20       0.629       False    True     False     <NA>  *VOLUE BOARD CONSIDERS OFFER PRICE AT MODEST END OF...
19   2024-08-27/2024-09-02           foundry split  foundry, intel, split, options, including, intel we...         5      19       0.695       False    True     False     <NA>  Intel Weighs Options Including Foundry Split to Ste...
20   2024-09-03/2024-09-09                francine  storm, tropical, tropical storm, oil, gulf, mph, mp...        17      51       0.562       False    True     False     <NA>  Tropical Storm Francine in Southern Gulf With 50 Mp...
21   2024-09-03/2024-09-09                 xockets  alleges, colluded, licensing, microsoft, microsoft ...         3      26       0.486       False    True     False     <NA>  *XOCKETS ALLEGES NVIDIA, MICROSOFT COLLUDED ON PATE...
22   2024-09-03/2024-09-09                  galkin  investor, jetblue, jetblue investor, board, board s...         6      26       0.543       False    True     False     <NA>  *JBLU HOLDER GALKIN DISCUSSED BOARD REPRESENTATION ...
23   2024-09-03/2024-09-09                daventry  letter, kinaxis, board, sends, sends letter, sale, ...         8      26       0.562       False    True     False     <NA>  *DAVENTRY GROUP SENDS LETTER TO BOARD OF KINAXIS ON...
24   2024-09-03/2024-09-09                   lumio  files, firm, solar, chapter, delaware, lumio files,...         8      24       0.390       False    True     False     <NA>  Lumio Holdings Files for Chapter 11 Bankruptcy in D...
25   2024-09-03/2024-09-09        jetblue investor  investor, jetblue, galkin, board, seat, board seat,...         7      24       0.571       False    True     False     <NA>  *JETBLUE INVESTOR GALKIN SAYS HE MET WITH CEO GERAG...
26   2024-09-03/2024-09-09                  medera  public, acquisition, keen, keen vision, vision, bio...         4      21       0.476       False    True     False     <NA>  Biotech Firm Medera Set to Go Public in $623 Millio...
27   2024-09-03/2024-09-09                   parle  approves, approves increase, authorized, authorized...         3      20       0.486       False    True     False     <NA>  *PARLE INDUSTRIES APPROVES INCREASE IN AUTHORIZED S...
28   2024-09-03/2024-09-09                end news  dual-class, end, news, starboard, structure, dual-c...         7      20       0.686       False    True     False     <NA>  *STARBOARD SEEKS TO END NEWS CORP DUAL-CLASS STRUCT...
29   2024-09-03/2024-09-09           peers tighten  peers, spreads, tighten, ashtead, ashtead capital, ...         4      19       0.562       False    True     False     <NA>  Caterpillar, Ashtead Capital Bond Spreads vs Peers ...
30   2024-09-10/2024-09-16                francine  hurricane, hurricane francine, winds, gulf, coast, ...        61     167       0.762       False    True     False     <NA>  Cameron LNG Flows Drop 41% as Storm Francine Streng...
31   2024-09-10/2024-09-16      hurricane francine  francine, hurricane, winds, gulf, mph, mph winds, l...        32      82       0.619       False    True     False     <NA>         Hurricane Francine in US Gulf With 75 Mph Winds
32   2024-09-10/2024-09-16           peers tighten  peers, spreads, tighten, capital, hyundai, hyundai ...         5      30       0.676       False    True     False     <NA>  Hyundai Capital, Keurig Dr Pepper Spreads vs Peers ...
33   2024-09-10/2024-09-16                   wamco  fund, job, lose, lose job, managing, managing money...         4      26       0.543       False    True     False     <NA>  *WAMCO FLAGSHIP BOND FUND ASSETS DIP TO $14.3B AS I...
34   2024-09-10/2024-09-16       commerzbank share  commerzbank, sale, share, germany, prices, sale pri...         7      25       0.571       False    True     False     <NA>         *COMMERZBANK SHARE SALE PRICES AT EU13.20/SHARE
35   2024-09-10/2024-09-16            trump-harris  debate, trump-harris debate, pivotal, traders, bitc...         5      24       0.600       False    True     False     <NA>  Edgy Traders Gird for Potentially ‘Pivotal’ Trump-H...
36   2024-09-10/2024-09-16              space walk  space, walk, private, spacex, historic, historic pr...         5      23       0.714       False    True     False     <NA>  SpaceX Launches Crew for First-Ever Private Space W...
37   2024-09-10/2024-09-16          sanctioned lng  lng, sanctioned, cargo, fifth, ship, facility, fift...         3      23       0.781       False    True     False     <NA>  Sanctioned LNG Ship Picks Up Fifth Cargo From Russi...
38   2024-09-10/2024-09-16             peers widen  peers, spreads, widen, capital, clean, energy, enn,...         4      22       0.638       False    True     False     <NA>  ENN Clean Energy, Minejesa Capital Bond Spreads vs ...
39   2024-09-10/2024-09-16                 sub-140  dollar-yen, dollar-yen opening, door, land, opening...         3      21       0.371       False    True     False     <NA>                 Dollar-Yen Opening Door to Sub-140 Land
40   2024-09-17/2024-09-23                   pager  blasts, hezbollah, lebanon, israel, pager blasts, t...        21     102       0.448       False    True     False     <NA>  Iran Envoy to Lebanon Injured in Pager Explosion: Mehr
41   2024-09-17/2024-09-23                  pagers  lebanon, exploding, exploding pagers, taiwan, suppl...        18      64       0.448       False    True     False     <NA>  Hezbollah Members Wounded in Lebanon as Pagers Expl...
42   2024-09-17/2024-09-23             monlunabant  novo, loss, weight, phase, data, limited, monlunaba...         9      43       0.629       False    True     False     <NA>  *NOVO NORDISK MONLUNABANT PHASE 2A TRIAL IN OBESITY...
43   2024-09-17/2024-09-23            pager blasts  blasts, pager, israel, lebanon, accuses, accuses is...         6      31       0.562       False    True     False     <NA>  Lebanon Cabinet Accuses Israel of Being Behind Page...
44   2024-09-17/2024-09-23           africa floods  africa, floods, million, affect, deepen, deepen foo...         3      24       0.600       False    True     False     <NA>  Africa Floods Affect 4 Million People, Deepen Food ...
45   2024-09-17/2024-09-23       northvolt lenders  lenders, northvolt, advice, pjt, funding, funding o...         4      24       0.571       False    True     False     <NA>  *NORTHVOLT LENDERS SELECT PJT FOR ADVICE ON FUNDING...
46   2024-09-17/2024-09-23                 barnier  french, edition, barnier starts, budget, climb, fre...         3      24       0.629       False    True      True    False  Barnier Starts Climb on French Budget Mountain: Par...
47   2024-09-17/2024-09-23                 makarna  oba, oba makarna, buyback, buyback prgrm, explosion...         5      22       0.610       False    True     False     <NA>  *OBA MAKARNA LAUNCHES SHR BUYBACK PRGRM AFTER FACTO...
48   2024-09-17/2024-09-23             oba makarna  makarna, oba, buyback, buyback prgrm, explosion, fa...         5      22       0.610       False    True     False     <NA>  *OBA MAKARNA LAUNCHES SHR BUYBACK PRGRM AFTER FACTO...
49   2024-09-17/2024-09-23        exploding pagers  exploding, pagers, supply-chain, security, supply-c...         8      22       0.590       False    True     False     <NA>  Exploding Pagers in Lebanon Spur Theories on Sabota...
50   2024-09-24/2024-09-30        hurricane helene  helene, hurricane, mph, mph winds, winds, florida, ...        38     100       0.543       False    True     False     <NA>                 WHO DAT SHUT IN DUE TO HURRICANE HELENE
51   2024-09-24/2024-09-30                ldp vote  ldp, vote, takaichi, yen, chances, chances rising, ...         4      30       0.648       False    True     False     <NA>  Yen Drops as Traders See Takaichi’s Chances Rising ...
52   2024-09-24/2024-09-30              roche aims  aims, roche, portfolio, growth, deliver, exec, exec...         5      27       0.619       False    True     False     <NA>  *ROCHE AIMS TO EXPAND OPHTHALMOLOGY PORTFOLIO, EXEC...
53   2024-09-24/2024-09-30             peers widen  peers, spreads, widen, communications, omnicom, rog...         5      25       0.629       False    True     False     <NA>  CRH America Finance, Dow Chemical Bond Spreads vs P...
54   2024-09-24/2024-09-30        australia grants  australia, grants, beach, licenses, feasibility, li...         4      25       0.629       False    True     False     <NA>  Australia Grants Spinifex Feasibility License for O...
55   2024-09-24/2024-09-30                liebherr  fortescue, equipment, green, green equipment, partn...         8      24       0.552       False    True     False     <NA>     *FMG FORTESCUE LIEBHERR GREEN EQUIPMENT PARTNERSHIP
56   2024-09-24/2024-09-30              ishiba win  ishiba, win, yen, herald, higher, higher rates, liv...         3      24       0.733       False    True     False     <NA>  Yen Surges as Ishiba Win May Herald Higher Rates: M...
57   2024-09-24/2024-09-30           america event  america, bank, event, barclays, venkatakrishnan, co...         4      21       0.638       False    True     False     <NA>  *BARCLAYS CEO CS VENKATAKRISHNAN SAYS AT BANK OF AM...
58   2024-09-24/2024-09-30  potential price-fixing  potential, price-fixing, sap, carahsoft, probing, i...        10      21       0.619       False    True     False     <NA>  *US PROBING TECH FIRMS SAP, CARAHSOFT FOR POTENTIAL...
59   2024-09-24/2024-09-30              istaroxime  phase, study, primary, positive, positive topline, ...         5      21       0.486       False    True     False     <NA>  *WINDTREE REPORTS POSITIVE TOPLINE OF PHASE 2B ISTA...
60   2024-10-01/2024-10-07        hurricane milton  hurricane, milton, winds, mph, mph winds, gulf, sou...        22      49       0.524       False    True     False     <NA>           Hurricane Milton in US Gulf With 80 Mph Winds
61   2024-10-01/2024-10-07        hurricane helene  helene, hurricane, provides, asheville, asheville h...         8      37       0.419       False    True     False     <NA>                           Gateway Aid, Hurricane Helene
62   2024-10-01/2024-10-07               dsv share  dsv, share, sale, draw, investor, investor orders, ...         8      35       0.562       False    True     False     <NA>                 *DSV SHARE SALE BOOKS ARE CLOSED: TERMS
63   2024-10-01/2024-10-07             peers widen  peers, spreads, widen, capital, bakeries, bimbo, bi...         6      34       0.600       False    True     False     <NA>  Bimbo Bakeries USA, BMW US Capital Bond Spreads vs ...
64   2024-10-01/2024-10-07                 barnier  watch, french, parliament, barnier walks, france, t...         5      25       0.495       False    True     False     <NA>  France’s Barnier Walks Parliamentary Tightrope: Wha...
65   2024-10-01/2024-10-07             tariff vote  tariff, vote, dsv, dsv share, israel, israel strike...         3      23       0.600       False    True     False     <NA>          DSV Share Sale, EU Tariff Vote, Israel Strikes
66   2024-10-01/2024-10-07         rate-hike hopes  hopes, rate-hike, yen, dim, worst, boj, boj dim, mi...         7      22       0.657       False    True     False     <NA>  Yen Set for Worst Day Since 2023 as Ishiba Dims Rat...
67   2024-10-01/2024-10-07           dovish bailey  bailey, dovish, bets, pound, add, traders, traders ...         3      21       0.733       False    True     False     <NA>  Dovish Bailey Tilt Can Ramp Up Easing Bets, Sink Pound
68   2024-10-01/2024-10-07                  solorz  board, ousts, sons, polish, firms, pak, pak ousts, ...         4      21       0.495       False    True     False     <NA>  *ZE PAK OUSTS SOLORZ'S TWO SONS FROM SUPERVISORY BOARD
69   2024-10-01/2024-10-07            japan ishiba  approval, cabinet, cabinet approval, ishiba, japan,...         6      20       0.752       False    True     False     <NA>  *JAPAN ISHIBA CABINET APPROVAL RATE 51% IN NIKKEI POLL
70   2024-10-08/2024-10-14        hurricane milton  hurricane, milton, florida, winds, mph, mph winds, ...        65     166       0.600       False    True      True    False  Hurricane Milton Prompts Closure of Mexico Ports, S...
71   2024-10-08/2024-10-14                cybercab  tesla, musk, production, cost, tesla cybercab, cybe...        17      61       0.457       False    True     False     <NA>                  *MUSK SAYS ROBOTAXI IS CALLED CYBERCAB
72   2024-10-08/2024-10-14                  unifil  israel, peacekeepers, tank, lebanon, injured, peace...         6      34       0.524       False    True     False     <NA>  *UNIFIL SAYS 2 PEACEKEEPERS INJURED AFTER ISRAEL TA...
73   2024-10-08/2024-10-14          china briefing  briefing, china, earnings, ahead, dollar, asian, as...         6      28       0.562       False    True     False     <NA>                  China Briefing Reaction, TSMC Earnings
74   2024-10-08/2024-10-14                  solorz  board, cyfrowy, son, supervisory, tobias, family, f...         4      27       0.505       False    True      True    False               Solorz Family Feud, Long-Term Fiscal Plan
75   2024-10-08/2024-10-14                  siller  mexico, base, fdi, financiero, financiero base, gru...         4      27       0.495       False    True     False     <NA>  *MEXICO IS LAGGING ON FDI, SAYS GRUPO FINANCIERO BA...
76   2024-10-08/2024-10-14            milton nears  milton, nears, fences, flood-proof, flood-proof fen...         4      26       0.638       False    True     False     <NA>  As Milton Nears, Flood-Proof Fences Are a Key Acces...
77   2024-10-08/2024-10-14            mof briefing  briefing, mof, china, yuan, maybank, trade, usd, await         4      25       0.648       False    True     False     <NA>  Yuan May Trade Between 7 to 7.1/USD Before MOF Brie...
78   2024-10-08/2024-10-14                  opella  sanofi, talks, controlling, potential, sale, discus...        10      24       0.390       False    True     False     <NA>  *SANOFI IN TALKS TO SELL A CONTROLLING STAKE IN OPELLA
79   2024-10-08/2024-10-14            bets boosted  bets, boosted, bullish, high, oil, brent, cattle, c...         6      24       0.676       False    True     False     <NA>  Net Bullish ICE Brent Crude Oil Bets Boosted to 12-...
80   2024-10-15/2024-10-21                  opella  sanofi, talks, transfer, bpifrance, france, control...        19      84       0.467       False    True      True    False  *PAI PARTNERS IS SAID TO SUBMIT REVISED BID FOR SAN...
81   2024-10-15/2024-10-21                  kyriba  atlantic, general, general atlantic, firm, tech, te...         9      29       0.467       False    True     False     <NA>  *GENERAL ATLANTIC SAID TO NEAR STAKE DEAL FOR TECH ...
82   2024-10-15/2024-10-21        housing ministry  housing, ministry, briefing, china, mof, pboc, topl...        11      25       0.562       False    True     False     <NA>   *CHINA'S HOUSING MINISTRY, MOF, PBOC TO HOLD BRIEFING
83   2024-10-15/2024-10-21                   sfisf  pboc, firms, launches, operation, pboc launches, sf...         4      25       0.410       False    True     False     <NA>               *PBOC LAUNCHES SFISF OPERATION FROM TODAY
84   2024-10-15/2024-10-21                  balint  romanian, deficit, rate, reduction, clouds, clouds ...         3      21       0.581       False    True     False     <NA>  *ROMANIAN DEFICIT REDUCTION NEED CLOUDS RATE CUTS T...

### QTUP_etf: no data (future date)

In [33]:
DFS['CHPX_etf'][DFS['CHPX_etf'].is_quantum]

,week,anchor,partners,mentions,degree,clustering,is_quantum,caught,promoted,llm_kept,example,rank_candidate,rank_caught,rank_promoted,llm_judged
5408,2025-01-07/2025-01-13,ionq delta,"daily, daily volume, delta, hedge, ionq, options, o...",3,9,1.0,True,True,False,<NA>,IonQ Delta Hedge at 12% Daily Volume: Options Pre-Mkt,139,205,<NA>,False