# Stage 1 — Topic → Theme (temporal) with **BERTrend**

Roadmap goal: turn per-window BERTopic clusters into **themes with a stable ID over time** (continuation / merge / split / birth), build a **theme-intensity time series**, and label lifecycle stage.

[BERTrend](https://github.com/rte-france/BERTrend) trains a BERTopic model **per time slice**, merges topics across slices with a cosine threshold to form cumulative themes, then computes a **popularity (intensity)** signal per theme with exponential decay — classifying each as `noise` / `weak signal` / `strong signal`.

**This run (v2)** incorporates the review findings from the H1 prototype:

1. **Wider window** — full **2023 + 2024** (~52 bi-weekly slices) instead of one half-year.
2. **Cleaner inputs** — strip wire-source prefixes, drop earnings/announcement boilerplate, and extend the stopword list, so junk clusters (`inc, plc, results, ceo, …`) stop dominating.
3. **Intensity *rate*** — add a first-difference / per-slice doc-count signal so themes show birth→peak→decay (needed for the lead–lag test), not just cumulative attention.
4. **Honest sector map** — calibrate the cosine threshold empirically *and* add a complementary mapping via the `DerivedTickersId` already in the news.
5. **Native BERTrend dashboards** — three HTML artifacts mirroring the official demos:
   - [`topic_analysis`](https://github.com/rte-france/BERTrend/tree/main/bertrend/demos/topic_analysis) — per-slice topic exploration
   - [`weak_signals`](https://github.com/rte-france/BERTrend/tree/main/bertrend/demos/weak_signals) — signal evolution + merge Sankey + emergence
   - [`prospective_demo`](https://github.com/rte-france/BERTrend/tree/main/bertrend/bertrend_apps/prospective_demo) — point-in-time signal dashboard

**Stage-1 gate (later):** does our theme-intensity series *lead* the ETF cohort's price peak (which leads flows)? See `docs/roadmap.md`.

## 0. Environment

BERTrend is part of the main project env (added to `pyproject.toml`; `pandas` pinned `>=2.2,<3.0.0`). To (re)install: `uv sync` from `code/`. Use the project `.venv` kernel.

> **Note:** BERTrend creates a base directory for its models/cache (defaults to `~/.bertrend`). The first code cell sets `BERTREND_BASE_DIR` to a folder inside `notebooks/output/` **before** importing BERTrend, so nothing is written to your home dir.

In [1]:
# Keep BERTrend's base dir inside the project (must be set BEFORE importing bertrend).
import os
from pathlib import Path

_PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
os.environ["BERTREND_BASE_DIR"] = str(_PROJECT_ROOT / "notebooks" / "output" / "bertrend_base")

import bertrend  # noqa: E402
import pandas as pd  # noqa: E402

print("bertrend base dir:", bertrend.BASE_PATH)
print("pandas:           ", pd.__version__, "(BERTrend requires <3.0.0)")

2026-06-08 16:12:14.023 | WARNING  | bertrend:<module>:22 - Failed to load .env file

bertrend base dir: /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_base
pandas:            2.3.3 (BERTrend requires <3.0.0)

## 1. Config & imports

In [2]:
from __future__ import annotations

import lzma
import re
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import polars as pl
import torch
from sentence_transformers import SentenceTransformer

from bertrend.BERTrend import BERTrend
from bertrend.BERTopicModel import BERTopicModel
from bertrend.utils.data_loading import (
    group_by_days,
    TEXT_COLUMN,
    TIMESTAMP_COLUMN,
    DOCUMENT_ID_COLUMN,
    SOURCE_COLUMN,
    URL_COLUMN,
)

# --- paths ---
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_DIR = PROJECT_ROOT / "data" / "raw"
ICB_PATH = PROJECT_ROOT / "notebooks" / "input" / "icb-structure-and-definitions.xlsx"
OUTPUT_DIR = PROJECT_ROOT / "notebooks" / "output"
MODELS_DIR = PROJECT_ROOT / "notebooks" / "output" / "bertrend_models"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)

EMBEDDING_MODEL = "FinLang/finance-embeddings-investopedia"
RANDOM_SEED = 42

# --- temporal window: full 2023 + 2024 ---
YEARS = [2023, 2024]
DATE_START = f"{YEARS[0]}-01-01T00:00:00+00:00"
DATE_END = f"{YEARS[-1] + 1}-01-01T00:00:00+00:00"
TAG = f"{YEARS[0]}_{YEARS[-1]}"               # output-file suffix
GRANULARITY_DAYS = 14                          # one BERTopic model every 2 weeks
WINDOW_SIZE = 28                               # rolling window (days) for signal classification
SAMPLE_N = 60_000                              # cap total headlines for tractable embedding

# --- per-slice BERTopic params ---
MIN_TOPIC_SIZE = 25                            # larger clusters -> fewer junk micro-topics
MIN_SAMPLES = 5
MIN_SIMILARITY = 0.7                           # cosine threshold for merging themes across slices

DEVICE = (
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
print(f"Device:      {DEVICE}")
print(f"Window:      {DATE_START[:10]} → {DATE_END[:10]}  ({GRANULARITY_DAYS}d slices)")
print(f"Year files:  {[str(RAW_DIR / f'raw_news_{y}.csv.xz') for y in YEARS]}")

Device:      mps
Window:      2023-01-01 → 2025-01-01  (14d slices)
Year files:  ['/Users/federicocinus/Progetti - Local/ThematicTrading/code/data/raw/raw_news_2023.csv.xz', '/Users/federicocinus/Progetti - Local/ThematicTrading/code/data/raw/raw_news_2024.csv.xz']

## 2. Load & clean headlines → BERTrend schema

Polars does not auto-decompress `.xz`, so we open each year file with `lzma` and concatenate. Then we **clean aggressively** (the H1 run was dominated by wire boilerplate):

- `strip_colon_prefix` — drop short wire-source prefixes (`BSECorpAnn:`, `Reuters:`) but keep real content.
- `strip_dates` — remove dates / bare numbers.
- **Boilerplate blocklist** — drop earnings / announcement / governance wire copy (`half-year-report`, `dividend`, `appoints`, `total voting rights`, …) and headlines with < 4 words.

BERTrend expects a pandas frame with `timestamp` + `text`; we also keep `DerivedTickersId` (for the sector/ticker map), `source`, `url`, `document_id`. We **sort by time and reset the index** so embedding row *i* ↔ `document_id == i` (BERTrend slices via `embeddings[group.index]`).

In [3]:
DATE_PATTERNS = (
    r"\b\d{4}[/\-]\d{1,2}[/\-]\d{1,2}\b",
    r"\b\d{1,2}[/\-]\d{1,2}[/\-]\d{2,4}\b",
    r"\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+\d{1,2},?\s+\d{4}\b",
    r"\bq[1-4]\s+\d{4}\b",
)

# Earnings / announcement / governance wire boilerplate — the noise clusters in the H1 run.
BOILERPLATE_RE = re.compile(
    r"\b(half[- ]year|annual report|interim (results|report)|quarterly report|"
    r"results? (announcement|publication)|dividend|interim dividend|agm|egm|"
    r"notice of|appoint(s|ed|ment)?|resignation|board change|"
    r"transaction in own shares|total voting rights|director/pdmr|pdmr|"
    r"holding\(s\) in company|net asset value|prospectus|earnings call|"
    r"conference call|webcast|trading update|block listing)\b",
    re.IGNORECASE,
)


def strip_colon_prefix(text: str) -> str:
    """Drop short wire-source prefixes like 'BSECorpAnn:'. Applied twice for stacked prefixes."""
    for _ in range(2):
        if not text or ":" not in text:
            return text
        prefix, _, rest = text.partition(":")
        prefix, rest = prefix.strip(), rest.strip()
        if not prefix or not prefix[0].isalpha() or not rest:
            return text
        if len(prefix) > 30 or len(prefix.split()) > 4:
            return text
        text = rest
    return text


def strip_dates(text: str) -> str:
    for pat in DATE_PATTERNS:
        text = re.sub(pat, " ", text, flags=re.IGNORECASE)
    text = re.sub(r":\s*\d+\b", ":", text)
    text = re.sub(r"\b\d+\b", " ", text)
    text = re.sub(r":\s*$", "", text)
    return re.sub(r"\s+", " ", text).strip()


def normalize_headline(text: str) -> str:
    return strip_dates(strip_colon_prefix(text))


# --- load every year file, filter to the window, concat, dedupe ---
WANT_COLS = ["Headline", "CaptureTime", "WireName", "DerivedTickersId"]
frames = []
for yr in YEARS:
    p = RAW_DIR / f"raw_news_{yr}.csv.xz"
    with lzma.open(p, "rb") as f:
        frames.append(
            pl.scan_csv(f, infer_schema_length=10_000)
            .select(WANT_COLS)
            .with_columns(pl.col("CaptureTime").str.to_datetime(time_zone="UTC", strict=False))
            .filter(
                (pl.col("CaptureTime") >= pl.lit(DATE_START).str.to_datetime(time_zone="UTC"))
                & (pl.col("CaptureTime") < pl.lit(DATE_END).str.to_datetime(time_zone="UTC"))
                & pl.col("Headline").is_not_null()
                & (pl.col("Headline").str.len_chars() > 0)
            )
            .collect()
        )
corpus = pl.concat(frames).unique(subset=["Headline"])
print(f"Unique headlines in window: {corpus.height:,}")

if corpus.height > SAMPLE_N:
    corpus = corpus.sample(n=SAMPLE_N, seed=RANDOM_SEED, shuffle=True)

# --- to pandas + clean ---
df = corpus.to_pandas()
df = df.rename(columns={"Headline": TEXT_COLUMN, "CaptureTime": TIMESTAMP_COLUMN, "WireName": SOURCE_COLUMN})
n0 = len(df)

# drop boilerplate on the RAW headline before normalization
df = df[~df[TEXT_COLUMN].fillna("").str.contains(BOILERPLATE_RE)]
n1 = len(df)

df[TEXT_COLUMN] = df[TEXT_COLUMN].map(normalize_headline)
df = df[df[TEXT_COLUMN].str.split().map(len) >= 4]            # require >= 4 words
n2 = len(df)

df[TIMESTAMP_COLUMN] = pd.to_datetime(df[TIMESTAMP_COLUMN]).dt.tz_localize(None)
df = df.sort_values(TIMESTAMP_COLUMN).reset_index(drop=True)
df[DOCUMENT_ID_COLUMN] = df.index
df[URL_COLUMN] = None
df[SOURCE_COLUMN] = df[SOURCE_COLUMN].fillna("unknown")
df["DerivedTickersId"] = df["DerivedTickersId"].fillna("")

print(f"After boilerplate blocklist: {n1:,}  (-{n0 - n1:,})")
print(f"After <4-word / date strip:  {n2:,}  (-{n1 - n2:,})")
print(f"Headlines used:              {len(df):,}")
print(f"Date span:                   {df[TIMESTAMP_COLUMN].min()} → {df[TIMESTAMP_COLUMN].max()}")
df.head(3)

Unique headlines in window: 21,658,899

After boilerplate blocklist: 58,233  (-1,767)
After <4-word / date strip:  53,581  (-4,652)
Headlines used:              53,581
Date span:                   2023-01-01 00:04:48.767000 → 2024-12-31 23:21:29.106000

,text,timestamp,source,DerivedTickersId,document_id,url
0,Vietnam’s abandoned F1 circuit finally hosts f...,2023-01-01 00:04:48.767,BLG,ALPRG@FP,0,None
1,"Time zone by time zone, world welcomes the new...",2023-01-01 01:24:02.319,NS1,3735162ZIM,1,None
2,TOP SPORTS STORIES for : Big Rock leads the wa...,2023-01-01 05:11:39.136,NS1,4480107Z;596856Z;1022737D,2,None

## 3. Embed once with FinLang

Embed the whole corpus a single time and hand the matrix to BERTrend (it re-uses rows per slice). With ~60k headlines this is the bulk of the runtime.

In [4]:
embedder = SentenceTransformer(EMBEDDING_MODEL, device=DEVICE)

embeddings = embedder.encode(
    df[TEXT_COLUMN].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
)
assert len(embeddings) == len(df), "embeddings must align row-for-row with df"
print(f"Embeddings: {embeddings.shape}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/838 [00:00<?, ?it/s]

Embeddings: (53581, 768)

## 4. Configure BERTopic + train across time slices

`BERTopicModel` reads a TOML config. After construction we **override the vectorizer** to add a finance-boilerplate stopword list (`inc, plc, ltd, ceo, results, …`) on top of the English stopwords — this is what kills the junk clusters at the representation level. `BERTrend.train_topic_models` then fits one model per slice and merges new topics into the cumulative set when cosine ≥ `MIN_SIMILARITY` (continuation), else creates a new theme (birth).

In [5]:
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS

FINANCE_BOILERPLATE = {
    # corporate / governance boilerplate
    "inc", "plc", "ltd", "llc", "corp", "co", "sa", "ag", "nv", "group", "holdings",
    "ceo", "cfo", "coo", "cio", "chairman", "director", "board", "officer",
    "results", "report", "reports", "update", "announces", "announced", "announcement",
    "dividend", "agm", "egm", "shares", "stake", "stock", "stocks", "shareholders",
    "says", "said", "new", "year", "today", "week", "day", "amp", "via", "live",
    "review", "preview", "q1", "q2", "q3", "q4", "fy",
    # generic news filler that dominated the representations (the 'terrible labels')
    "good", "bad", "best", "better", "big", "way", "ways", "world", "global",
    "get", "gets", "make", "makes", "made", "take", "takes", "turn", "turns",
    "see", "sees", "seen", "hit", "hits", "set", "sets", "top", "back", "off",
    "total", "increase", "decrease", "change", "changes", "rise", "rises", "fall", "falls",
    "role", "call", "calls", "need", "needs", "plan", "plans", "thing", "things",
    "people", "man", "woman", "men", "women", "life", "home", "time", "times",
    "city", "limited", "release", "released", "expands", "replace", "phase",
    # sports / off-domain noise
    "win", "wins", "won", "loss", "losses", "season", "league", "cup", "match",
    "game", "games", "club", "team", "teams", "player", "players", "goal", "goals",
    "united", "sport", "sports",
}
CUSTOM_STOP_WORDS = list(ENGLISH_STOP_WORDS.union(FINANCE_BOILERPLATE))

bertopic_config = f"""
[global]
language = "English"

[bertopic_model]
top_n_words = 10
verbose = false
representation_model = ["MaximalMarginalRelevance"]
zeroshot_topic_list = []
zeroshot_min_similarity = 0

[umap_model]
n_neighbors = 15
n_components = 5
min_dist = 0.0
metric = "cosine"
random_state = {RANDOM_SEED}

[hdbscan_model]
min_cluster_size = {MIN_TOPIC_SIZE}
min_samples = {MIN_SAMPLES}
metric = "euclidean"
cluster_selection_method = "eom"
prediction_data = true

[vectorizer_model]
ngram_range = [1, 1]
stop_words = true
min_df = 3

[ctfidf_model]
bm25_weighting = false
reduce_frequent_words = true

[mmr_model]
diversity = 0.3

[reduce_outliers]
strategy = "c-tf-idf"
"""

topic_model = BERTopicModel(bertopic_config)
# Override the internal vectorizer with our extended finance stopword list.
topic_model.vectorizer_model = CountVectorizer(
    stop_words=CUSTOM_STOP_WORDS,
    token_pattern=r"(?u)\b[a-zA-Z]{3,}\b",     # alpha tokens, >= 3 chars (drops tickers/numbers)
    ngram_range=(1, 2),                         # allow phrases ("interest rate", "clean energy")
    min_df=3,
)

# Use KeyBERTInspired to re-rank candidate words by embedding similarity to the topic
# (kills generic filler like "good/way/world") then MMR for diversity. We build the models
# directly because BERTrend's factory passes tuple args (nr_repr_docs=(5,)) that crash fit().
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance  # noqa: E402

topic_model.config["bertopic_model"]["representation_model"] = [
    KeyBERTInspired(top_n_words=20, nr_repr_docs=5, nr_candidate_words=40),
    MaximalMarginalRelevance(diversity=0.4),
]

# BERTrend._train_by_period calls fit() WITHOUT forwarding embedding_model, so BERTopic's
# embedding_model is None — fine for MMR but KeyBERTInspired needs it to embed candidate
# words/representative docs. Wrap fit to inject our FinLang embedder by default.
import functools  # noqa: E402

_orig_fit = topic_model.fit


@functools.wraps(_orig_fit)
def _fit_with_embedder(*args, **kwargs):
    kwargs.setdefault("embedding_model", embedder)
    return _orig_fit(*args, **kwargs)


topic_model.fit = _fit_with_embedder

bertrend = BERTrend(topic_model=topic_model)
bertrend.config["granularity"] = GRANULARITY_DAYS
bertrend.config["min_similarity"] = MIN_SIMILARITY

grouped_data = group_by_days(df=df, day_granularity=GRANULARITY_DAYS)
grouped_data = {ts: g for ts, g in grouped_data.items() if not g.empty}
print(f"Time slices: {len(grouped_data)}  (granularity = {GRANULARITY_DAYS}d)")
print(f"docs/slice — min {min(len(g) for g in grouped_data.values())}, "
      f"median {int(np.median([len(g) for g in grouped_data.values()]))}, "
      f"max {max(len(g) for g in grouped_data.values())}")

Time slices: 53  (granularity = 14d)
docs/slice — min 106, median 1027, max 1228

In [6]:
# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.
bertrend.train_topic_models(
    grouped_data=grouped_data,
    embedding_model=embedder,
    embeddings=embeddings,
    bertrend_models_path=MODELS_DIR,
    save_topic_models=True,
)
# Detach the SentenceTransformer before pickling: injecting it for KeyBERT makes the
# trained model + our fit-wrapper hold an unpicklable sqlite3.Connection. None of the
# downstream steps (popularity, signals, Sankey) need the embedder.
topic_model.fit = _orig_fit
if bertrend.last_topic_model is not None:
    bertrend.last_topic_model.embedding_model = None
bertrend.save_model(models_path=MODELS_DIR)

print(f"Trained periods:  {len(bertrend.doc_groups)}")
print(f"Merged themes:    {bertrend.merged_df['Topic'].nunique() if bertrend.merged_df is not None else 0}")

2026-06-08 16:14:27.631 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 1/53...

2026-06-08 16:14:27.632 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-01-01 00:00:00

2026-06-08 16:14:27.633 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1018

2026-06-08 16:14:27.633 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:27.634 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:27.653 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:27.654 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:33.516 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:33.519 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:33,519 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:33.970 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:33.971 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:33.977 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-01-01 00:00:00...

2026-06-08 16:14:33.979 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-01-01 00:00:00

2026-06-08 16:14:33.980 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 2/53...

2026-06-08 16:14:33.980 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-01-15 00:00:00

2026-06-08 16:14:33.981 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1063

2026-06-08 16:14:33.981 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:33.981 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:33.981 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:33.981 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:35.988 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:35.991 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:35,991 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:36.586 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:36.587 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:36.592 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-01-01 00:00:00 and 2023-01-15 00:00:00

2026-06-08 16:14:36.608 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-01-15 00:00:00 merged successfully with others

2026-06-08 16:14:36.609 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-01-15 00:00:00...

2026-06-08 16:14:36.611 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-01-15 00:00:00

2026-06-08 16:14:36.611 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 3/53...

2026-06-08 16:14:36.612 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-01-29 00:00:00

2026-06-08 16:14:36.612 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1199

2026-06-08 16:14:36.612 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:36.612 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:36.612 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:36.613 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:38.835 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:38.839 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:38,839 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:39.413 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:39.413 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:39.420 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-01-15 00:00:00 and 2023-01-29 00:00:00

2026-06-08 16:14:39.434 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-01-29 00:00:00 merged successfully with others

2026-06-08 16:14:39.434 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-01-29 00:00:00...

2026-06-08 16:14:39.437 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-01-29 00:00:00

2026-06-08 16:14:39.437 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 4/53...

2026-06-08 16:14:39.438 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-02-12 00:00:00

2026-06-08 16:14:39.438 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1228

2026-06-08 16:14:39.438 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:39.438 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:39.439 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:39.439 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:41.674 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:41.676 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:41,677 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:42.101 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:42.101 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:42.106 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-01-29 00:00:00 and 2023-02-12 00:00:00

2026-06-08 16:14:42.117 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-02-12 00:00:00 merged successfully with others

2026-06-08 16:14:42.118 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-02-12 00:00:00...

2026-06-08 16:14:42.120 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-02-12 00:00:00

2026-06-08 16:14:42.120 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 5/53...

2026-06-08 16:14:42.121 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-02-26 00:00:00

2026-06-08 16:14:42.121 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1177

2026-06-08 16:14:42.121 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:42.121 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:42.121 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:42.122 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:44.128 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:44.131 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:44,131 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:44.567 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:44.567 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:44.573 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-02-12 00:00:00 and 2023-02-26 00:00:00

2026-06-08 16:14:44.584 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-02-26 00:00:00 merged successfully with others

2026-06-08 16:14:44.584 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-02-26 00:00:00...

2026-06-08 16:14:44.586 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-02-26 00:00:00

2026-06-08 16:14:44.586 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 6/53...

2026-06-08 16:14:44.587 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-03-12 00:00:00

2026-06-08 16:14:44.587 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1184

2026-06-08 16:14:44.587 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:44.587 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:44.587 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:44.587 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:46.540 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:46.542 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:46,543 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:46.987 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:46.988 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:46.993 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-02-26 00:00:00 and 2023-03-12 00:00:00

2026-06-08 16:14:47.004 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-03-12 00:00:00 merged successfully with others

2026-06-08 16:14:47.004 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-03-12 00:00:00...

2026-06-08 16:14:47.007 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-03-12 00:00:00

2026-06-08 16:14:47.007 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 7/53...

2026-06-08 16:14:47.008 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-03-26 00:00:00

2026-06-08 16:14:47.008 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1117

2026-06-08 16:14:47.008 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:47.008 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:47.008 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:47.008 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:48.872 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:48.874 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:48,875 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:49.338 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:49.339 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:49.344 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-03-12 00:00:00 and 2023-03-26 00:00:00

2026-06-08 16:14:49.356 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-03-26 00:00:00 merged successfully with others

2026-06-08 16:14:49.356 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-03-26 00:00:00...

2026-06-08 16:14:49.358 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-03-26 00:00:00

2026-06-08 16:14:49.358 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 8/53...

2026-06-08 16:14:49.359 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-04-09 00:00:00

2026-06-08 16:14:49.359 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1100

2026-06-08 16:14:49.359 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:49.359 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:49.359 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:49.360 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:50.763 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: max_df corresponds to < documents than min_df

2026-06-08 16:14:50.763 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Prince Harry and Meghan Markle’s $ .7K embarrassment', 'Centre denies plans of milk and dairy import', 'Congress b...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.07067995, -0.02893152, -0.00531985, ...,  0.01827159,
                    │           │             │                0.0592464 , -0.00128599],
                    │           │             │              [-0.00932915,  0.0...
                    │           │             └ ['Prince Harry and Meghan Markle’s $ .7K embarrassment', 'Centre denies plans of milk and dairy import', 'Congress brands ame...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Prince Harry and Meghan Markle’s $ .7K embarra...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Prince Harry and Meghan Markle’s $ .7K embarrassment Centre denies plans of milk and dairy import Congress brands amended I...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Prince Harry and Meghan Markle’s $ .7K embarrassment Centre denies plans of milk and dairy import Congress brands amended ...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:14:50.772 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2023-04-09 00:00:00: max_df corresponds to < documents than min_df

2026-06-08 16:14:50.772 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Prince Harry and Meghan Markle’s $ .7K embarrassment', 'Centre denies plans of milk and dairy import', 'Congress b...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.07067995, -0.02893152, -0.00531985, ...,  0.01827159,
                    │           │             │                0.0592464 , -0.00128599],
                    │           │             │              [-0.00932915,  0.0...
                    │           │             └ ['Prince Harry and Meghan Markle’s $ .7K embarrassment', 'Centre denies plans of milk and dairy import', 'Congress brands ame...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Prince Harry and Meghan Markle’s $ .7K embarra...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Prince Harry and Meghan Markle’s $ .7K embarrassment Centre denies plans of milk and dairy import Congress brands amended I...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5037ba40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Prince Harry and Meghan Markle’s $ .7K embarrassment Centre denies plans of milk and dairy import Congress brands amended ...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:14:50.777 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 9/53...

2026-06-08 16:14:50.777 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-04-23 00:00:00

2026-06-08 16:14:50.777 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1198

2026-06-08 16:14:50.778 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:50.778 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:50.778 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:50.778 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:52.921 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:52.924 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:52,924 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:53.509 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:53.509 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:53.517 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-03-26 00:00:00 and 2023-04-23 00:00:00

2026-06-08 16:14:53.534 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-04-23 00:00:00 merged successfully with others

2026-06-08 16:14:53.535 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-04-23 00:00:00...

2026-06-08 16:14:53.537 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-04-23 00:00:00

2026-06-08 16:14:53.538 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 10/53...

2026-06-08 16:14:53.538 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-05-07 00:00:00

2026-06-08 16:14:53.538 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1221

2026-06-08 16:14:53.539 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:53.539 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:53.540 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:53.540 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:55.730 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:55.733 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:55,733 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:56.206 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:56.207 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:56.212 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-04-23 00:00:00 and 2023-05-07 00:00:00

2026-06-08 16:14:56.224 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-05-07 00:00:00 merged successfully with others

2026-06-08 16:14:56.225 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-05-07 00:00:00...

2026-06-08 16:14:56.227 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-05-07 00:00:00

2026-06-08 16:14:56.227 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 11/53...

2026-06-08 16:14:56.228 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-05-21 00:00:00

2026-06-08 16:14:56.228 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1124

2026-06-08 16:14:56.228 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:56.228 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:56.229 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:56.229 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:14:58.123 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:14:58.125 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:14:58,125 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:14:58.607 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:14:58.607 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:14:58.615 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-05-07 00:00:00 and 2023-05-21 00:00:00

2026-06-08 16:14:58.626 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-05-21 00:00:00 merged successfully with others

2026-06-08 16:14:58.626 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-05-21 00:00:00...

2026-06-08 16:14:58.628 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-05-21 00:00:00

2026-06-08 16:14:58.628 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 12/53...

2026-06-08 16:14:58.629 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-06-04 00:00:00

2026-06-08 16:14:58.629 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1085

2026-06-08 16:14:58.629 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:14:58.629 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:14:58.629 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:14:58.629 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:00.454 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:00.457 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:00,457 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:00.873 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:00.873 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:00.878 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-05-21 00:00:00 and 2023-06-04 00:00:00

2026-06-08 16:15:00.887 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-06-04 00:00:00 merged successfully with others

2026-06-08 16:15:00.888 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-06-04 00:00:00...

2026-06-08 16:15:00.890 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-06-04 00:00:00

2026-06-08 16:15:00.890 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 13/53...

2026-06-08 16:15:00.890 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-06-18 00:00:00

2026-06-08 16:15:00.890 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1047

2026-06-08 16:15:00.890 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:00.891 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:00.891 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:00.891 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:02.753 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:02.757 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:02,758 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:03.095 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:03.095 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:03.100 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-06-04 00:00:00 and 2023-06-18 00:00:00

2026-06-08 16:15:03.108 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-06-18 00:00:00 merged successfully with others

2026-06-08 16:15:03.108 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-06-18 00:00:00...

2026-06-08 16:15:03.110 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-06-18 00:00:00

2026-06-08 16:15:03.111 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 14/53...

2026-06-08 16:15:03.111 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-07-02 00:00:00

2026-06-08 16:15:03.111 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1012

2026-06-08 16:15:03.111 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:03.111 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:03.111 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:03.112 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:04.735 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:04.737 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:04,738 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:05.209 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:05.209 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:05.215 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-06-18 00:00:00 and 2023-07-02 00:00:00

2026-06-08 16:15:05.224 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-07-02 00:00:00 merged successfully with others

2026-06-08 16:15:05.225 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-07-02 00:00:00...

2026-06-08 16:15:05.227 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-07-02 00:00:00

2026-06-08 16:15:05.227 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 15/53...

2026-06-08 16:15:05.228 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-07-16 00:00:00

2026-06-08 16:15:05.228 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1159

2026-06-08 16:15:05.228 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:05.228 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:05.228 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:05.228 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:07.073 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:07.076 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:07,076 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:07.505 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:07.506 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:07.512 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-07-02 00:00:00 and 2023-07-16 00:00:00

2026-06-08 16:15:07.524 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-07-16 00:00:00 merged successfully with others

2026-06-08 16:15:07.524 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-07-16 00:00:00...

2026-06-08 16:15:07.526 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-07-16 00:00:00

2026-06-08 16:15:07.526 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 16/53...

2026-06-08 16:15:07.527 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-07-30 00:00:00

2026-06-08 16:15:07.527 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1169

2026-06-08 16:15:07.527 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:07.527 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:07.527 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:07.527 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:09.406 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:09.409 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:09,409 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:09.904 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:09.905 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:09.910 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-07-16 00:00:00 and 2023-07-30 00:00:00

2026-06-08 16:15:09.921 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-07-30 00:00:00 merged successfully with others

2026-06-08 16:15:09.921 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-07-30 00:00:00...

2026-06-08 16:15:09.923 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-07-30 00:00:00

2026-06-08 16:15:09.923 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 17/53...

2026-06-08 16:15:09.924 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-08-13 00:00:00

2026-06-08 16:15:09.924 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1019

2026-06-08 16:15:09.924 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:09.924 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:09.924 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:09.924 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:11.490 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:11.492 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:11,492 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:11.828 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:11.828 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:11.833 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-07-30 00:00:00 and 2023-08-13 00:00:00

2026-06-08 16:15:11.842 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-08-13 00:00:00 merged successfully with others

2026-06-08 16:15:11.842 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-08-13 00:00:00...

2026-06-08 16:15:11.844 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-08-13 00:00:00

2026-06-08 16:15:11.844 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 18/53...

2026-06-08 16:15:11.845 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-08-27 00:00:00

2026-06-08 16:15:11.845 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 956

2026-06-08 16:15:11.845 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:11.845 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:11.845 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:11.846 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:13.178 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:13.178 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:13,179 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:13.185 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: object of type 'numpy.float64' has no len()

2026-06-08 16:15:13.185 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Jordan Wicks wins his big-league debut for the Chicago Cubs, who hold on to beat the Pittsburgh Pirates -', 'Michi...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 290, in fit
    topic_model.update_topics(
    │           └ <function BERTopic.update_topics at 0x1596ef420>
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 1580, in update_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Elon Musk Said X Will Remove the Block Feature...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 12 stored elements and shape (3, 4)>
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4449, in _c_tf_idf
    self.ctfidf_model = self.ctfidf_model.fit(X, multiplier=multiplier)
    │    │              │    │            │   │             └ None
    │    │              │    │            │   └ <Compressed Sparse Row sparse matrix of dtype 'int64'
    │    │              │    │            │     	with 3 stored elements and shape (3, 1)>
    │    │              │    │            └ <function ClassTfidfTransformer.fit at 0x1596ede40>
    │    │              │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    │    │              └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
    │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/vectorizers/_ctfidf.py", line 88, in fit
    self._idf_diag = sp.diags(
    │    │           │  └ <function diags at 0x115019c60>
    │    │           └ <module 'scipy.sparse' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sc...
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 4 stored elements and shape (4, 4)>
    └ ClassTfidfTransformer(reduce_frequent_words=True)
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 543, in diags
    A = diags_array(diagonals, offsets=offsets, shape=shape, dtype=dtype)
        │           │                  │              │            └ <class 'numpy.float64'>
        │           │                  │              └ (1, 1)
        │           │                  └ 0
        │           └ np.float64(0.28768207245178085)
        └ <function diags_array at 0x115019bc0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 367, in diags_array
    if len(diagonals) == 0 or isscalarlike(diagonals[0]):
           │                  │            └ np.float64(0.28768207245178085)
           │                  └ <function isscalarlike at 0x114f4a660>
           └ np.float64(0.28768207245178085)

TypeError: object of type 'numpy.float64' has no len()

2026-06-08 16:15:13.189 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2023-08-27 00:00:00: object of type 'numpy.float64' has no len()

2026-06-08 16:15:13.189 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Jordan Wicks wins his big-league debut for the Chicago Cubs, who hold on to beat the Pittsburgh Pirates -', 'Michi...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 290, in fit
    topic_model.update_topics(
    │           └ <function BERTopic.update_topics at 0x1596ef420>
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 1580, in update_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Elon Musk Said X Will Remove the Block Feature...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 12 stored elements and shape (3, 4)>
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4449, in _c_tf_idf
    self.ctfidf_model = self.ctfidf_model.fit(X, multiplier=multiplier)
    │    │              │    │            │   │             └ None
    │    │              │    │            │   └ <Compressed Sparse Row sparse matrix of dtype 'int64'
    │    │              │    │            │     	with 3 stored elements and shape (3, 1)>
    │    │              │    │            └ <function ClassTfidfTransformer.fit at 0x1596ede40>
    │    │              │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    │    │              └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
    │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    └ <bertopic._bertopic.BERTopic object at 0xc503a45f0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/vectorizers/_ctfidf.py", line 88, in fit
    self._idf_diag = sp.diags(
    │    │           │  └ <function diags at 0x115019c60>
    │    │           └ <module 'scipy.sparse' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sc...
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 4 stored elements and shape (4, 4)>
    └ ClassTfidfTransformer(reduce_frequent_words=True)
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 543, in diags
    A = diags_array(diagonals, offsets=offsets, shape=shape, dtype=dtype)
        │           │                  │              │            └ <class 'numpy.float64'>
        │           │                  │              └ (1, 1)
        │           │                  └ 0
        │           └ np.float64(0.28768207245178085)
        └ <function diags_array at 0x115019bc0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 367, in diags_array
    if len(diagonals) == 0 or isscalarlike(diagonals[0]):
           │                  │            └ np.float64(0.28768207245178085)
           │                  └ <function isscalarlike at 0x114f4a660>
           └ np.float64(0.28768207245178085)

TypeError: object of type 'numpy.float64' has no len()

2026-06-08 16:15:13.191 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 19/53...

2026-06-08 16:15:13.192 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-09-10 00:00:00

2026-06-08 16:15:13.192 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1102

2026-06-08 16:15:13.192 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:13.192 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:13.192 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:13.193 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:15.130 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:15.132 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:15,132 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:15.565 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:15.566 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:15.571 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-08-13 00:00:00 and 2023-09-10 00:00:00

2026-06-08 16:15:15.581 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-09-10 00:00:00 merged successfully with others

2026-06-08 16:15:15.582 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-09-10 00:00:00...

2026-06-08 16:15:15.584 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-09-10 00:00:00

2026-06-08 16:15:15.584 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 20/53...

2026-06-08 16:15:15.584 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-09-24 00:00:00

2026-06-08 16:15:15.585 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1055

2026-06-08 16:15:15.585 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:15.585 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:15.585 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:15.585 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:17.296 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:17.299 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:17,299 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:17.728 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:17.729 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:17.735 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-09-10 00:00:00 and 2023-09-24 00:00:00

2026-06-08 16:15:17.746 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-09-24 00:00:00 merged successfully with others

2026-06-08 16:15:17.747 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-09-24 00:00:00...

2026-06-08 16:15:17.749 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-09-24 00:00:00

2026-06-08 16:15:17.749 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 21/53...

2026-06-08 16:15:17.750 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-10-08 00:00:00

2026-06-08 16:15:17.750 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1071

2026-06-08 16:15:17.750 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:17.751 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:17.751 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:17.751 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:19.501 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:19.503 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:19,503 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:19.922 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:19.923 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:19.929 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-09-24 00:00:00 and 2023-10-08 00:00:00

2026-06-08 16:15:19.946 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-10-08 00:00:00 merged successfully with others

2026-06-08 16:15:19.947 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-10-08 00:00:00...

2026-06-08 16:15:19.950 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-10-08 00:00:00

2026-06-08 16:15:19.950 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 22/53...

2026-06-08 16:15:19.951 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-10-22 00:00:00

2026-06-08 16:15:19.951 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1182

2026-06-08 16:15:19.952 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:19.952 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:19.952 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:19.952 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:21.449 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: max_df corresponds to < documents than min_df

2026-06-08 16:15:21.449 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Climb the stairs to lower your risk of heart disease', ': Hamas apologists plague Ivory Tower', 'Hundreds protest ...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.03602408, -0.01538955,  0.04922836, ...,  0.0137845 ,
                    │           │             │               -0.04298078, -0.00539501],
                    │           │             │              [-0.02911547,  0.0...
                    │           │             └ ['Climb the stairs to lower your risk of heart disease', ': Hamas apologists plague Ivory Tower', 'Hundreds protest in San Di...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Climb the stairs to lower your risk of heart d...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Climb the stairs to lower your risk of heart disease : Hamas apologists plague Ivory Tower Hundreds protest in San Diego fo...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Climb the stairs to lower your risk of heart disease : Hamas apologists plague Ivory Tower Hundreds protest in San Diego f...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:15:21.453 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2023-10-22 00:00:00: max_df corresponds to < documents than min_df

2026-06-08 16:15:21.453 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Climb the stairs to lower your risk of heart disease', ': Hamas apologists plague Ivory Tower', 'Hundreds protest ...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.03602408, -0.01538955,  0.04922836, ...,  0.0137845 ,
                    │           │             │               -0.04298078, -0.00539501],
                    │           │             │              [-0.02911547,  0.0...
                    │           │             └ ['Climb the stairs to lower your risk of heart disease', ': Hamas apologists plague Ivory Tower', 'Hundreds protest in San Di...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Climb the stairs to lower your risk of heart d...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Climb the stairs to lower your risk of heart disease : Hamas apologists plague Ivory Tower Hundreds protest in San Diego fo...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc509fcdd0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Climb the stairs to lower your risk of heart disease : Hamas apologists plague Ivory Tower Hundreds protest in San Diego f...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:15:21.457 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 23/53...

2026-06-08 16:15:21.457 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-11-05 00:00:00

2026-06-08 16:15:21.457 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1164

2026-06-08 16:15:21.457 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:21.457 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:21.458 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:21.458 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:23.016 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:23.016 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:23,016 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:23.022 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:15:23.022 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['CSR Impact Assessment Report FY2023 - Akhand Jyoti Eye Hospital', 'Kuchar blows -shot lead with late collapse, fal...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 290, in fit
    topic_model.update_topics(
    │           └ <function BERTopic.update_topics at 0x1596ef420>
    └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 1580, in update_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Pinoys from Gaza set to arrive today *KUWAIT S...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 12 stored elements and shape (3, 4)>
    └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Pinoys from Gaza set to arrive today *KUWAIT SETS DEC. CRUDE TO MED REGION AT $ . /BBL PREMIUM How many foreign citizens fr...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Pinoys from Gaza set to arrive today *KUWAIT SETS DEC. CRUDE TO MED REGION AT $ . /BBL PREMIUM How many foreign citizens f...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:15:23.025 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2023-11-05 00:00:00: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:15:23.026 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['CSR Impact Assessment Report FY2023 - Akhand Jyoti Eye Hospital', 'Kuchar blows -shot lead with late collapse, fal...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 290, in fit
    topic_model.update_topics(
    │           └ <function BERTopic.update_topics at 0x1596ef420>
    └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 1580, in update_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Pinoys from Gaza set to arrive today *KUWAIT S...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 12 stored elements and shape (3, 4)>
    └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Pinoys from Gaza set to arrive today *KUWAIT SETS DEC. CRUDE TO MED REGION AT $ . /BBL PREMIUM How many foreign citizens fr...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc508d7b30>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Pinoys from Gaza set to arrive today *KUWAIT SETS DEC. CRUDE TO MED REGION AT $ . /BBL PREMIUM How many foreign citizens f...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:15:23.028 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 24/53...

2026-06-08 16:15:23.029 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-11-19 00:00:00

2026-06-08 16:15:23.029 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 965

2026-06-08 16:15:23.029 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:23.029 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:23.030 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:23.030 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:24.516 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:24.518 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:24,519 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:24.922 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:24.922 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:24.927 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-10-08 00:00:00 and 2023-11-19 00:00:00

2026-06-08 16:15:24.936 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-11-19 00:00:00 merged successfully with others

2026-06-08 16:15:24.937 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-11-19 00:00:00...

2026-06-08 16:15:24.938 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-11-19 00:00:00

2026-06-08 16:15:24.939 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 25/53...

2026-06-08 16:15:24.939 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-12-03 00:00:00

2026-06-08 16:15:24.939 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1046

2026-06-08 16:15:24.939 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:24.940 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:24.940 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:24.940 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:26.600 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:26.602 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:26,602 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:27.027 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:27.027 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:27.033 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-11-19 00:00:00 and 2023-12-03 00:00:00

2026-06-08 16:15:27.042 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-12-03 00:00:00 merged successfully with others

2026-06-08 16:15:27.042 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-12-03 00:00:00...

2026-06-08 16:15:27.044 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-12-03 00:00:00

2026-06-08 16:15:27.044 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 26/53...

2026-06-08 16:15:27.045 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-12-17 00:00:00

2026-06-08 16:15:27.045 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 791

2026-06-08 16:15:27.045 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:27.045 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:27.046 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:27.046 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:28.190 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:28.192 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:28,192 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:28.571 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:28.571 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:28.578 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-12-03 00:00:00 and 2023-12-17 00:00:00

2026-06-08 16:15:28.588 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2023-12-17 00:00:00 merged successfully with others

2026-06-08 16:15:28.589 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2023-12-17 00:00:00...

2026-06-08 16:15:28.591 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2023-12-17 00:00:00

2026-06-08 16:15:28.591 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 27/53...

2026-06-08 16:15:28.592 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2023-12-31 00:00:00

2026-06-08 16:15:28.592 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 911

2026-06-08 16:15:28.592 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:28.593 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:28.593 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:28.593 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:29.686 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: max_df corresponds to < documents than min_df

2026-06-08 16:15:29.686 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['‘Look you fly spirit if you wanna become a spirit’: Spirit Airlines passenger brings his own parachute to the', "G...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.05607631, -0.03330243, -0.00754313, ...,  0.0087205 ,
                    │           │             │                0.00097798, -0.02878226],
                    │           │             │              [-0.0718037 , -0.0...
                    │           │             └ ['‘Look you fly spirit if you wanna become a spirit’: Spirit Airlines passenger brings his own parachute to the', "Gary Nevil...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Gary Neville delivers scathing verdict of Manc...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Gary Neville delivers scathing verdict of Manchester United\'s transfer strategy as he claims Antony is \'nowhere near\' th...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Gary Neville delivers scathing verdict of Manchester United\'s transfer strategy as he claims Antony is \'nowhere near\' t...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:15:29.690 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2023-12-31 00:00:00: max_df corresponds to < documents than min_df

2026-06-08 16:15:29.691 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['‘Look you fly spirit if you wanna become a spirit’: Spirit Airlines passenger brings his own parachute to the', "G...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.05607631, -0.03330243, -0.00754313, ...,  0.0087205 ,
                    │           │             │                0.00097798, -0.02878226],
                    │           │             │              [-0.0718037 , -0.0...
                    │           │             └ ['‘Look you fly spirit if you wanna become a spirit’: Spirit Airlines passenger brings his own parachute to the', "Gary Nevil...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Gary Neville delivers scathing verdict of Manc...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['Gary Neville delivers scathing verdict of Manchester United\'s transfer strategy as he claims Antony is \'nowhere near\' th...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5099b320>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['Gary Neville delivers scathing verdict of Manchester United\'s transfer strategy as he claims Antony is \'nowhere near\' t...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1396, in fit_transform
    raise ValueError("max_df corresponds to < documents than min_df")

ValueError: max_df corresponds to < documents than min_df

2026-06-08 16:15:29.694 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 28/53...

2026-06-08 16:15:29.694 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-01-14 00:00:00

2026-06-08 16:15:29.695 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 989

2026-06-08 16:15:29.695 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:29.695 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:29.695 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:29.695 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:31.340 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:31.343 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:31,343 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:31.796 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:31.796 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:31.801 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2023-12-17 00:00:00 and 2024-01-14 00:00:00

2026-06-08 16:15:31.812 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-01-14 00:00:00 merged successfully with others

2026-06-08 16:15:31.812 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-01-14 00:00:00...

2026-06-08 16:15:31.814 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-01-14 00:00:00

2026-06-08 16:15:31.814 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 29/53...

2026-06-08 16:15:31.815 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-01-28 00:00:00

2026-06-08 16:15:31.815 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1062

2026-06-08 16:15:31.815 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:31.815 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:31.815 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:31.816 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:33.525 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:33.528 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:33,528 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:33.998 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:33.998 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:34.003 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-01-14 00:00:00 and 2024-01-28 00:00:00

2026-06-08 16:15:34.013 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-01-28 00:00:00 merged successfully with others

2026-06-08 16:15:34.013 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-01-28 00:00:00...

2026-06-08 16:15:34.015 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-01-28 00:00:00

2026-06-08 16:15:34.015 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 30/53...

2026-06-08 16:15:34.016 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-02-11 00:00:00

2026-06-08 16:15:34.016 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1044

2026-06-08 16:15:34.016 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:34.016 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:34.016 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:34.017 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:35.762 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:35.764 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:35,764 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:36.266 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:36.267 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:36.272 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-01-28 00:00:00 and 2024-02-11 00:00:00

2026-06-08 16:15:36.283 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-02-11 00:00:00 merged successfully with others

2026-06-08 16:15:36.283 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-02-11 00:00:00...

2026-06-08 16:15:36.285 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-02-11 00:00:00

2026-06-08 16:15:36.285 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 31/53...

2026-06-08 16:15:36.286 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-02-25 00:00:00

2026-06-08 16:15:36.286 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1207

2026-06-08 16:15:36.286 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:36.286 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:36.286 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:36.286 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:38.281 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:38.284 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:38,284 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:38.854 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:38.854 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:38.859 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-02-11 00:00:00 and 2024-02-25 00:00:00

2026-06-08 16:15:38.870 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-02-25 00:00:00 merged successfully with others

2026-06-08 16:15:38.870 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-02-25 00:00:00...

2026-06-08 16:15:38.872 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-02-25 00:00:00

2026-06-08 16:15:38.872 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 32/53...

2026-06-08 16:15:38.873 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-03-10 00:00:00

2026-06-08 16:15:38.873 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1000

2026-06-08 16:15:38.873 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:38.873 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:38.874 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:38.874 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:40.350 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:40.351 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:40,351 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:40.651 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:40.652 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:40.656 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-02-25 00:00:00 and 2024-03-10 00:00:00

2026-06-08 16:15:40.664 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-03-10 00:00:00 merged successfully with others

2026-06-08 16:15:40.665 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-03-10 00:00:00...

2026-06-08 16:15:40.666 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-03-10 00:00:00

2026-06-08 16:15:40.667 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 33/53...

2026-06-08 16:15:40.667 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-03-24 00:00:00

2026-06-08 16:15:40.667 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 928

2026-06-08 16:15:40.667 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:40.668 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:40.668 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:40.668 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:42.061 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:42.062 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:42,063 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:42.484 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:42.484 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:42.489 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-03-10 00:00:00 and 2024-03-24 00:00:00

2026-06-08 16:15:42.497 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-03-24 00:00:00 merged successfully with others

2026-06-08 16:15:42.498 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-03-24 00:00:00...

2026-06-08 16:15:42.500 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-03-24 00:00:00

2026-06-08 16:15:42.500 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 34/53...

2026-06-08 16:15:42.500 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-04-07 00:00:00

2026-06-08 16:15:42.500 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 925

2026-06-08 16:15:42.501 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:42.501 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:42.501 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:42.501 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:43.915 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:43.916 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:43,917 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:44.286 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:44.287 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:44.292 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-03-24 00:00:00 and 2024-04-07 00:00:00

2026-06-08 16:15:44.300 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-04-07 00:00:00 merged successfully with others

2026-06-08 16:15:44.300 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-04-07 00:00:00...

2026-06-08 16:15:44.302 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-04-07 00:00:00

2026-06-08 16:15:44.302 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 35/53...

2026-06-08 16:15:44.303 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-04-21 00:00:00

2026-06-08 16:15:44.303 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1195

2026-06-08 16:15:44.303 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:44.303 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:44.303 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:44.303 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:46.178 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:46.181 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:46,181 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:46.565 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:46.565 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:46.570 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-04-07 00:00:00 and 2024-04-21 00:00:00

2026-06-08 16:15:46.580 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-04-21 00:00:00 merged successfully with others

2026-06-08 16:15:46.580 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-04-21 00:00:00...

2026-06-08 16:15:46.582 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-04-21 00:00:00

2026-06-08 16:15:46.582 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 36/53...

2026-06-08 16:15:46.582 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-05-05 00:00:00

2026-06-08 16:15:46.583 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1083

2026-06-08 16:15:46.583 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:46.583 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:46.583 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:46.583 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:48.353 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:48.356 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:48,356 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:48.807 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:48.807 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:48.813 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-04-21 00:00:00 and 2024-05-05 00:00:00

2026-06-08 16:15:48.823 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-05-05 00:00:00 merged successfully with others

2026-06-08 16:15:48.824 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-05-05 00:00:00...

2026-06-08 16:15:48.826 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-05-05 00:00:00

2026-06-08 16:15:48.826 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 37/53...

2026-06-08 16:15:48.827 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-05-19 00:00:00

2026-06-08 16:15:48.827 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 936

2026-06-08 16:15:48.827 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:48.827 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:48.827 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:48.828 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:50.212 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:50.214 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:50,214 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:50.536 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:50.536 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:50.542 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-05-05 00:00:00 and 2024-05-19 00:00:00

2026-06-08 16:15:50.552 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-05-19 00:00:00 merged successfully with others

2026-06-08 16:15:50.552 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-05-19 00:00:00...

2026-06-08 16:15:50.554 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-05-19 00:00:00

2026-06-08 16:15:50.554 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 38/53...

2026-06-08 16:15:50.555 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-06-02 00:00:00

2026-06-08 16:15:50.555 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 942

2026-06-08 16:15:50.555 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:50.555 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:50.556 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:50.556 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:51.972 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:51.974 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:51,974 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:52.320 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:52.321 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:52.326 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-05-19 00:00:00 and 2024-06-02 00:00:00

2026-06-08 16:15:52.334 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-06-02 00:00:00 merged successfully with others

2026-06-08 16:15:52.335 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-06-02 00:00:00...

2026-06-08 16:15:52.336 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-06-02 00:00:00

2026-06-08 16:15:52.337 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 39/53...

2026-06-08 16:15:52.337 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-06-16 00:00:00

2026-06-08 16:15:52.337 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 910

2026-06-08 16:15:52.337 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:52.338 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:52.338 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:52.338 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:53.719 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:53.721 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:53,721 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:54.064 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:54.064 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:54.069 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-06-02 00:00:00 and 2024-06-16 00:00:00

2026-06-08 16:15:54.078 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-06-16 00:00:00 merged successfully with others

2026-06-08 16:15:54.078 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-06-16 00:00:00...

2026-06-08 16:15:54.080 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-06-16 00:00:00

2026-06-08 16:15:54.081 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 40/53...

2026-06-08 16:15:54.081 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-06-30 00:00:00

2026-06-08 16:15:54.081 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 835

2026-06-08 16:15:54.081 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:54.082 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:54.082 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:54.082 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:56.211 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:56.215 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:56,215 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:56.521 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:56.521 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:56.529 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-06-16 00:00:00 and 2024-06-30 00:00:00

2026-06-08 16:15:56.539 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-06-30 00:00:00 merged successfully with others

2026-06-08 16:15:56.539 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-06-30 00:00:00...

2026-06-08 16:15:56.542 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-06-30 00:00:00

2026-06-08 16:15:56.542 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 41/53...

2026-06-08 16:15:56.544 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-07-14 00:00:00

2026-06-08 16:15:56.544 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1017

2026-06-08 16:15:56.544 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:56.544 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:56.545 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:56.545 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:57.781 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: object of type 'numpy.float64' has no len()

2026-06-08 16:15:57.781 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Ways to Unite As a Nation After the Attempted Assassination of Trump | Opinion', "Revolut's new banking licence st...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-2.7722223e-02, -4.9345616e-02,  7.3853643e-03, ...,
                    │           │             │                2.7006801e-02, -3.7503969e-02, -2.2055220e-02],
                    │           │             │              ...
                    │           │             └ ['Ways to Unite As a Nation After the Attempted Assassination of Trump | Opinion', "Revolut's new banking licence strategy", ...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Ways to Unite As a Nation After the Attempted ...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4449, in _c_tf_idf
    self.ctfidf_model = self.ctfidf_model.fit(X, multiplier=multiplier)
    │    │              │    │            │   │             └ None
    │    │              │    │            │   └ <Compressed Sparse Row sparse matrix of dtype 'int64'
    │    │              │    │            │     	with 3 stored elements and shape (3, 1)>
    │    │              │    │            └ <function ClassTfidfTransformer.fit at 0x1596ede40>
    │    │              │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    │    │              └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
    │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/vectorizers/_ctfidf.py", line 88, in fit
    self._idf_diag = sp.diags(
    │    │           │  └ <function diags at 0x115019c60>
    │    │           └ <module 'scipy.sparse' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sc...
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 187 stored elements and shape (187, 187)>
    └ ClassTfidfTransformer(reduce_frequent_words=True)
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 543, in diags
    A = diags_array(diagonals, offsets=offsets, shape=shape, dtype=dtype)
        │           │                  │              │            └ <class 'numpy.float64'>
        │           │                  │              └ (1, 1)
        │           │                  └ 0
        │           └ np.float64(0.22314355131420976)
        └ <function diags_array at 0x115019bc0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 367, in diags_array
    if len(diagonals) == 0 or isscalarlike(diagonals[0]):
           │                  │            └ np.float64(0.22314355131420976)
           │                  └ <function isscalarlike at 0x114f4a660>
           └ np.float64(0.22314355131420976)

TypeError: object of type 'numpy.float64' has no len()

2026-06-08 16:15:57.785 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2024-07-14 00:00:00: object of type 'numpy.float64' has no len()

2026-06-08 16:15:57.785 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Ways to Unite As a Nation After the Attempted Assassination of Trump | Opinion', "Revolut's new banking licence st...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-2.7722223e-02, -4.9345616e-02,  7.3853643e-03, ...,
                    │           │             │                2.7006801e-02, -3.7503969e-02, -2.2055220e-02],
                    │           │             │              ...
                    │           │             └ ['Ways to Unite As a Nation After the Attempted Assassination of Trump | Opinion', "Revolut's new banking licence strategy", ...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0      0  Ways to Unite As a Nation After the Attempted ...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4449, in _c_tf_idf
    self.ctfidf_model = self.ctfidf_model.fit(X, multiplier=multiplier)
    │    │              │    │            │   │             └ None
    │    │              │    │            │   └ <Compressed Sparse Row sparse matrix of dtype 'int64'
    │    │              │    │            │     	with 3 stored elements and shape (3, 1)>
    │    │              │    │            └ <function ClassTfidfTransformer.fit at 0x1596ede40>
    │    │              │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    │    │              └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
    │    └ ClassTfidfTransformer(reduce_frequent_words=True)
    └ <bertopic._bertopic.BERTopic object at 0xc58d3eff0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/vectorizers/_ctfidf.py", line 88, in fit
    self._idf_diag = sp.diags(
    │    │           │  └ <function diags at 0x115019c60>
    │    │           └ <module 'scipy.sparse' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sc...
    │    └ <Compressed Sparse Row sparse matrix of dtype 'float64'
    │      	with 187 stored elements and shape (187, 187)>
    └ ClassTfidfTransformer(reduce_frequent_words=True)
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 543, in diags
    A = diags_array(diagonals, offsets=offsets, shape=shape, dtype=dtype)
        │           │                  │              │            └ <class 'numpy.float64'>
        │           │                  │              └ (1, 1)
        │           │                  └ 0
        │           └ np.float64(0.22314355131420976)
        └ <function diags_array at 0x115019bc0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/scipy/sparse/_construct.py", line 367, in diags_array
    if len(diagonals) == 0 or isscalarlike(diagonals[0]):
           │                  │            └ np.float64(0.22314355131420976)
           │                  └ <function isscalarlike at 0x114f4a660>
           └ np.float64(0.22314355131420976)

TypeError: object of type 'numpy.float64' has no len()

2026-06-08 16:15:57.787 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 42/53...

2026-06-08 16:15:57.790 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-07-28 00:00:00

2026-06-08 16:15:57.790 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1048

2026-06-08 16:15:57.791 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:15:57.791 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:15:57.791 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:15:57.791 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:15:59.551 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:15:59.553 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:15:59,553 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:15:59.980 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:15:59.980 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:15:59.988 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-06-30 00:00:00 and 2024-07-28 00:00:00

2026-06-08 16:16:00.011 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-07-28 00:00:00 merged successfully with others

2026-06-08 16:16:00.012 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-07-28 00:00:00...

2026-06-08 16:16:00.022 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-07-28 00:00:00

2026-06-08 16:16:00.022 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 43/53...

2026-06-08 16:16:00.024 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-08-11 00:00:00

2026-06-08 16:16:00.024 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 853

2026-06-08 16:16:00.024 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:00.025 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:00.025 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:00.026 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:01.393 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:01.395 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:01,395 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:01.751 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:01.752 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:01.757 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-07-28 00:00:00 and 2024-08-11 00:00:00

2026-06-08 16:16:01.766 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-08-11 00:00:00 merged successfully with others

2026-06-08 16:16:01.766 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-08-11 00:00:00...

2026-06-08 16:16:01.768 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-08-11 00:00:00

2026-06-08 16:16:01.768 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 44/53...

2026-06-08 16:16:01.769 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-08-25 00:00:00

2026-06-08 16:16:01.769 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 872

2026-06-08 16:16:01.769 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:01.769 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:01.770 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:01.770 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:03.163 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:03.165 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:03,166 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:03.921 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:03.921 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:03.926 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-08-11 00:00:00 and 2024-08-25 00:00:00

2026-06-08 16:16:03.936 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-08-25 00:00:00 merged successfully with others

2026-06-08 16:16:03.936 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-08-25 00:00:00...

2026-06-08 16:16:03.938 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-08-25 00:00:00

2026-06-08 16:16:03.938 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 45/53...

2026-06-08 16:16:03.939 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-09-08 00:00:00

2026-06-08 16:16:03.939 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 940

2026-06-08 16:16:03.939 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:03.939 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:03.940 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:03.940 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:05.341 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:05.343 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:05,343 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:05.658 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:05.659 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:05.664 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-08-25 00:00:00 and 2024-09-08 00:00:00

2026-06-08 16:16:05.672 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-09-08 00:00:00 merged successfully with others

2026-06-08 16:16:05.672 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-09-08 00:00:00...

2026-06-08 16:16:05.674 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-09-08 00:00:00

2026-06-08 16:16:05.674 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 46/53...

2026-06-08 16:16:05.675 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-09-22 00:00:00

2026-06-08 16:16:05.675 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 911

2026-06-08 16:16:05.675 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:05.675 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:05.676 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:05.676 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:07.045 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:07.047 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:07,047 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:07.381 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:07.381 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:07.386 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-09-08 00:00:00 and 2024-09-22 00:00:00

2026-06-08 16:16:07.395 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-09-22 00:00:00 merged successfully with others

2026-06-08 16:16:07.395 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-09-22 00:00:00...

2026-06-08 16:16:07.397 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-09-22 00:00:00

2026-06-08 16:16:07.397 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 47/53...

2026-06-08 16:16:07.398 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-10-06 00:00:00

2026-06-08 16:16:07.398 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 918

2026-06-08 16:16:07.398 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:07.398 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:07.398 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:07.399 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:08.825 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:08.828 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:08,828 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:09.199 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:09.199 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:09.204 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-09-22 00:00:00 and 2024-10-06 00:00:00

2026-06-08 16:16:09.213 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-10-06 00:00:00 merged successfully with others

2026-06-08 16:16:09.213 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-10-06 00:00:00...

2026-06-08 16:16:09.215 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-10-06 00:00:00

2026-06-08 16:16:09.215 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 48/53...

2026-06-08 16:16:09.216 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-10-20 00:00:00

2026-06-08 16:16:09.216 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1027

2026-06-08 16:16:09.217 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:09.217 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:09.217 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:09.217 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:10.811 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:10.813 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:10,813 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:11.175 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:11.176 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:11.181 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-10-06 00:00:00 and 2024-10-20 00:00:00

2026-06-08 16:16:11.190 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-10-20 00:00:00 merged successfully with others

2026-06-08 16:16:11.190 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-10-20 00:00:00...

2026-06-08 16:16:11.193 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-10-20 00:00:00

2026-06-08 16:16:11.193 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 49/53...

2026-06-08 16:16:11.194 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-11-03 00:00:00

2026-06-08 16:16:11.194 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 1023

2026-06-08 16:16:11.194 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:11.194 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:11.195 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:11.195 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:12.869 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:12.871 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:12,871 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:13.396 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:13.396 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:13.401 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-10-20 00:00:00 and 2024-11-03 00:00:00

2026-06-08 16:16:13.412 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-11-03 00:00:00 merged successfully with others

2026-06-08 16:16:13.412 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-11-03 00:00:00...

2026-06-08 16:16:13.414 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-11-03 00:00:00

2026-06-08 16:16:13.415 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 50/53...

2026-06-08 16:16:13.415 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-11-17 00:00:00

2026-06-08 16:16:13.416 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 870

2026-06-08 16:16:13.416 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:13.416 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:13.416 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:13.416 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:14.660 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:14.662 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:14,662 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:14.976 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:14.976 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:14.981 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-11-03 00:00:00 and 2024-11-17 00:00:00

2026-06-08 16:16:14.989 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-11-17 00:00:00 merged successfully with others

2026-06-08 16:16:14.989 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-11-17 00:00:00...

2026-06-08 16:16:14.991 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-11-17 00:00:00

2026-06-08 16:16:14.991 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 51/53...

2026-06-08 16:16:14.992 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-12-01 00:00:00

2026-06-08 16:16:14.992 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 902

2026-06-08 16:16:14.992 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:14.993 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:14.993 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:14.993 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:15.966 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:15.967 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Edison football charges to Division football title over Simi Valley', 'Musiala rescues point for Bayern at Borussi...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.06954661, -0.03167984, -0.02264538, ..., -0.00054191,
                    │           │             │                0.02262317, -0.03057161],
                    │           │             │              [-0.13739589, -0.0...
                    │           │             └ ['Edison football charges to Division football title over Simi Valley', 'Musiala rescues point for Bayern at Borussia Dortmun...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  [HTML] Insider Hist: > % Own BBAI Ultimate Hol...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['[HTML] Insider Hist: > % Own BBAI Ultimate Holdings Sells $26M of BBAI-BigBear.ai Holdings Inc [HTML] Hist: VP Cardenas Fil...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['[HTML] Insider Hist: > % Own BBAI Ultimate Holdings Sells $26M of BBAI-BigBear.ai Holdings Inc [HTML] Hist: VP Cardenas Fi...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:15.971 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2024-12-01 00:00:00: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:15.971 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Edison football charges to Division football title over Simi Valley', 'Musiala rescues point for Bayern at Borussi...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.06954661, -0.03167984, -0.02264538, ..., -0.00054191,
                    │           │             │                0.02262317, -0.03057161],
                    │           │             │              [-0.13739589, -0.0...
                    │           │             └ ['Edison football charges to Division football title over Simi Valley', 'Musiala rescues point for Bayern at Borussia Dortmun...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  [HTML] Insider Hist: > % Own BBAI Ultimate Hol...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ['[HTML] Insider Hist: > % Own BBAI Ultimate Holdings Sells $26M of BBAI-BigBear.ai Holdings Inc [HTML] Hist: VP Cardenas Fil...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5eccfe60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (['[HTML] Insider Hist: > % Own BBAI Ultimate Holdings Sells $26M of BBAI-BigBear.ai Holdings Inc [HTML] Hist: VP Cardenas Fi...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:15.974 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 52/53...

2026-06-08 16:16:15.975 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-12-15 00:00:00

2026-06-08 16:16:15.975 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 675

2026-06-08 16:16:15.975 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:15.975 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:15.975 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:15.975 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:16.935 | DEBUG    | bertrend.BERTopicModel:fit:282 - 	Reducing outliers

2026-06-08 16:16:16.936 | DEBUG    | bertrend.BERTopicModel:fit:289 - 	Updating topics

2026-06-08 16:16:16,937 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

2026-06-08 16:16:17.225 | SUCCESS  | bertrend.BERTopicModel:fit:311 - 	BERTopic model fitted successfully

2026-06-08 16:16:17.225 | DEBUG    | bertrend.BERTrend:_train_by_period:195 - Topic model created successfully

2026-06-08 16:16:17.231 | DEBUG    | bertrend.BERTrend:merge_models_with:360 - Merging topic models for timestamps: 2024-11-17 00:00:00 and 2024-12-15 00:00:00

2026-06-08 16:16:17.238 | SUCCESS  | bertrend.BERTrend:merge_models_with:428 - Models 2024-12-15 00:00:00 merged successfully with others

2026-06-08 16:16:17.238 | INFO     | bertrend.BERTrend:train_topic_models:301 - Saving topic model for period 2024-12-15 00:00:00...

2026-06-08 16:16:17.240 | DEBUG    | bertrend.BERTrend:train_topic_models:311 - Successfully processed period: 2024-12-15 00:00:00

2026-06-08 16:16:17.240 | INFO     | bertrend.BERTrend:train_topic_models:288 - Training topic model 53/53...

2026-06-08 16:16:17.241 | DEBUG    | bertrend.BERTrend:_train_by_period:186 - Processing period: 2024-12-29 00:00:00

2026-06-08 16:16:17.241 | DEBUG    | bertrend.BERTrend:_train_by_period:187 - Number of documents: 106

2026-06-08 16:16:17.241 | DEBUG    | bertrend.BERTrend:_train_by_period:189 - Creating topic model...

2026-06-08 16:16:17.241 | DEBUG    | bertrend.BERTopicModel:fit:263 - 	Initializing BERTopic model

2026-06-08 16:16:17.241 | SUCCESS  | bertrend.BERTopicModel:fit:273 - 	BERTopic model instance created successfully

2026-06-08 16:16:17.242 | DEBUG    | bertrend.BERTopicModel:fit:275 - 	Fitting BERTopic model

2026-06-08 16:16:17.316 | ERROR    | bertrend.BERTopicModel:fit:317 - 	Error in create_topic_model: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:17.316 | ERROR    | bertrend.BERTopicModel:fit:318 - 	Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Latin America outlook as amid fiscal challenges by Julius Baer', 'Broncos’ Nix, Mims conjure fourth-quarter magic ...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.0427274 , -0.00946038,  0.01650982, ..., -0.01607375,
                    │           │             │                0.04644477, -0.01280294],
                    │           │             │              [-0.09704606,  0.0...
                    │           │             └ ['Latin America outlook as amid fiscal challenges by Julius Baer', 'Broncos’ Nix, Mims conjure fourth-quarter magic vs. Benga...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Officers To Get Allowances In Digital Rupee Wa...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ["Officers To Get Allowances In Digital Rupee Wallets? Know All About RBI's Plan RBI to conduct -day Variable Rate Repo (VRR)...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (["Officers To Get Allowances In Digital Rupee Wallets? Know All About RBI's Plan RBI to conduct -day Variable Rate Repo (VRR...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:17.319 | ERROR    | bertrend.BERTrend:train_topic_models:315 - Error processing period 2024-12-29 00:00:00: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:17.319 | ERROR    | bertrend.BERTrend:train_topic_models:316 - Traceback:
Traceback (most recent call last):

  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
           └ <function _run_code at 0x105399da0>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x104919ce0, file "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/s...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-pack...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x10c0c87c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x10c0cb060>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x1048d7e60>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1058ff6a0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10c6f2c60>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1059054e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1058a09a0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x121868370>()>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'ccbe0c7a-345'...33B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'64840024f3cf'...64B)>, <zmq.Frame(b'{"msg_id":"c...
          │    └ <function Kernel.dispatch_shell at 0x10c0491c0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x10bfa9730>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x10c3af880>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'msg_id': 'ccbe0c7a-345d9690d18287e49cf5a592_76213_7', 'msg_type': 'execute_request', 'username': 'federicocinus'...
                                  │       └ [b'ccbe0c7a-345d9690d18287e49cf5a592']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10c6f4b40>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x10c096a70>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x10c07aa20>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('# This is the long step: ~one BERTopic fit per slice. Saved per-period so it is resumable.\nbertrend.train_topic_models(\n ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x10b675f80>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
             └ <function _pseudo_sync_runner at 0x10b660fe0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x1217ecee0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py'
                       │    │             │        └ [<ast.Expr object at 0xc40ec3e90>, <ast.Assign object at 0xc3dc6cf90>, <ast.If object at 0xc3dc6eb50>, <ast.Expr object at 0x...
                       │    │             └ <ast.Module object at 0x13c9975d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x10b676340>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 13e389a30, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...
             │    └ <function InteractiveShell.run_code at 0x10b6763e0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x10b65b010>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         │         │    └ <property object at 0x10b65b0b0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10c6c07d0>
         └ <code object <module> at 0x13dcb1200, file "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", l...

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/132218871.py", line 2, in <module>
    bertrend.train_topic_models(
    │        └ <function BERTrend.train_topic_models at 0x15b5b5120>
    └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

> File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 293, in train_topic_models
    ) = self._train_by_period(
        │    └ <function BERTrend._train_by_period at 0x15b5b5080>
        └ <bertrend.BERTrend.BERTrend object at 0x13e405130>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTrend.py", line 190, in _train_by_period
    topic_model = self.topic_model.fit(
                  │    │           └ <function BERTopicModel.fit at 0xc3dc0dda0>
                  │    └ <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>
                  └ <bertrend.BERTrend.BERTrend object at 0x13e405130>

  File "/var/folders/35/gj9vtpy568v6t175jnf2289c0000gn/T/ipykernel_76214/3836162086.py", line 97, in _fit_with_embedder
    return _orig_fit(*args, **kwargs)
           │          │       └ {'docs': ['Latin America outlook as amid fiscal challenges by Julius Baer', 'Broncos’ Nix, Mims conjure fourth-quarter magic ...
           │          └ ()
           └ <bound method BERTopicModel.fit of <bertrend.BERTopicModel.BERTopicModel object at 0x10c124bf0>>

  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertrend/BERTopicModel.py", line 276, in fit
    topics, probs = topic_model.fit_transform(docs, embeddings)
                    │           │             │     └ array([[-0.0427274 , -0.00946038,  0.01650982, ..., -0.01607375,
                    │           │             │                0.04644477, -0.01280294],
                    │           │             │              [-0.09704606,  0.0...
                    │           │             └ ['Latin America outlook as amid fiscal challenges by Julius Baer', 'Broncos’ Nix, Mims conjure fourth-quarter magic vs. Benga...
                    │           └ <function BERTopic.fit_transform at 0x13b920360>
                    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 520, in fit_transform
    self._extract_topics(
    │    └ <function BERTopic._extract_topics at 0x1596fce00>
    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4204, in _extract_topics
    self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
    │    │                  │    │         └    Topic                                           Document
    │    │                  │    │           0     -1  Officers To Get Allowances In Digital Rupee Wa...
    │    │                  │    │           1    ...
    │    │                  │    └ <function BERTopic._c_tf_idf at 0x1596fd120>
    │    │                  └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
    │    └ None
    └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/bertopic/_bertopic.py", line 4422, in _c_tf_idf
    X = self.vectorizer_model.fit_transform(documents)
        │    │                │             └ ["Officers To Get Allowances In Digital Rupee Wallets? Know All About RBI's Plan RBI to conduct -day Variable Rate Repo (VRR)...
        │    │                └ <function CountVectorizer.fit_transform at 0x11d7e2660>
        │    └ CountVectorizer(min_df=3, ngram_range=(1, 2),
        │                      stop_words=['perhaps', 'them', 'we', 'hers', 'already',
        │             ...
        └ <bertopic._bertopic.BERTopic object at 0xc5eccb1a0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           │          │           │       └ {}
           │          │           └ (["Officers To Get Allowances In Digital Rupee Wallets? Know All About RBI's Plan RBI to conduct -day Variable Rate Repo (VRR...
           │          └ CountVectorizer(min_df=3, ngram_range=(1, 2),
           │                            stop_words=['perhaps', 'them', 'we', 'hers', 'already',
           │                   ...
           └ <function CountVectorizer.fit_transform at 0x11d7e25c0>
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1399, in fit_transform
    X = self._limit_features(
        │    └ <function CountVectorizer._limit_features at 0x11d7e2340>
        └ CountVectorizer(min_df=3, ngram_range=(1, 2),
                          stop_words=['perhaps', 'them', 'we', 'hers', 'already',
                 ...
  File "/Users/federicocinus/Progetti - Local/ThematicTrading/code/.venv/lib/python3.12/site-packages/sklearn/feature_extraction/text.py", line 1251, in _limit_features
    raise ValueError(

ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.

2026-06-08 16:16:17.321 | ERROR    | bertrend.BERTrend:train_topic_models:323 - Training completed with failures for 8 periods: [Timestamp('2023-04-09 00:00:00'), Timestamp('2023-08-27 00:00:00'), Timestamp('2023-10-22 00:00:00'), Timestamp('2023-11-05 00:00:00'), Timestamp('2023-12-31 00:00:00'), Timestamp('2024-07-14 00:00:00'), Timestamp('2024-12-01 00:00:00'), Timestamp('2024-12-29 00:00:00')]

2026-06-08 16:16:17.322 | WARNING  | bertrend.BERTrend:train_topic_models:327 - Successfully trained topic models for 45 periods: [Timestamp('2023-01-01 00:00:00'), Timestamp('2023-01-15 00:00:00'), Timestamp('2023-01-29 00:00:00'), Timestamp('2023-02-12 00:00:00'), Timestamp('2023-02-26 00:00:00'), Timestamp('2023-03-12 00:00:00'), Timestamp('2023-03-26 00:00:00'), Timestamp('2023-04-23 00:00:00'), Timestamp('2023-05-07 00:00:00'), Timestamp('2023-05-21 00:00:00'), Timestamp('2023-06-04 00:00:00'), Timestamp('2023-06-18 00:00:00'), Timestamp('2023-07-02 00:00:00'), Timestamp('2023-07-16 00:00:00'), Timestamp('2023-07-30 00:00:00'), Timestamp('2023-08-13 00:00:00'), Timestamp('2023-09-10 00:00:00'), Timestamp('2023-09-24 00:00:00'), Timestamp('2023-10-08 00:00:00'), Timestamp('2023-11-19 00:00:00'), Timestamp('2023-12-03 00:00:00'), Timestamp('2023-12-17 00:00:00'), Timestamp('2024-01-14 00:00:00'), Timestamp('2024-01-28 00:00:00'), Timestamp('2024-02-11 00:00:00'), Timestamp('2024-02-25 00:00:00'), Timestamp('2024-03-10 00:00:00'), Timestamp('2024-03-24 00:00:00'), Timestamp('2024-04-07 00:00:00'), Timestamp('2024-04-21 00:00:00'), Timestamp('2024-05-05 00:00:00'), Timestamp('2024-05-19 00:00:00'), Timestamp('2024-06-02 00:00:00'), Timestamp('2024-06-16 00:00:00'), Timestamp('2024-06-30 00:00:00'), Timestamp('2024-07-28 00:00:00'), Timestamp('2024-08-11 00:00:00'), Timestamp('2024-08-25 00:00:00'), Timestamp('2024-09-08 00:00:00'), Timestamp('2024-09-22 00:00:00'), Timestamp('2024-10-06 00:00:00'), Timestamp('2024-10-20 00:00:00'), Timestamp('2024-11-03 00:00:00'), Timestamp('2024-11-17 00:00:00'), Timestamp('2024-12-15 00:00:00')]

2026-06-08 16:16:17.523 | INFO     | bertrend.BERTrend:save_model:753 - BERTrend model saved to: /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_models

Trained periods:  45
Merged themes:    18

## 5. Theme-intensity time series + **rate**  ← *the Stage-1 deliverable*

`calculate_signal_popularity` gives a per-theme popularity that **accumulates** while a theme keeps receiving docs (and decays when quiet). For the lead–lag test we also need a *rate* that peaks and falls, so we add:

- `intensity_rate` — first difference of popularity per theme (Δ popularity per slice),
- `new_docs` — non-cumulative docs per slice (Δ of BERTrend's cumulative `Docs_Count`).

The `new_docs` curve is the cleanest "attention pulse" for aligning against ETF price/volume peaks.

In [7]:
bertrend.calculate_signal_popularity()

# theme -> short keyword label from the merged topic representation
rep_map = {}
if bertrend.merged_df is not None:
    for _, r in bertrend.merged_df.iterrows():
        rep = r.get("Representation")
        rep_map[r["Topic"]] = ", ".join(rep[:5]) if isinstance(rep, (list, tuple)) else str(rep)


def theme_label(tid: int) -> str:
    return f"{tid}: {rep_map.get(tid, '')}"


rows = []
for tid, data in bertrend.topic_sizes.items():
    ts_list = data.get("Timestamps", [])
    pops = data.get("Popularity", [])
    docs_cum = data.get("Docs_Count", [0] * len(ts_list))
    for ts, pop, dc in zip(ts_list, pops, docs_cum):
        rows.append({
            "theme_id": tid, "timestamp": pd.Timestamp(ts),
            "intensity": float(pop), "docs_cum": float(dc), "label": theme_label(tid),
        })

intensity = pd.DataFrame(rows).sort_values(["theme_id", "timestamp"]).reset_index(drop=True)
g = intensity.groupby("theme_id")
intensity["intensity_rate"] = g["intensity"].diff().fillna(intensity["intensity"])
intensity["new_docs"] = g["docs_cum"].diff().fillna(intensity["docs_cum"]).clip(lower=0)

print(f"Themes tracked: {intensity['theme_id'].nunique()}   rows: {len(intensity)}")
intensity.head()

Themes tracked: 16   rows: 650

,theme_id,timestamp,intensity,docs_cum,label,intensity_rate,new_docs
0,0,2023-01-01,141.0,141.0,"0: partners, reach, japan, partner, american",141.0,141.0
1,0,2023-01-15,200.0,200.0,"0: partners, reach, japan, partner, american",59.0,59.0
2,0,2023-01-15,242.0,242.0,"0: partners, reach, japan, partner, american",42.0,42.0
3,0,2023-01-15,286.0,286.0,"0: partners, reach, japan, partner, american",44.0,44.0
4,0,2023-01-29,429.0,429.0,"0: partners, reach, japan, partner, american",143.0,143.0

In [8]:
# Cumulative intensity (top) vs per-slice attention pulse (bottom) for the top themes.
TOP_THEMES = 12
top_ids = (
    intensity.groupby("theme_id")["intensity"].max().sort_values(ascending=False).head(TOP_THEMES).index
)
plot_df = intensity[intensity["theme_id"].isin(top_ids)]

fig_int = px.line(
    plot_df, x="timestamp", y="intensity", color="label", markers=True,
    title=f"Cumulative theme-intensity — top {TOP_THEMES} themes ({TAG})",
)
fig_int.update_layout(legend_title_text="theme", height=520)
fig_int.write_html(OUTPUT_DIR / f"bertrend_intensity_{TAG}.html")
fig_int.show()

fig_rate = px.line(
    plot_df, x="timestamp", y="new_docs", color="label", markers=True,
    title=f"Attention pulse (new docs / slice) — top {TOP_THEMES} themes ({TAG})",
)
fig_rate.update_layout(legend_title_text="theme", height=520)
fig_rate.write_html(OUTPUT_DIR / f"bertrend_intensity_rate_{TAG}.html")
fig_rate.show()

## 6. Signal classification at the latest date

For `current_date`, BERTrend computes the P10/P50 popularity percentiles over the trailing `WINDOW_SIZE` days and buckets each theme into **noise / weak / strong**. Weak signals (emerging, rising) are the ones we care about for "before it's priced in".

In [9]:
current_date = max(bertrend.doc_groups.keys())
noise_df, weak_df, strong_df = bertrend.classify_signals(WINDOW_SIZE, current_date)

print(f"As of {pd.Timestamp(current_date).date()}  (window = {WINDOW_SIZE}d)")
print(f"  noise:  {len(noise_df)}")
print(f"  weak:   {len(weak_df)}   <- emerging themes")
print(f"  strong: {len(strong_df)}")

cols = [c for c in ["Topic", "Representation", "Latest_Popularity", "Docs_Count", "Sources"]
        if weak_df is not None and c in weak_df.columns]
if weak_df is not None and not weak_df.empty:
    display(weak_df[cols].head(10))
else:
    print("No weak signals at this date — try a different current_date or window.")

As of 2024-12-15  (window = 28d)
  noise:  8
  weak:   5   <- emerging themes
  strong: 3

,Topic,Representation,Latest_Popularity,Docs_Count,Sources
0,3,pharma_fda_drug_health_deal_insider_public_app...,3174.745603,3211,"{DBF, VOX, TIF, TIL, STS, SLE, OPA, PDA, FM5, ..."
1,7,news_nasa_march_expected_watch_night_public_mi...,1650.347842,1878,"{DBF, VOX, TIL, SLE, PDA, FM5, NS1, CO1, DML, ..."
2,8,company_share_bank_ipo_insider_tiktok_public_s...,4180.373388,4211,"{DBF, VRG, TIL, HUR, STS, PDA, FM5, NS1, CO1, ..."
3,11,growth_market_india_industry_energy_sales_cror...,1100.531024,1764,"{HUR, TIL, GBI, STS, OPA, PDA, FM5, NS1, CO1, ..."
4,15,christmas_buy_watch_free_sale_online_starbucks...,153.872366,313,"{FEX, TIL, TOI, BGL, STS, GO5, NS7, NS3, TGI, ..."

## 7. Map themes → ICB sectors **and** tickers

Two complementary mappings, since the H1 run showed the ICB-cosine map was unreliable (max cosine ≈ 0.5, AI→Leisure Goods, etc.):

1. **ICB cosine** — theme centroid vs the 45 ICB Sector centroids. We **calibrate** the `aligned` threshold from the empirical cosine distribution (75th percentile) instead of a hardcoded 0.30, and keep `sector_cos` as an explicit confidence score.
2. **Tickers** — aggregate the `DerivedTickersId` of each theme's member headlines. This is grounded in the data (not in ICB definitions) and is the more trustworthy bridge to Stage 3 exposure.

In [10]:
icb_raw = pd.read_excel(ICB_PATH, sheet_name="Mappable", header=1).dropna(subset=["Subsector"])
icb = pd.DataFrame({
    "industry": icb_raw["Industry"].str.strip(),
    "sector": icb_raw["Sector"].str.strip(),
    "subsector": icb_raw["Subsector"].str.strip(),
    "definition": icb_raw["Definition"].fillna("").str.strip(),
}).reset_index(drop=True)

sub_emb = embedder.encode(
    (icb["subsector"] + ". " + icb["definition"]).tolist(),
    batch_size=32, show_progress_bar=False, convert_to_numpy=True, normalize_embeddings=True,
)
sector_meta = (
    icb.groupby("sector", as_index=False).agg(industry=("industry", "first"))
    .sort_values(["industry", "sector"]).reset_index(drop=True)
)
sector_emb = np.stack([sub_emb[(icb["sector"] == s).to_numpy()].mean(axis=0) for s in sector_meta["sector"]])
sector_emb /= np.linalg.norm(sector_emb, axis=1, keepdims=True)
print(f"Sector centroids: {sector_emb.shape}")

Sector centroids: (45, 768)

In [11]:
# --- ticker aggregation per theme (grounded in DerivedTickersId) ---
text2tick = dict(zip(df[TEXT_COLUMN], df["DerivedTickersId"]))


def _flatten_docs(documents) -> list[str]:
    """merged_df['Documents'] mixes flat strings and (timestamp, [docs]) tuples — flatten both."""
    out = []
    if not isinstance(documents, (list, tuple)):
        return out
    for item in documents:
        if isinstance(item, str):
            out.append(item)
        elif isinstance(item, tuple) and len(item) == 2 and isinstance(item[1], list):
            out.extend([t for t in item[1] if isinstance(t, str)])
        elif isinstance(item, list):
            out.extend([t for t in item if isinstance(t, str)])
    return out


def top_tickers(documents, k: int = 6) -> str:
    cnt = Counter()
    for t in _flatten_docs(documents):
        raw = text2tick.get(t, "")
        if isinstance(raw, str) and raw:
            for tk in raw.split(";"):
                tk = tk.strip()
                if tk:
                    cnt[tk] += 1
    return ", ".join(f"{tk}({c})" for tk, c in cnt.most_common(k))


docs_by_theme = dict(zip(bertrend.merged_df["Topic"], bertrend.merged_df["Documents"]))


def exemplar_headline(tid: int) -> str:
    """Pick the real headline that best represents a theme: the one overlapping the most
    theme keywords (ties broken toward shorter, punchier headlines). Far more legible than
    a bag of c-TF-IDF words."""
    kws = [w.strip().lower() for w in rep_map.get(tid, "").split(",") if w.strip()]
    docs = _flatten_docs(docs_by_theme.get(tid, []))
    if not docs:
        return ""
    best = max(docs, key=lambda h: (sum(kw in h.lower() for kw in kws), -len(h)))
    return best.strip()


# --- ICB cosine map (calibrated threshold) ---
theme_emb = np.stack(bertrend.merged_df["Embedding"].to_numpy())
theme_emb = theme_emb / (np.linalg.norm(theme_emb, axis=1, keepdims=True) + 1e-12)
sim = theme_emb @ sector_emb.T
nearest = sim.argmax(axis=1)
max_cos = sim.max(axis=1)

TAU_COV = float(np.round(np.percentile(max_cos, 75), 3))      # calibrated, not hardcoded
peak = intensity.groupby("theme_id")["intensity"].max()
peak_rate = intensity.groupby("theme_id")["new_docs"].max()

theme_ids = bertrend.merged_df["Topic"].to_numpy()
themes = pd.DataFrame({
    "theme_id": theme_ids,
    "keywords": [rep_map.get(t, "") for t in theme_ids],
    "sector_cos": np.round(max_cos, 3),
    "nearest_sector": sector_meta["sector"].to_numpy()[nearest],
    "nearest_industry": sector_meta["industry"].to_numpy()[nearest],
    "top_tickers": [top_tickers(docs_by_theme.get(t, [])) for t in theme_ids],
    "exemplar": [exemplar_headline(t) for t in theme_ids],
})
themes["description"] = themes.apply(
    lambda r: f'{r["keywords"]} — e.g. "{r["exemplar"]}"' if r["exemplar"] else r["keywords"],
    axis=1,
)
themes["sector_conf"] = np.where(themes["sector_cos"] >= TAU_COV, "aligned", "novel")
themes["peak_intensity"] = themes["theme_id"].map(peak).fillna(0.0)
themes["peak_new_docs"] = themes["theme_id"].map(peak_rate).fillna(0.0)
themes = themes.sort_values("peak_intensity", ascending=False).reset_index(drop=True)

tick_cov = (themes["top_tickers"].str.len() > 0).mean()
print(f"Calibrated TAU_COV (P75 of cosine): {TAU_COV}")
print(f"aligned: {(themes['sector_conf'] == 'aligned').sum()}   novel: {(themes['sector_conf'] == 'novel').sum()}")
print(f"themes with >=1 ticker: {tick_cov:.0%}")
themes.head(15)

Calibrated TAU_COV (P75 of cosine): 0.4259999990463257
aligned: 5   novel: 13
themes with >=1 ticker: 100%

,theme_id,keywords,sector_cos,nearest_sector,nearest_industry,top_tickers,exemplar,description,sector_conf,peak_intensity,peak_new_docs
0,2,"price target, price, ahead, downgrades, prices",0.336,"Gas, Water and Multi-utilities",Utilities,"%USD(323), %XBT(279), %JPY(278), %EUR(209), 83...",Analyst Downgrades Lucid Gr NASDAQLCID with Lo...,"price target, price, ahead, downgrades, prices...",novel,6533.000000,231.0
1,0,"partners, reach, japan, partner, american",0.427,"Gas, Water and Multi-utilities",Utilities,"3400398Z(172), AAPL(107), 0629846DBB(104), MSF...",Elys Game Technology partners with U.S. Integr...,"partners, reach, japan, partner, american — e....",aligned,6069.000000,278.0
2,1,"hydrogen, meeting, public, hong kong, conference",0.424,"Gas, Water and Multi-utilities",Utilities,"9904743Z(135), 0629846DBB(59), ISMEN@TI(53), 3...",Mar Conferences/Seminar Investor Meetings in S...,"hydrogen, meeting, public, hong kong, conferen...",novel,5632.000000,219.0
3,5,"chief, news, key, hotel, newly",0.307,Consumer Services,Consumer Discretionary,"AAPL(123), SPOT(84), 1022737D(60), 32663Z(54),...",Meet the chief marketing officers of US News' ...,"chief, news, key, hotel, newly — e.g. ""Meet th...",novel,4279.000000,393.0
4,8,"westpac, icici, billion, capital, exchange",0.466,Finance and Credit Services,Financials,"0235304Z(144), 9904743Z(64), 3400398Z(56), 883...",Westpac to raise $ million in additional Tier ...,"westpac, icici, billion, capital, exchange — e...",aligned,4180.373388,217.0
5,3,"certificate, details, county, act, safe",0.271,Non-life Insurance,Financials,"1000L(157), 1070L(109), 32663Z(75), GOOGL(62),...",Compliances-Reg. ( ) - Details of Loss of Cert...,"certificate, details, county, act, safe — e.g....",novel,3174.745603,191.0
6,4,"cuts, shortage, industry, sales, largest",0.400,Telecommunications Equipment,Telecommunications,"AAPL(342), MSFT(273), GOOGL(210), 1554630D(119...",Kia's Dec. sales rise pct despite chip shortage,"cuts, shortage, industry, sales, largest — e.g...",novel,3136.034950,153.0
7,9,"gop, legislature, senator, storms, state",0.289,"Gas, Water and Multi-utilities",Utilities,"1000L(153), 32663Z(120), AAPL(86), 0141541D(52...",New York state Legislature rejects proposed Ho...,"gop, legislature, senator, storms, state — e.g...",novel,2870.635854,377.0
8,7,"staff, message, warns, issue, fans",0.267,"Gas, Water and Multi-utilities",Utilities,"1022737D(193), 9889440Z(171), 0326786Z(152), A...","Man Utd Issue Update On Takeover, Send Message...","staff, message, warns, issue, fans — e.g. ""Man...",novel,1650.347842,127.0
9,6,"covid, passengers, longer, earlier, health",0.520,"Gas, Water and Multi-utilities",Utilities,"AAPL(59), 3400398Z(51), 0751538DSW(44), 817688...",announcement that the COVID- pandemic is no lo...,"covid, passengers, longer, earlier, health — e...",aligned,1597.621375,149.0
10,11,"china, ban, senate, chinese, staff",0.257,Aerospace and Defense,Industrials,"0629846DBB(114), 13347Z(77), 8243133Z(76), 817...",Pro-pot banking bill sees boost in Senate,"china, ban, senate, chinese, staff — e.g. ""Pro...",novel,1545.248837,149.0
11,16,"second quarter, increased, gains, positive, pe...",0.270,"Gas, Water and Multi-utilities",Utilities,"MSFT(3), AMD(3), ZOMATO@IN(3), BABA(3), ABBN@S...",Resolute reports strong second quarter perform...,"second quarter, increased, gains, positive, pe...",novel,383.875631,104.0
12,14,"flights, air, fuel, accident, health",0.354,"Gas, Water and Multi-utilities",Utilities,"BA(38), 711339Z(24), 29638Z(17), AIR@FP(16), I...",PSO commences aircraft refuelling at Skardu ai...,"flights, air, fuel, accident, health — e.g. ""P...",novel,321.411354,65.0
13,10,"adani enterprises, pakistan, centre, issues, c...",0.248,"Gas, Water and Multi-utilities",Utilities,"ADE@IN(36), 13347Z(29), 8176888Z(22), 0629846D...","Pakistan's deepening politico-economic crisis,...","adani enterprises, pakistan, centre, issues, c...",novel,206.504845,126.0
14,15,"deals, sales, commerce, apple, families",0.494,Household Goods and Home Construction,Consumer Discretionary,"AAPL(29), WBD(9), GOOGL(6), 0417707D(6), SPOT(...",Black Friday Cell Phone Deals : Early Apple iP...,"deals, sales, commerce, apple, families — e.g....",aligned,153.872366,73.0

## 8. Persist (parquet)

In [12]:
intensity_path = OUTPUT_DIR / f"bertrend_intensity_{TAG}.parquet"
themes_path = OUTPUT_DIR / f"bertrend_themes_{TAG}.parquet"
intensity.to_parquet(intensity_path, index=False)
themes.to_parquet(themes_path, index=False)
print(f"Wrote {intensity_path}")
print(f"Wrote {themes_path}")

Wrote /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_intensity_2023_2024.parquet
Wrote /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_themes_2023_2024.parquet

## 9. Native BERTrend dashboards (3 HTML artifacts)

We render three standalone HTML dashboards mirroring the official BERTrend demos. A small helper concatenates Plotly figures + HTML tables into one self-contained page (Plotly JS via CDN, loaded once).

In [13]:
def write_dashboard(path: Path, title: str, blocks: list[tuple[str, object]]):
    """blocks: list of ('fig', go.Figure) | ('html', str) | ('h2', str) | ('p', str)."""
    parts, first_fig = [], True
    for kind, obj in blocks:
        if kind == "fig":
            parts.append(obj.to_html(full_html=False, include_plotlyjs="cdn" if first_fig else False))
            first_fig = False
        elif kind == "h2":
            parts.append(f"<h2>{obj}</h2>")
        elif kind == "p":
            parts.append(f"<p class='note'>{obj}</p>")
        elif kind == "html":
            parts.append(str(obj))
    style = (
        "body{font-family:-apple-system,Segoe UI,Arial,sans-serif;margin:0;padding:24px;"
        "background:#f4f6f9;color:#222} h1{color:#1f3a5f} h2{color:#2980b9;"
        "border-bottom:2px solid #d6e0ea;padding-bottom:6px;margin-top:32px}"
        ".note{color:#555;font-size:14px} .card{background:#fff;border-radius:8px;padding:18px;"
        "margin:14px 0;box-shadow:0 1px 3px rgba(0,0,0,.08)} table{border-collapse:collapse;"
        "font-size:13px;width:100%} th,td{border:1px solid #e2e8f0;padding:6px 8px;text-align:left}"
        "th{background:#eef3f8}"
    )
    html = (
        f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>{title}</title>"
        f"<style>{style}</style></head><body><h1>{title}</h1>"
        + "<div class='card'>" + "</div><div class='card'>".join(parts) + "</div>"
        + "</body></html>"
    )
    Path(path).write_text(html)
    print(f"Wrote {path}")

### 9a. `topic_analysis` — per-slice topic exploration

Mirrors [`demos/topic_analysis`](https://github.com/rte-france/BERTrend/tree/main/bertrend/demos/topic_analysis): number of topics per slice, outlier size per slice, and the talked-about topics per news source for the latest slice.

In [14]:
from bertrend.trend_analysis.visualizations import (
    plot_num_topics,
    plot_size_outliers,
    plot_topics_for_model,
)

topic_models = bertrend.restore_topic_models(MODELS_DIR)        # dict[ts, BERTopic] (with doc_info_df)
latest_ts = max(topic_models)
latest_model = topic_models[latest_ts]

fig_ntopics = plot_num_topics(topic_models)
fig_outliers = plot_size_outliers(topic_models)
fig_src = plot_topics_for_model(latest_model)

write_dashboard(
    OUTPUT_DIR / f"bertrend_topic_analysis_{TAG}.html",
    f"BERTrend · Topic Analysis ({TAG})",
    [
        ("p", f"Per-slice topic models: {len(topic_models)} periods. Latest slice: {pd.Timestamp(latest_ts).date()}."),
        ("h2", "Number of topics detected per slice"), ("fig", fig_ntopics),
        ("h2", "Outlier (-1) size per slice"), ("fig", fig_outliers),
        ("h2", f"Topics per source — slice {pd.Timestamp(latest_ts).date()}"), ("fig", fig_src),
    ],
)
fig_ntopics.show()

2026-06-08 16:16:18,259 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,260 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,261 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,263 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,264 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,265 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,266 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,267 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,269 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,270 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,271 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,272 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,273 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,274 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,275 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,276 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,278 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,279 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,280 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,281 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,282 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,283 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,284 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,285 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,286 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,287 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,288 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,289 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,290 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,291 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,292 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,293 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,294 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,295 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,296 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,297 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,298 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,299 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,300 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,301 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,302 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,303 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,304 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,305 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-06-08 16:16:18,306 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

Wrote /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_topic_analysis_2023_2024.html

### 9b. `weak_signals` — signal evolution + merge Sankey + emergence

Mirrors [`demos/weak_signals`](https://github.com/rte-france/BERTrend/tree/main/bertrend/demos/weak_signals): the popularity-evolution plot with **noise / weak / strong** shaded bands (log y-axis), the **merge Sankey** (continuation / birth across slices), and the **newly emerged** themes per timestamp.

In [15]:
from bertrend.trend_analysis.visualizations import (
    create_topic_size_evolution_figure,
    create_sankey_diagram_plotly,
    plot_newly_emerged_topics,
)

# Signal thresholds for the trailing window (P10 / P90 of popularity).
window_start, window_end, all_pop, q1, q3 = bertrend._compute_popularity_values_and_thresholds(
    WINDOW_SIZE, current_date
)


def signal_evolution_figure(q1: float, q3: float, current_date, top_n: int = 15):
    """Robust replacement for BERTrend's plot_topic_size_evolution.

    BERTrend's helper puts the y-axis on a log scale with range [0, y_max] — but Plotly
    expects log-axis ranges in log10 units, so [0, …] renders as 'NaN×10^Infinity' and the
    curves disappear. Here we keep a linear y-axis, show the full timeline, and shade the
    noise / weak / strong regions from the window thresholds.
    """
    top = (
        intensity.groupby("theme_id")["intensity"].max()
        .sort_values(ascending=False).head(top_n).index
    )
    d = intensity[intensity["theme_id"].isin(top)]
    y_max = max(float(d["intensity"].max()), float(q3), 1.0)

    fig = px.line(d, x="timestamp", y="intensity", color="label", markers=True)
    # signal-region bands
    fig.add_hrect(y0=0, y1=q1, fillcolor="rgba(128,128,128,0.12)", line_width=0,
                  annotation_text="noise", annotation_position="top left")
    fig.add_hrect(y0=q1, y1=q3, fillcolor="rgba(255,165,0,0.14)", line_width=0,
                  annotation_text="weak signal", annotation_position="top left")
    fig.add_hrect(y0=q3, y1=y_max * 1.1, fillcolor="rgba(0,200,0,0.12)", line_width=0,
                  annotation_text="strong signal", annotation_position="top left")
    # Plotly's add_vline does integer arithmetic on datetime x (buggy with pandas
    # Timestamps), so pass the x as epoch-milliseconds, which date axes use internally.
    cd_ms = pd.Timestamp(current_date).value // 10**6
    fig.add_vline(x=cd_ms, line_width=2, line_dash="dash", line_color="red",
                  annotation_text="current date", annotation_position="top")
    fig.update_layout(
        title="Lifetime cumulative popularity (BERTrend signal metric)",
        xaxis_title="Timestamp", yaxis_title="Popularity (cumulative doc count)",
        legend_title_text="theme", height=600,
    )
    return fig


def attention_pulse_figure(current_date, top_n: int = 15, smooth: int = 3):
    """The thematic-trading view: new documents per slice (a *flow*, not a stock).

    Unlike cumulative popularity this rises AND falls, so its peak can be lead-lag tested
    against the cohort's price/flow peaks (roadmap Stage 1 gate)."""
    top = (
        intensity.groupby("theme_id")["new_docs"].max()
        .sort_values(ascending=False).head(top_n).index
    )
    d = intensity[intensity["theme_id"].isin(top)].copy()
    d["pulse"] = (
        d.groupby("theme_id")["new_docs"]
        .transform(lambda s: s.rolling(smooth, min_periods=1, center=True).mean())
    )
    fig = px.line(d, x="timestamp", y="pulse", color="label", markers=True)
    cd_ms = pd.Timestamp(current_date).value // 10**6
    fig.add_vline(x=cd_ms, line_width=2, line_dash="dash", line_color="red",
                  annotation_text="current date", annotation_position="top")
    fig.update_layout(
        title=f"Attention pulse — new docs / slice ({smooth}-slice smoothed)",
        xaxis_title="Timestamp", yaxis_title="New documents per slice",
        legend_title_text="theme", height=600,
    )
    return fig


fig_pulse_main = attention_pulse_figure(current_date)
fig_evo = signal_evolution_figure(q1, q3, current_date)

# Merge Sankey (topic continuation / birth)
fig_sankey = create_sankey_diagram_plotly(bertrend.all_merge_histories_df)

# Newly emerged themes per timestamp
fig_births = (
    plot_newly_emerged_topics(bertrend.all_new_topics_df)
    if bertrend.all_new_topics_df is not None and not bertrend.all_new_topics_df.empty
    else go.Figure()
)

write_dashboard(
    OUTPUT_DIR / f"bertrend_weak_signals_{TAG}.html",
    f"BERTrend · Weak Signals ({TAG})",
    [
        ("p", f"As of {pd.Timestamp(current_date).date()} (window {WINDOW_SIZE}d). "
              "<b>Attention pulse</b> (new docs/slice) is the trading-relevant series — it "
              "rises and falls, so its peak can be lead-lag tested against price/flows. "
              "<b>Cumulative popularity</b> below is BERTrend's signal metric (a running total "
              "that only grows while a theme stays active, decaying only when it goes silent); "
              f"noise P10={q1:.1f}, strong P90={q3:.1f}."),
        ("h2", "Attention pulse — new docs / slice (trading view)"), ("fig", fig_pulse_main),
        ("h2", "Lifetime cumulative popularity (signal regions)"), ("fig", fig_evo),
        ("h2", "Topic merging — Sankey"), ("fig", fig_sankey),
        ("h2", "Newly emerged themes"), ("fig", fig_births),
    ],
)
fig_pulse_main.show()

Wrote /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_weak_signals_2023_2024.html

### 9c. `prospective_demo` — point-in-time signal dashboard

Mirrors [`bertrend_apps/prospective_demo`](https://github.com/rte-france/BERTrend/tree/main/bertrend/bertrend_apps/prospective_demo): a decision-oriented snapshot at `current_date` — the classified **weak** and **strong** signal tables (with tickers joined from our theme map) plus the attention-pulse chart for the emerging themes.

In [16]:
tick_by_theme = dict(zip(themes["theme_id"], themes["top_tickers"]))
desc_by_theme = dict(zip(themes["theme_id"], themes["description"]))
sector_by_theme = dict(zip(themes["theme_id"], themes["nearest_sector"]))


def _signal_table(sig_df: pd.DataFrame) -> str:
    if sig_df is None or sig_df.empty:
        return "<p class='note'>none at this date</p>"
    keep = [c for c in ["Topic", "Latest_Popularity", "Docs_Count"] if c in sig_df.columns]
    t = sig_df[keep].copy()
    t.insert(1, "theme", t["Topic"].map(desc_by_theme).fillna(""))
    t["sector"] = t["Topic"].map(sector_by_theme).fillna("")
    t["tickers"] = t["Topic"].map(tick_by_theme).fillna("")
    return t.head(15).to_html(index=False, escape=False)


# attention pulse for the classified weak/strong themes
sig_ids = []
for d in (weak_df, strong_df):
    if d is not None and not d.empty and "Topic" in d.columns:
        sig_ids += d["Topic"].tolist()
pulse_df = intensity[intensity["theme_id"].isin(sig_ids)] if sig_ids else intensity[intensity["theme_id"].isin(top_ids)]
fig_pulse = px.line(
    pulse_df, x="timestamp", y="new_docs", color="label", markers=True,
    title="Attention pulse — classified weak/strong themes",
)
fig_pulse.update_layout(height=480, legend_title_text="theme")

write_dashboard(
    OUTPUT_DIR / f"bertrend_prospective_{TAG}.html",
    f"BERTrend · Prospective Dashboard ({TAG})",
    [
        ("p", f"Point-in-time snapshot as of {pd.Timestamp(current_date).date()} "
              f"(window {WINDOW_SIZE}d). Strong = established, Weak = emerging."),
        ("h2", f"Strong signals ({0 if strong_df is None else len(strong_df)})"),
        ("html", _signal_table(strong_df)),
        ("h2", f"Weak signals ({0 if weak_df is None else len(weak_df)})  ← emerging"),
        ("html", _signal_table(weak_df)),
        ("h2", "Attention pulse"), ("fig", fig_pulse),
    ],
)
fig_pulse.show()

Wrote /Users/federicocinus/Progetti - Local/ThematicTrading/code/notebooks/output/bertrend_prospective_2023_2024.html

## Next steps (Stage-1 gate)

- **Lead–lag test:** align each theme's **`new_docs` pulse** with the matching ETF cohort (e.g. Clean Energy = ICLN/TAN/QCLN…) and check the ordering `news-pulse → PX_LAST → PX_VOLUME / FUND_FLOW`. The lag is the edge.
- **Use the ticker map** (`themes.top_tickers`) as the candidate universe for Stage 3 exposure — more trustworthy than the ICB cosine here.
- **Tune merging:** sweep `MIN_SIMILARITY` and `GRANULARITY_DAYS` (try 7d); inspect the merge Sankey for over-merging.
- **Lifecycle labels:** derive birth / growth / peak / decay from the `new_docs` curve + signal class.

**Artifacts written to `notebooks/output/`:** `bertrend_intensity_{TAG}.html`, `bertrend_intensity_rate_{TAG}.html`, `bertrend_topic_analysis_{TAG}.html`, `bertrend_weak_signals_{TAG}.html`, `bertrend_prospective_{TAG}.html`, plus the two parquet files.