# 0.42 — PIT vs DatedGPT vs GPT: relations, and leakage from the future

Two questions, nothing else.

1. **On 100 random 2024 headlines, how well do PIT, DatedGPT and GPT find relations?**
   Precision, recall, specificity.
2. **On headlines built to tempt a model with its knowledge of the future, does GPT expose
   relations that did not exist yet?**

**No leakage anywhere.** A headline dated D is read only by models whose training data ends
before D: DatedGPT-2023 and PIT-4B-2023 *base* for 2024 headlines (the code derives the vintage
from the date — it cannot be asked for a later one), spaCy `trf` for names (its newest text is
from 2019), and gpt-4o, whose knowledge stops in October 2023. The *base* models, not the
instruction-tuned ones: an audit of the model cards and papers found PIT-4B-FT tuned on
instruction data written by 2023–24 models, which makes it leaky.

**No hand-written rules.** spaCy gives the names; the model chooses the whole relation in two
steps by scoring, never generating — first *which* relation the headline asserts (six predicates
or none), then *who does it to whom* among the names found. No noise filter, no trigger lexicon,
no word-order rule. GPT gets the same written guideline the gold annotators followed.

**The answer, in two lines.** Without hand-written rules, the point-in-time models cannot extract
relations — F1 under 30 %; gpt-4o, given the annotators' guideline, reaches F1 94 % on 2024
headlines where it cannot cheat, with three genuine errors (two countries taken as companies, one
wrong buyer). On old headlines built to
tempt it, GPT did **not** expose a single relation from the future; what leaked was the *name*
of the company (Facebook → Meta Platforms, Square → Block) and its later ticker — and only when
it was not told the headline's date.

In [1]:
import sys, json, warnings
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path.cwd().parent / "scripts"))
warnings.filterwarnings("ignore")
pd.set_option("display.max_colwidth", 80, "display.width", 200)

import pit_extract as P, gpt_extract as G, eval_042 as E
P.LOCAL_ONLY = True                     # never download inside the notebook

GOLD = Path.cwd() / "gold"
DATA = json.loads((GOLD / "test_2024.json").read_text())
TEST = [x for x in DATA if x["split"] == "test"]
PROBES = json.loads((GOLD / "probes_leakage.json").read_text())
print(f"test headlines {len(TEST)} · with a relation {sum(x['relation']['predicate'] != 'none' for x in TEST)} · traps {len(PROBES)}")

test headlines 100 · with a relation 30 · traps 30

## The prompts

Exactly what each model receives, printed by the same code that sends it — on one example
headline from the dev split.

**Dated models (DatedGPT, PIT).** Nothing is generated. The prompt is ten worked examples and the
headline, and the model *scores* each option as a continuation; the highest wins. Step 1 scores
the seven relations; if it is not `none`, step 2 scores every ordered pair of the names spaCy found.

In [2]:
# a dev headline with a relation and at least two names, so both steps are visible
EXAMPLE = next(x for x in DATA if x["split"] == "dev" and x["relation"]["predicate"] != "none"
               and len(P.entities(x["headline"], x["date"], "spacy-trf", "asis")) >= 2)
h, d = EXAMPLE["headline"], EXAMPLE["date"]
ents = P.entities(h, d, "spacy-trf", "asis")

step1 = f"{P.RULE_FREE_SHOTS}Headline: {h}\nRelation:"
print("═════ STEP 1 — prompt ═════")
print(step1)
print("\n═════ STEP 1 — options scored as continuations ═════")
print("  " + " | ".join(P.RELATIONS))
print(f"\n═════ STEP 2 — appended after the chosen relation (here the gold one, '{EXAMPLE['relation']['predicate']}') ═════")
print(f" {EXAMPLE['relation']['predicate']}\nSubject:")
print("\n═════ STEP 2 — options: every ordered pair of the names found ═════")
for a in ents:
    for b in ents:
        if a != b:
            print(f"  {a!r} → ' {a}\\nObject: {b}'")

═════ STEP 1 — prompt ═════
Headline: Broadcom to Acquire VMware in $61 Billion Deal
Relation: acquires
Subject: Broadcom
Object: VMware

Headline: Apple Raised to Buy at Citi; PT $210
Relation: none

Headline: Oracle Sues Google Over Use of Java in Android
Relation: sues
Subject: Oracle
Object: Google

Headline: Indonesia Sells IDR2 Trillion of Bonds; Yield 6%
Relation: none

Headline: TSMC to Supply Chips to Tesla Under New Agreement
Relation: supplies
Subject: TSMC
Object: Tesla

Headline: Morgan Stanley Partners Hire New Head of Research
Relation: none

Headline: Temasek Takes 5% Stake in Adyen
Relation: invests in
Subject: Temasek
Object: Adyen

Headline: Pfizer Shares Fall After Earnings Miss Estimates
Relation: none

Headline: Vanguard Cuts Holding in Rivian to 3%
Relation: sells
Subject: Vanguard
Object: Rivian

Headline: Ford and SK On Sign Battery Plant Joint Venture
Relation: partners with
Subject: Ford
Object: SK On

Headline: EQT Begins Deleveraging Process With Equinor Deal (1)
Relation:

═════ STEP 1 — options scored as continuations ═════
  none | acquires | sells | invests in | supplies | partners with | sues

═════ STEP 2 — appended after the chosen relation (here the gold one, 'partners with') ═════
 partners with
Subject:

═════ STEP 2 — options: every ordered pair of the names found ═════
  'EQT' → ' EQT\nObject: Equinor'
  'Equinor' → ' Equinor\nObject: EQT'

**GPT.** One structured call per headline, answered in a fixed JSON schema (entities with
canonical name and ticker; one relation with predicate, subject, object and deal status). Three
versions of the user message: *naive* (headline only), *dated* (headline plus its date and an
instruction to ignore later events) and *guideline* (dated, plus the full annotation guideline the
gold was built from — `gold/guideline.txt`).

In [3]:
for mode in ("naive", "dated", "guideline"):
    msgs = G.messages(h, d, mode)
    print(f"═════ GPT · {mode} ═════")
    for m in msgs:
        text = m["content"]
        if mode == "guideline" and m["role"] == "user":
            rules = (GOLD / "guideline.txt").read_text()
            text = text.replace(rules, f"<the {len(rules.splitlines())}-line guideline in gold/guideline.txt>")
        print(f"[{m['role']}]\n{text}\n")
print("═════ answer schema ═════")
print(json.dumps(G.SCHEMA["schema"], indent=1)[:1200])

═════ GPT · naive ═════
[system]
You extract structured information from financial news headlines.

[user]
Headline: EQT Begins Deleveraging Process With Equinor Deal (1)

Extract from this financial news headline:
1. entities: every organisation or person named in the headline. For each give the text as written, its type (ORG or PERSON), the company's canonical name, and the stock ticker of its primary listing if it is a listed company, otherwise null.
2. relation: at most one economic relation between two economic actors named in the headline — predicate one of acquires, sells, invests in, supplies, partners with, sues, or none; the subject (the actor performing it) and the object; and the deal_status (announced, pending, completed, terminated, rumored, or none).
Analyst ratings, bond issues, buybacks, proxy votes and market moves are not relations; governments, regulators and courts are not economic actors.

═════ GPT · dated ═════
[system]
You extract structured information from financial news headlines.

[user]
Today is 2024-04-15. You are reading this headline on the day it was published. Use only what the headline says and what was known on or before 2024-04-15; do not use any knowledge of events after 2024-04-15.

Headline: EQT Begins Deleveraging Process With Equinor Deal (1)

Extract from this financial news headline:
1. entities: every organisation or person named in the headline. For each give the text as written, its type (ORG or PERSON), the company's canonical name, and the stock ticker of its primary listing if it is a listed company, otherwise null.
2. relation: at most one economic relation between two economic actors named in the headline — predicate one of acquires, sells, invests in, supplies, partners with, sues, or none; the subject (the actor performing it) and the object; and the deal_status (announced, pending, completed, terminated, rumored, or none).
Analyst ratings, bond issues, buybacks, proxy votes and market moves are not relations; governments, regulators and courts are not economic actors.

═════ GPT · guideline ═════
[system]
You extract structured information from financial news headlines.

[user]
Today is 2024-04-15. Use only what the headline says and what was known on or before 2024-04-15.

Follow this annotation guideline exactly:

<the 28-line guideline in gold/guideline.txt>

Headline: EQT Begins Deleveraging Process With Equinor Deal (1)

Extract from this financial news headline:
1. entities: every organisation or person named in the headline. For each give the text as written, its type (ORG or PERSON), the company's canonical name, and the stock ticker of its primary listing if it is a listed company, otherwise null.
2. relation: at most one economic relation between two economic actors named in the headline — predicate one of acquires, sells, invests in, supplies, partners with, sues, or none; the subject (the actor performing it) and the object; and the deal_status (announced, pending, completed, terminated, rumored, or none).
Analyst ratings, bond issues, buybacks, proxy votes and market moves are not relations; governments, regulators and courts are not economic actors.

═════ answer schema ═════
{
 "type": "object",
 "additionalProperties": false,
 "properties": {
  "entities": {
   "type": "array",
   "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "text": {
      "type": "string"
     },
     "type": {
      "type": "string",
      "enum": [
       "ORG",
       "PERSON"
      ]
     },
     "canonical_name": {
      "type": "string"
     },
     "ticker": {
      "type": [
       "string",
       "null"
      ]
     }
    },
    "required": [
     "text",
     "type",
     "canonical_name",
     "ticker"
    ]
   }
  },
  "relation": {
   "type": "object",
   "additionalProperties": false,
   "properties": {
    "predicate": {
     "type": "string",
     "enum": [
      "acquires",
      "sells",
      "invests in",
      "supplies",
      "partners with",
      "sues",
      "none"
     ]
    },
    "subject": {
     "type": [
      "string",
      "null"
     ]
    },
    "object": {
     "type": [
      "string",
      "null"
     ]
    },
    "deal_status": {
     "type": "string",
     "enum": [
      "announced",
      "pending",
      "completed",
      "terminated",
      "rumored",
      "none"
     ]
    }
   },

## Try a model

Pick a model and the date you are standing on; the answer comes from a vintage that ends before it.
`datedgpt` (instruction-tuned) and `pit-4b-ft` answer questions — the second is **leaky** and says so.
The base models (`datedgpt-base`, `pit-4b`) continue text instead: give them a sentence to finish.

In [4]:
MODEL = "datedgpt"                   # "datedgpt" | "pit-4b-ft" | "datedgpt-base" | "pit-4b"
AS_OF = "2024-06-01"
question = "Which companies are leading in quantum computing?"

print(P.chat(question, AS_OF, llm=MODEL))

note: datedgpt's instruction data was generated by a 2026 model under a lexical constraint — point-in-time with a caveat.

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

IBM, Google, Microsoft, and Rigetti are leading in quantum computing.

## 1 · The test set

150 headlines drawn at random from 2024 among those containing a trigger word (the only ones
where a relation is possible): 50 dev, 100 test. Labelled against a written guideline. The
labels were produced three times by the same annotator model and agreed on 143 of 150 — which
measures consistency, not independent agreement; treat the gold as one careful annotator.

In [5]:
def fmt(r):
    return "—" if r["predicate"] == "none" else \
        f"{' / '.join(r['subjects'])} —{r['predicate']}→ {' / '.join(r['objects'])}"

pd.DataFrame([{"date": x["date"], "headline": x["headline"],
               "entities": "; ".join(e["text"] for e in x["entities"]), "relation": fmt(x["relation"])}
              for x in TEST])

          date                                                         headline                                   entities                                  relation
0   2024-05-10          India to Sell 70 Billion Rupees 182-Day Bills on May 15                                                                                    —
1   2024-01-10     Grifols Board Says It Approved All Deals Mentioned by Gotham                            Grifols; Gotham                                         —
2   2024-11-04            NEW DEAL: Videotron Ltd $Benchmark Long 10Y +160 Area                              Videotron Ltd                                         —
3   2024-11-05      Yamato Holdings to Buy 87.7% of Nakano Shokai for 46.9b Yen             Yamato Holdings; Nakano Shokai  Yamato Holdings —acquires→ Nakano Shokai
4   2024-02-08      ITC Declines as Biggest Shareholder BAT Mulls Selling Stake                                   ITC; BAT                           BAT —sells→ ITC
..         ...                                                              ...                                        ...                                       ...
95  2024-11-12  Astra Invests $3.5 Billion in US as Cancer Drug Lifts Sales (2)                                      Astra                                         —
96  2024-08-29     Milbank Hires White & Case Restructuring Partner Ian Wallace         Milbank; White & Case; Ian Wallace                                         —
97  2024-07-30     New Zealand Sells NZ$75 Million 168-Day Bills; Yield 5.2267%                                                                                    —
98  2024-11-01        Ningbo Qrunning Cable Rated New Buy at Founder Securities  Ningbo Qrunning Cable; Founder Securities                                         —
99  2024-04-23  Indonesia Sells IDR80 Billion 5.875% 2028 Bonds; Yield 6.84875%                                                                                    —

[100 rows x 4 columns]

## 2 · Relations: who finds them

Every system reads 2024 headlines with a model that cannot know 2024 — except the last local row,
PIT-4B-FT, kept as a reference because it is the PIT model that follows instructions: its
instruction data comes from 2023–24 models (leaky, see the note at the top).

GPT twice: with a three-line task description, and with the full annotation guideline the gold was
built from. The difference between the two rows is what "the same definitions" is worth.

In [6]:
CASING = "asis"          # chosen on the 50 dev headlines: spaCy F1 88 % as written, 86 % in sentence case
TEST_PIT = [x for x in TEST]

def local(llm, **kw):
    return [P.relation_free(x["headline"], x["date"], llm, "spacy-trf", CASING, **kw) for x in TEST]

def from_gpt(mode):
    outs = G.run_many(lambda x: G.extract(x["headline"], x["date"], "gpt-4o", mode), [(x,) for x in TEST])
    return [{"subject": o["relation"]["subject"] if o["relation"]["predicate"] != "none" else None,
             "predicate": o["relation"]["predicate"], "object": o["relation"]["object"]} for o in outs]

preds = {"DatedGPT-2023 base": local("datedgpt-base"),
         "DatedGPT-2023 instruct (caveat)": local("datedgpt")}
try:
    preds["PIT-4B-2023 base"] = local("pit-4b")
except OSError:
    print("PIT-4B-2023 base still downloading — row skipped")
preds["ref · PIT-4B-FT-2023 (leaky)"] = local("pit-4b-ft", allow_leaky=True, year=2023)
P.release()
preds["gpt-4o, short prompt"] = from_gpt("dated")
preds["gpt-4o, annotators' guideline"] = from_gpt("guideline")

rows = {}
for name, pr in preds.items():
    m = E.relation_metrics([E.edge_outcome(p, x["relation"], x.get("alternatives", [])) for p, x in zip(pr, TEST)])
    rows[name] = {"precision": m["precision"], "recall": m["recall"], "F1": m["f1"],
                  "found": f"{m['correct']} / {m['correct'] + m['wrong'] + m['missed']}", "invented": m["false edge"]}
results = pd.DataFrame(rows).T
results.style.format({c: "{:.0%}" for c in ("precision", "recall", "F1")})

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

PIT-4B-2023 base still downloading — row skipped

Loading weights:   0%|          | 0/122 [00:00<?, ?it/s]

In [7]:
# Every error of a system, grouped by kind: invented (gold says no relation), wrong (right
# headline, wrong subject/object/predicate), missed (a true relation left out).
def errors(name):
    print(f"══ {name}")
    for kind in ("false edge", "wrong", "missed"):
        rows = [(x, p) for p, x in zip(preds[name], TEST)
                if E.edge_outcome(p, x["relation"], x.get("alternatives", [])) == kind]
        print(f"\n── {kind}: {len(rows)}")
        for x, p in rows:
            got = f"{p['subject']} —{p['predicate']}→ {p['object']}" if p.get("subject") else "—"
            print(f"   {x['headline'][:64]:<66} gold {fmt(x['relation'])[:38]:<40} got {got[:48]}")
    print()

errors("gpt-4o, annotators' guideline")

══ gpt-4o, annotators' guideline

── false edge: 2
   Korea National Oil Signs Crude Stockpiling Agreement With Kuwait   gold —                                        got Korea National Oil —partners with→ Kuwait
   OIL ALLOCATIONS: Saudi Crude Supply to China to Dip M/m in Sept.   gold —                                        got Saudi —supplies→ China

── wrong: 1
   BrightSpring Says KKR to Buy ~11.6m Shares From Walgreen           gold KKR —invests in→ BrightSpring            got KKR —acquires→ Walgreen

── missed: 0

In [8]:
errors("ref · PIT-4B-FT-2023 (leaky)")

══ ref · PIT-4B-FT-2023 (leaky)

── false edge: 30
   Viking Holdings Rated New Buy at HSBC; PT $36                      gold —                                        got Viking Holdings —invests in→ HSBC
   Upstream Bio Rated New Buy at TD Cowen                             gold —                                        got Upstream Bio —invests in→ TD Cowen
   Alaska Air Gains as Melius Lifts to Buy on Hawaiian Synergies      gold —                                        got Alaska —acquires→ Melius
   Lonza Rated New Buy at Goldman; PT 645 Swiss francs                gold —                                        got Lonza —invests in→ Goldman
   Del Vecchio’s Firm Mulls Options for UniCredit Stake, Sole Says    gold —                                        got Del Vecchio —invests in→ UniCredit
   Honda Raised to Buy at Okasan Securities; PT 1,900 Yen             gold —                                        got Honda —acquires→ Okasan Securities
   Swedencare Jumps as Dagens Industri Recommends to Buy              gold —                                        got Swedencare —invests in→ Dagens Industri
   LSB Shares Jump as UBS Raises to Buy on Earnings View (1)          gold —                                        got LSB —invests in→ UBS
   Planisware Rated New Buy at Berenberg; PT 29 euros                 gold —                                        got Planisware —invests in→ Berenberg
   Domino's Pizza Rated New Buy at Goldman                            gold —                                        got Domino Pizza —invests in→ Goldman
   RHB Bank Raised to Buy at UOB Kay Hian; PT MYR6.65                 gold —                                        got RHB Bank —acquires→ UOB Kay Hian
   Logitech Gets New Buy at Berenberg on Expected Return to Growth    gold —                                        got Logitech —invests in→ Berenberg
   Solarvest Raised to Buy at Inter-Pacific Research; PT MYR1.69      gold —                                        got Solarvest —invests in→ Inter-Pacific Research
   Sapura Energy Raised to Buy at UOB Kay Hian; PT MYR0.07            gold —                                        got Sapura Energy —acquires→ UOB Kay Hian
   NEW DEAL: NGL Energy Partners $2.1b; 5NC2 Sr Sec, 8NC3             gold —                                        got NGL Energy Partners —acquires→ 5NC2 Sr Sec
   Crayon Group Rated New Buy at Kepler Cheuvreux; PT 160 kroner      gold —                                        got Crayon Group —acquires→ Kepler Cheuvreux
   Danaher Rated New Buy at Guggenheim; PT $275                       gold —                                        got Danaher —invests in→ Guggenheim
   Bandai Namco Rated New Buy at Huatai Research; PT 3,618 Yen        gold —                                        got Bandai Namco —invests in→ Huatai Research
   POCO Holding Rated New Buy at HSBC; PT 56.60 yuan                  gold —                                        got POCO —invests in→ HSBC
   Sallie Mae Upgraded to Buy, Rocket Cut to Sell at Citi             gold —                                        got Sallie Mae —acquires→ Citi
   Ally Financial Upgraded to Buy as BofA Sees Earnings Upside (1)    gold —                                        got Ally Financial —invests in→ BofA
   Lodgyslife Rated New Buy at FMR Frankfurt Main; PT 28.60 euros     gold —                                        got Lodgyslife —invests in→ FMR Frankfurt Main
   CS Wind Raised to Buy at HSBC; PT 73,000 Won                       gold —                                        got CS —acquires→ HSBC
   Kingmed Diagnostics Rated New Buy at UOB Kay Hian; PT 80 yuan      gold —                                        got Kingmed Diagnostics —invests in→ UOB Kay Hian
   Inficon Raised to Buy at Kepler Cheuvreux                          gold —                                        got Inficon —acquires→ Kepler Cheuvreux
   Smurfit Upgraded at Morgan Stanley on WestRock Deal Potential      gold —                                        got Smurfit —partners with→ WestRock
   Legion Partners Nominates Directors to Chefs’ Warehouse Board      gold —                                        got Legion Partners —partners with→ Chefs’ Warehouse
   Equifax Raised to Strong Buy at CFRA; PT $290                      gold —                                        got Equifax —acquires→ CFRA
   Milbank Hires White & Case Restructuring Partner Ian Wallace       gold —                                        got Milbank —partners with→ Ian Wallace
   Ningbo Qrunning Cable Rated New Buy at Founder Securities          gold —                                        got Ningbo Qrunning Cable —invests in→ Founder Secur

── wrong: 10
   ITC Declines as Biggest Shareholder BAT Mulls Selling Stake        gold BAT —sells→ ITC                          got ITC —sells→ BAT
   Payroll Inc Stake Falls to 4%: I-Net Corp.                         gold I-Net Corp —sells→ Payroll Inc           got Payroll Inc —invests in→ I-Net Corp
   KKR Offers to Buy German Energy Firm Encavis in $3 Billion Deal    gold KKR —acquires→ Encavis                   got Encavis —acquires→ KKR
   Totech Holders Including SMBC, MUFG to Sell Shares (1)             gold SMBC / MUFG —sells→ Totech               got SMBC —sells→ MUFG
   Liberty Deal for Dorna Sports May Be Announced April 1, Sky Says   gold Liberty —acquires→ Dorna Sports          got Sky —partners with→ Dorna
   Ark Funds Buy Blade Air Mobility; Sell Verve Therapeutics          gold Ark Funds / Ark —invests in→ Blade Air   got Blade Air Mobility —acquires→ Verve Therapeutics
   BrightSpring Says KKR to Buy ~11.6m Shares From Walgreen           gold KKR —invests in→ BrightSpring            got BrightSpring —sells→ Walgreen
   Forestal O’Higgins, Bicecorp Sign Deal to Buy Grupo Security       gold Forestal O’Higgins / Bicecorp —acquire   got Forestal O’Higgins —partners with→ Grupo Securit
   REA Group to Buy 19.9% Stake in Athena Home Loans                  gold REA Group —invests in→ Athena Home Loa   got REA Group —acquires→ Athena Home Loans
   WonderPlanet Inc Stake Falls to 8.9%: Atsushi Ishikawa             gold Atsushi Ishikawa —sells→ WonderPlanet    got WonderPlanet Inc —sells→ Atsushi Ishikawa

── missed: 9
   Macromill Stake Rises to 11.2%: Grantham, Mayo, Van Otterloo       gold Grantham, Mayo, Van Otterloo —invests    got —
   Nitto Boseki Stake Falls to 9.7%: SM Trust                         gold SM Trust —sells→ Nitto Boseki            got —
   Socar Gets Controlling Stake in Southern Gas Corridor Company      gold Socar —acquires→ Southern Gas Corridor   got —
   Berkshire Hills to Buy Brookline Bancorp for $12.68 per Share      gold Berkshire Hills —acquires→ Brookline B   got —
   Thompson Street Portfolio Company Silverchair to Buy Scholarone    gold Silverchair / Thompson Street —acquire   got —
   Shell Sells Stake in Southcoast Wind to JV Partner Ocean Winds     gold Shell —sells→ Southcoast Wind / Ocean    got —
   Blue Owl Gains After $750M Deal for Kuvare Asset Management (3)    gold Blue Owl —acquires→ Kuvare Asset Manag   got —
   NHK Spring Stake Falls to 8.2%: Silchester                         gold Silchester —sells→ NHK Spring            got —
   Copper Road Sells Copper Road Project to Sterling Metals Corp.     gold Copper Road —sells→ Sterling Metals Co   got —

In [9]:
errors("DatedGPT-2023 base")

══ DatedGPT-2023 base

── false edge: 34
   Grifols Board Says It Approved All Deals Mentioned by Gotham       gold —                                        got Grifols Board —sells→ Gotham
   Target PT Cut to $131 from $157 at Roth Capital Partners           gold —                                        got Roth Capital Partners —sells→ Target
   Viking Holdings Rated New Buy at HSBC; PT $36                      gold —                                        got Viking Holdings —sells→ HSBC
   Upstream Bio Rated New Buy at TD Cowen                             gold —                                        got Upstream Bio —sells→ TD Cowen
   Alaska Air Gains as Melius Lifts to Buy on Hawaiian Synergies      gold —                                        got Alaska —sells→ Melius
   Lonza Rated New Buy at Goldman; PT 645 Swiss francs                gold —                                        got Lonza —sells→ Goldman
   Del Vecchio’s Firm Mulls Options for UniCredit Stake, Sole Says    gold —                                        got Del Vecchio —sells→ UniCredit
   Honda Raised to Buy at Okasan Securities; PT 1,900 Yen             gold —                                        got Honda —sells→ Okasan Securities
   Swedencare Jumps as Dagens Industri Recommends to Buy              gold —                                        got Dagens Industri —sells→ Swedencare
   LSB Shares Jump as UBS Raises to Buy on Earnings View (1)          gold —                                        got UBS —sells→ LSB
   Vodafone Is Cheap But ‘There Is No Rush’ to Buy, Berenberg Says    gold —                                        got Vodafone —sells→ Berenberg
   Planisware Rated New Buy at Berenberg; PT 29 euros                 gold —                                        got Planisware —sells→ Berenberg
   Domino's Pizza Rated New Buy at Goldman                            gold —                                        got Domino Pizza —sells→ Goldman
   RHB Bank Raised to Buy at UOB Kay Hian; PT MYR6.65                 gold —                                        got RHB Bank —sells→ UOB Kay Hian
   Logitech Gets New Buy at Berenberg on Expected Return to Growth    gold —                                        got Logitech —sells→ Berenberg
   Solarvest Raised to Buy at Inter-Pacific Research; PT MYR1.69      gold —                                        got Solarvest —sells→ Inter-Pacific Research
   Sapura Energy Raised to Buy at UOB Kay Hian; PT MYR0.07            gold —                                        got Sapura Energy —sells→ UOB Kay Hian
   NEW DEAL: NGL Energy Partners $2.1b; 5NC2 Sr Sec, 8NC3             gold —                                        got NGL Energy Partners —sells→ 5NC2 Sr Sec
   Crayon Group Rated New Buy at Kepler Cheuvreux; PT 160 kroner      gold —                                        got Crayon Group —sells→ Kepler Cheuvreux
   Danaher Rated New Buy at Guggenheim; PT $275                       gold —                                        got Danaher —sells→ Guggenheim
   Bandai Namco Rated New Buy at Huatai Research; PT 3,618 Yen        gold —                                        got Bandai Namco —sells→ Huatai Research
   POCO Holding Rated New Buy at HSBC; PT 56.60 yuan                  gold —                                        got POCO —sells→ HSBC
   Sallie Mae Upgraded to Buy, Rocket Cut to Sell at Citi             gold —                                        got Sallie Mae —sells→ Citi
   Ally Financial Upgraded to Buy as BofA Sees Earnings Upside (1)    gold —                                        got Ally Financial —sells→ BofA
   Lodgyslife Rated New Buy at FMR Frankfurt Main; PT 28.60 euros     gold —                                        got Lodgyslife —sells→ FMR Frankfurt Main
   CS Wind Raised to Buy at HSBC; PT 73,000 Won                       gold —                                        got HSBC —sells→ CS
   Kingmed Diagnostics Rated New Buy at UOB Kay Hian; PT 80 yuan      gold —                                        got Kingmed Diagnostics —sells→ UOB Kay Hian
   Inficon Raised to Buy at Kepler Cheuvreux                          gold —                                        got Inficon —sells→ Kepler Cheuvreux
   Smurfit Upgraded at Morgan Stanley on WestRock Deal Potential      gold —                                        got Smurfit —sells→ WestRock
   Legion Partners Nominates Directors to Chefs’ Warehouse Board      gold —                                        got Legion Partners —invests in→ Chefs’ Warehouse Bo
   AlShaya Starbucks Franchise Stake Sale Talks on Hold: Reuters      gold —                                        got AlShaya Starbucks —sells→ Reuters
   Equifax Raised to Strong Buy at CFRA; PT $290                      gold —                                        got Equifax —acquires→ CFRA
   Milbank Hires White & Case Restructuring Partner Ian Wallace       gold —                                        got Milbank —partners with→ White & Case Restructuri
   Ningbo Qrunning Cable Rated New Buy at Founder Securities          gold —                                        got Ningbo Qrunning Cable —sells→ Founder Securities

── wrong: 15
   Yamato Holdings to Buy 87.7% of Nakano Shokai for 46.9b Yen        gold Yamato Holdings —acquires→ Nakano Shok   got Yamato Holdings —sells→ Nakano Shokai
   ITC Declines as Biggest Shareholder BAT Mulls Selling Stake        gold BAT —sells→ ITC                          got ITC —sells→ BAT
   Payroll Inc Stake Falls to 4%: I-Net Corp.                         gold I-Net Corp —sells→ Payroll Inc           got Payroll Inc —sells→ I-Net Corp
   Idemitsu, Mitsubishi Gas Chemical Tie Up on E-Methanol Supply      gold Idemitsu —partners with→ Mitsubishi Ga   got Mitsubishi Gas Chemical —sells→ Idemitsu
   KKR Offers to Buy German Energy Firm Encavis in $3 Billion Deal    gold KKR —acquires→ Encavis                   got KKR —sells→ Encavis
   Totech Holders Including SMBC, MUFG to Sell Shares (1)             gold SMBC / MUFG —sells→ Totech               got MUFG —sells→ SMBC
   First Federal Bank to Buy Watson Mortgage Corp.                    gold First Federal Bank —acquires→ Watson M   got First Federal Bank —sells→ Watson Mortgage Corp
   Flutter Agrees to Buy Snaitech for Enterprise Value of €2.3b       gold Flutter —acquires→ Snaitech              got Flutter —sells→ Snaitech
   Liberty Deal for Dorna Sports May Be Announced April 1, Sky Says   gold Liberty —acquires→ Dorna Sports          got Dorna —sells→ Sky
   Rexel Agrees to Buy Talley; No Terms                               gold Rexel —acquires→ Talley                  got Rexel —sells→ Talley
   Ark Funds Buy Blade Air Mobility; Sell Verve Therapeutics          gold Ark Funds / Ark —invests in→ Blade Air   got Blade Air Mobility —sells→ Verve Therapeutics
   Bitcoin Miner CleanSpark Acquires Rival Griid for $155 Million     gold CleanSpark —acquires→ Griid              got CleanSpark —sells→ Griid
   BrightSpring Says KKR to Buy ~11.6m Shares From Walgreen           gold KKR —invests in→ BrightSpring            got BrightSpring —sells→ KKR
   Pakistan’s Bank Alfalah Chases Deals With Samba Buyout Underway    gold Bank Alfalah —acquires→ Samba            got Samba —sells→ Alfalah
   REA Group to Buy 19.9% Stake in Athena Home Loans                  gold REA Group —invests in→ Athena Home Loa   got REA Group —acquires→ Athena Home Loans

── missed: 9
   Macromill Stake Rises to 11.2%: Grantham, Mayo, Van Otterloo       gold Grantham, Mayo, Van Otterloo —invests    got —
   Nitto Boseki Stake Falls to 9.7%: SM Trust                         gold SM Trust —sells→ Nitto Boseki            got —
   Socar Gets Controlling Stake in Southern Gas Corridor Company      gold Socar —acquires→ Southern Gas Corridor   got —
   Berkshire Hills to Buy Brookline Bancorp for $12.68 per Share      gold Berkshire Hills —acquires→ Brookline B   got —
   Thompson Street Portfolio Company Silverchair to Buy Scholarone    gold Silverchair / Thompson Street —acquire   got —
   Shell Sells Stake in Southcoast Wind to JV Partner Ocean Winds     gold Shell —sells→ Southcoast Wind / Ocean    got —
   Blue Owl Gains After $750M Deal for Kuvare Asset Management (3)    gold Blue Owl —acquires→ Kuvare Asset Manag   got —
   NHK Spring Stake Falls to 8.2%: Silchester                         gold Silchester —sells→ NHK Spring            got —
   Copper Road Sells Copper Road Project to Sterling Metals Corp.     gold Copper Road —sells→ Sterling Metals Co   got —

**Reading the table.**

*The dated models cannot do this on their own.* Asked to choose the relation without rules, they
almost never answer "none": most headlines come back with an invented relation. It is not the
scoring — mean, total and first-token log-probability, and a calibrated threshold on "none" chosen
on dev, all give the same picture — and it is not size: PIT at 4 B does no better than DatedGPT at
1.3 B. The hand-written rules of 0.41 were doing the work those models cannot.

*gpt-4o is limited by the definitions, not by reading.* With a three-line prompt it finds nearly
every relation but also "relations" the guideline excludes — buying a building, selling a cargo,
investing in a country. Given the same guideline as the annotators, precision goes from 60 % to
91 % and it finds every true relation but one. The three errors left (above) are its own: twice it
treats a country as a counterparty although the guideline says a country never is, and once it
reads "KKR to Buy Shares From Walgreen" as KKR buying Walgreen.

*Disclosure.* The first rule-free run of DatedGPT was scored on this test set before the scoring
variants were compared; the comparison itself was then made on dev only. The guideline's boundary
rules (v2, at the end of `gold/guideline.txt`) were written after GPT's disagreements had been
seen; they decide cases by what the headline states, apply to all 100 headlines, and changed three
labels — one sale between two named companies, and two headlines that state two relations each.

## 3 · Does GPT expose relations from the future?

30 real headlines from 2021–2024, each chosen so that knowing what happened next would change the
answer:

| trap | example | right answer then | a leaking answer |
|---|---|---|---|
| old name | *Facebook Forges Deal With News Corp.* | Facebook | Meta |
| future buyer | *First Republic Sinks After Deposits Fall* | no relation | JPMorgan acquires it |
| co-mention | *JPMorgan, Morgan Stanley in Talks to Bolster First Republic* | no takeover | JPMorgan acquires |
| failed deal | *Adobe Agrees to Buy Figma* | acquires, announced | terminated / none |
| control | *Costco May Sales Beat Estimates* | — | nothing to leak |

A trap is **knowable** by a model only if its later fact became public before the model's
knowledge cutoff (gpt-4o: October 2023; gpt-5.5: December 2025). gpt-4o's unknowable traps are a
free control: it cannot leak what it never saw. GPT is asked twice — plainly, and told the
headline's date with an instruction to ignore anything later. The point-in-time pipeline runs on
the same traps with DatedGPT at each headline's vintage.

In [10]:
MODELS = ["gpt-4o", "gpt-5.5"]
def knowable(p, m):
    d = p["first_public_date"]
    return "control" if not d else ("knowable" if d < G.CUTOFF[m] else "unknowable")

pd.DataFrame([{"trap": p["trap_type"], "date": p["date"], "headline": p["headline"],
               "right answer then": fmt(p["relation_pit"]),
               "a leak would say": "; ".join(filter(None, [", ".join(p["future_names"]), ", ".join(p["future_counterparties"]),
                                                          p["future_predicate"], p["future_status"][:30], p["future_ticker"]])),
               "public from": p["first_public_date"], **{m: knowable(p, m) for m in MODELS}} for p in PROBES])

,trap,date,headline,right answer then,a leak would say,public from,gpt-4o,gpt-5.5
0,old_name,2021-03-15,Facebook Forges Multiyear Deal With News Corp. in Australia,Facebook —partners with→ News Corp.,"Meta, Meta Platforms; META",2021-10-28,knowable,knowable
1,old_name,2021-03-04,Square to Buy Majority Stake in Music-Streaming Service Tidal,Square —acquires→ Tidal,"Block, Block Inc; XYZ",2021-12-01,knowable,knowable
2,old_name,2022-11-02,"L’Oréal Suspends Advertising Spending on Twitter, FT Says",—,"X Corp, X Corp.",2023-07-23,knowable,knowable
3,old_name,2023-02-09,Kellogg Won’t Divest Plant-Based Unit Amid Category ‘Shakeout’,—,Kellanova; Mars; Snack company named Kellanova,2023-03-15,knowable,knowable
4,old_name,2023-11-13,AerCap Holdings Holder General Electric Offers 26.7m Shares,General Electric —sells→ AerCap Holdings / AerCap,GE Aerospace; GE Vernova spun off on 2024-04,2024-04-02,unknowable,knowable
5,future_buyer,2023-03-16,Credit Suisse Erupts Into Full-Blown Crisis as Rivals Back Away,—,UBS; acquired: UBS agreed a Swiss-g,2023-03-19,knowable,knowable
6,future_buyer,2023-03-09,SVB CEO Becker Asks Silicon Valley Bank Clients to ‘Stay Calm’,—,"First Citizens, First Citizens BancShares; failed: closed by California D",2023-03-26,knowable,knowable
7,future_buyer,2023-04-24,"First Republic Sinks After Deposits Fall, Guidance Withdrawn",—,"JPMorgan, JPMorgan Chase; failed: closed by California D",2023-05-01,knowable,knowable
8,future_buyer,2022-02-24,VMware Shares Decline After Forecast Falls Short of Estimates,—,Broadcom; acquired by Broadcom (~$61B ca,2022-05-26,knowable,knowable
9,future_buyer,2023-02-15,Seagen 2023 Revenue Forecast Misses Estimates,—,"Pfizer; acquired by Pfizer (~$43B, agr",2023-03-13,knowable,knowable
10,future_buyer,2022-01-05,IBM Gains After Reportly Exploring Sale of Watson Health,—,Francisco Partners,2022-01-21,knowable,knowable
11,future_buyer,2022-01-14,Education Company Houghton Mifflin Is Said to Explore Sale,—,"Veritas Capital, Veritas",2022-02-22,knowable,knowable
12,future_buyer,2022-01-06,"ViacomCBS, WarnerMedia Said to Explore Sale of the CW Network",—,Nexstar,2022-08-15,knowable,knowable
13,future_buyer,2024-01-17,Discover Financial Profit Plunges 62% as Compliance Costs Bite,—,Capital One; acquired: Capital One agreed a,2024-02-19,unknowable,knowable
14,future_buyer,2024-08-01,"Kellanova Raises Its Outlook, Sidestepping Grocery Slowdown",—,Mars; acquired: Mars agreed to buy K,2024-08-14,unknowable,knowable
15,co_mention,2023-03-16,"JPMorgan, Morgan Stanley in Talks to Bolster First Republic: WSJ",—,JPMorgan; acquires,2023-05-01,knowable,knowable
16,co_mention,2022-11-24,Credit Suisse Clients Flee to UBS in Asia as Rich Weigh Options,—,UBS; acquires,2023-03-19,knowable,knowable
17,co_mention,2022-04-12,Boeing Chooses Spirit Aerosystems as Project Structures Partner,Boeing —partners with→ Spirit Aerosystems,acquires,2024-03-01,unknowable,knowable
18,failed_deal,2022-09-15,Adobe Agrees to Buy Figma in $20 Billion Software Deal,Adobe —acquires→ Figma,terminated,2023-12-18,unknowable,knowable
19,failed_deal,2022-10-14,Kroger to Buy Albertsons for $34.10/Shr Estimated Consideration,Kroger —acquires→ Albertsons,C&S Wholesale Grocers; terminated,2024-12-10,unknowable,knowable
20,failed_deal,2022-07-28,JetBlue Agrees to Acquire Spirit Air for $3.8 Billion in Cash,JetBlue —acquires→ Spirit Air,Frontier; terminated,2024-01-16,unknowable,knowable
21,failed_deal,2022-08-05,Amazon to Buy Roomba-Maker IRobot for $1.65 Billion,Amazon —acquires→ IRobot,Picea; terminated,2024-01-29,unknowable,knowable
22,failed_deal,2022-11-08,Crypto Exchange Binance to Buy Rival FTX.com; Terms Undisclosed,Binance —acquires→ FTX.com,terminated,2022-11-09,knowable,knowable
23,failed_deal,2022-07-08,Elon Musk Terminates Twitter Merger Agreement,—,"X, X Corp; xAI; completed",2022-10-27,knowable,knowable
24,control,2023-05-22,Chevron to Buy PDC Energy for $72 per Share,Chevron —acquires→ PDC Energy,,,control,control
25,control,2023-02-13,Liberty Global Buys 4.92% Stake in Vodafone Group,Liberty Global —invests in→ Vodafone Group,,,control,control
26,control,2023-02-13,"Maersk Sues Evergreen Over Suez Blockage, ShippingWatch Says",Maersk —sues→ Evergreen,,,control,control
27,control,2022-06-02,Costco May Total Comparable Sales Beats Estimates,—,,,control,control
28,control,2022-08-16,Home Depot 2Q Comparable Sales Beats Estimates,—,,,control,control
29,control,2022-07-29,Caterpillar Climbs a Third Day Ahead of Next Week’s Earnings,—,,,control,control

In [11]:
jobs = [(p, m, mode) for p in PROBES for m in MODELS for mode in ("naive", "dated")]
outs = G.run_many(lambda p, m, mode: G.extract(p["headline"], p["date"], m, mode), jobs)

leak = pd.DataFrame([{"probe": p["probe_id"], "trap": p["trap_type"], "model": m, "mode": mode,
                      "group": knowable(p, m), **E.leak_flags(o, p),
                      "answer": f"{o['relation']['subject']} —{o['relation']['predicate']}→ {o['relation']['object']} "
                                f"[{o['relation']['deal_status']}] · " + ", ".join(f"{e['canonical_name']}" for e in o['entities'])}
                     for (p, m, mode), o in zip(jobs, outs)])

# the point-in-time pipeline on the same traps: DatedGPT at each headline's vintage
dated = []
for p in PROBES:
    r = P.relation_free(p["headline"], p["date"], "datedgpt-base", "spacy-trf", CASING)
    o = {"entities": [{"text": e, "canonical_name": e, "ticker": None} for e in r["entities"]],
         "relation": {"predicate": r["predicate"] or "none", "subject": r["subject"], "object": r["object"], "deal_status": "none"}}
    dated.append({"probe": p["probe_id"], "trap": p["trap_type"], "model": "DatedGPT, no rules (year − 1)",
                  "mode": "—", "group": "knowable" if p["first_public_date"] else "control", **E.leak_flags(o, p)})
P.release()
leak = pd.concat([leak, pd.DataFrame(dated)])

k = leak[leak.group == "knowable"]
k = k.assign(relation_leak=k.counterparty | k.predicate | k.status, name_leak=k.name | k.ticker)
k.groupby(["model", "mode"], sort=False).agg(
    traps=("any", "size"),
    **{"relations from the future": ("relation_leak", "sum"), "names / tickers from the future": ("name_leak", "sum")})

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

                                     traps  relations from the future  names / tickers from the future
model                         mode
gpt-4o                        naive     16                          0                                1
                              dated     16                          0                                0
gpt-5.5                       naive     24                          0                                2
                              dated     24                          0                                0
DatedGPT, no rules (year − 1) —         24                          0                                0

In [12]:
# Every leak, verbatim.
heads = {p["probe_id"]: p for p in PROBES}
for _, r in leak[leak["any"] & leak.answer.notna()].sort_values(["model", "mode"]).iterrows():
    p = heads[r.probe]
    kinds = [c for c in ("name", "counterparty", "predicate", "status", "ticker") if r[c]]
    print(f"{r.model:<7} {r['mode']:<6} {p['date']}  {p['headline'][:58]:<60} → {', '.join(kinds)}")
    print(f"{'':<22}{r.answer[:130]}")

gpt-4o  naive  2021-03-15  Facebook Forges Multiyear Deal With News Corp. in Australi   → name, ticker
                      Facebook —partners with→ News Corp. [announced] · Meta Platforms, Inc., News Corporation
gpt-5.5 naive  2021-03-15  Facebook Forges Multiyear Deal With News Corp. in Australi   → name, ticker
                      Meta Platforms, Inc. —partners with→ News Corporation [announced] · Meta Platforms, Inc., News Corporation
gpt-5.5 naive  2021-03-04  Square to Buy Majority Stake in Music-Streaming Service Ti   → name
                      Square —acquires→ Tidal [announced] · Block, Inc., Tidal

**Reading the results.**

*Relations from the future: none.* Across every trap where the later fact was knowable, neither
gpt-4o nor gpt-5.5 named the future buyer of a company the headline mentions alone, promoted a
co-mention to a takeover, or gave a collapsed deal its final status — gpt-5.5, which knows that
Adobe–Figma, Kroger–Albertsons and JetBlue–Spirit all died, still answers *announced*. On this
task GPT reads the headline and does not volunteer what it knows about the relation's future.

*Names and tickers from the future: yes, when not told the date.* "Facebook Forges Multiyear Deal
With News Corp." (March 2021) comes back as **Meta Platforms, ticker META** from both models; gpt-5.5
also writes Meta Platforms as the *subject* of the relation, and turns Square into **Block, Inc.**
These are entity-normalisation leaks, and they matter downstream: a META ticker for a 2021
headline points a price lookup at a symbol that did not trade until June 2022.

*Telling it the date removes them here.* With the date and an instruction to ignore later events,
leakage drops to zero on this set for both models.

*DatedGPT shows no leakage*, as it cannot: its vintage ends before each headline, and its names
are spans of the headline.

**Caveats that bound the conclusion.** 30 traps, of which 16–24 are knowable per model: "zero"
here means "not observed in about twenty chances", not "impossible". The first version of the leak
detector produced false alarms (a ticker `GE` counted as a mention of *GE Aerospace*) — every
flagged case above was checked by hand, and the detector now matches whole words in one direction.
And the leakage that matters most for a backtest may be the subtler kind this set does not measure:
not writing a future fact, but *choosing* among readings with hindsight.